### ISSUE TITLE
Crash in vicadmin test

### ISSUE THREAD

**Issue by corrieb** [vmware/vic#1297]
See https://ci.vmware.run/vmware/vic/2440

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0xadc34a]

goroutine 100 [running]:
panic(0x1014d00, 0xc820012130)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
bufio.(*Writer).flush(0xc8203c1b40, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:562 +0xda
bufio.(*Writer).Flush(0xc8203c1b40, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:551 +0x2d
net/http.(*response).Flush(0xc8204adee0)
	/usr/local/go/src/net/http/server.go:1301 +0x45
github.com/vmware/vic/cmd/vicadmin.(*flushWriter).Write(0xc82038f0a0, 0xc820930000, 0x1, 0x8000, 0x1, 0x0, 0x0)
	github.com/vmware/vic/cmd/vicadmin/_test/_obj_test/vicadm.go:898 +0xcd
io.copyBuffer(0x7f42fef6ac70, 0xc82038f0a0, 0x7f42fef9e540, 0xc820026050, 0xc820930000, 0x8000, 0x8000, 0x177, 0x0, 0x0)
	/usr/local/go/src/io/io.go:382 +0x2c9
io.Copy(0x7f42fef6ac70, 0xc82038f0a0, 0x7f42fef9e540, 0xc820026050, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:350 +0x64
os/exec.(*Cmd).writerDescriptor.func1(0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:236 +0x8b
os/exec.(*Cmd).Start.func1(0xc8202e4a00, 0xc82038f2e0)
	/usr/local/go/src/os/exec/exec.go:344 +0x1d
created by os/exec.(*Cmd).Start
	/usr/local/go/src/os/exec/exec.go:345 +0x967
exit status 2
FAIL	github.com/vmware/vic/cmd/vicadmin	0.692s
Makefile:205: recipe for target 'test' failed
make: *** [test] Error 1
[info] build failed (exit code 2)

**Comment by corrieb** [comment]
Seems like we're crashing here: in bufio.go:
n, err := b.wr.Write(b.buf[0:b.n])

I suspect we may need to check for a nil slice here in vicadmin.go:
func (fw *flushWriter) Write(p []byte) (int, error) {
	n, err := fw.w.Write(p)

	fw.f.Flush()

	return n, err
}

**Comment by corrieb** [comment]
Unable to reproduce locally. Timing bug? Looping test 100 times to see

**Comment by corrieb** [comment]
Nope. the byte[] arg cannot be nil. See io.go:

	if buf == nil {
		buf = make([]byte, 32*1024)
	}
	for {
		nr, er := src.Read(buf)
		if nr > 0 {
			nw, ew := dst.Write(buf[0:nr])

**Comment by corrieb** [comment]
Ran the test 100 times locally. Did not fail once.

**Comment by corrieb** [comment]
Only think I can conclude from the line it crashed on is that the underlying buffered writer had a nil io.Writer field. I can't see why or how that could have happened.

Ultimately I don't believe this is a bug in our code.
