### ISSUE TITLE
vic-admin crash on log retreval

### ISSUE THREAD

**Issue by mlh78750** [vmware/vic#1358]
Build 2588

Fresh install on esx6.0u2

Ran a busybox container. 
Went to vicadmin page to pull logs. 

container-logs.tar.gz returns empty response.
tail/vicadmin.log hangs

I will attach the full vicadmin log which shows panics in the response code.

**Comment by mlh78750** [comment]
[vicadmin.log.txt](https://github.com/vmware/vic/files/350103/vicadmin.log.txt)

Example panic from log: 
`2016/06/18 02:37:58 http: panic serving 172.16.252.1:62865: assignment to entry in nil map
goroutine 21 [running]:
net/http.(*conn).serve.func1(0xc820467d00)
	/usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0xda47a0, 0xc820336ba0)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
main.findDatastoreLogs(0xc82046c780, 0x0, 0x0, 0x0)
	/drone/src/github.com/vmware/vic/cmd/vicadmin/vicadm.go:410 +0xc35
main.(*server).tarContainerLogs(0xc820207b80, 0x7f051f212428, 0xc8201849c0, 0xc820180620)
	/drone/src/github.com/vmware/vic/cmd/vicadmin/vicadm.go:745 +0x2c7
main.(*server).(main.tarContainerLogs)-fm(0x7f051f212428, 0xc8201849c0, 0xc820180620)
	/drone/src/github.com/vmware/vic/cmd/vicadmin/vicadm.go:688 +0x3e
net/http.HandlerFunc.ServeHTTP(0xc820249f30, 0x7f051f212428, 0xc8201849c0, 0xc820180620)
	/usr/local/go/src/net/http/server.go:1618 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc820273230, 0x7f051f212428, 0xc8201849c0, 0xc820180620)
	/usr/local/go/src/net/http/server.go:1910 +0x17d
net/http.serverHandler.ServeHTTP(0xc820265f80, 0x7f051f212428, 0xc8201849c0, 0xc820180620)
	/usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820467d00)
	/usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2137 +0x44e`
