### ISSUE TITLE
Link/Alias resolution not working in bridge network

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#1459]
First there is a panic in the personality during `network connect` - I was using an external network but didn't seem to matter whether it was an external network or the bridge that was first or second:
```
2016/07/13 10:13:58 http: panic serving 192.168.78.202:52582: runtime error: invalid memory address or nil pointer dereference
goroutine 44 [running]:
net/http.(*conn).serve.func1(0xc820363d80)
	/usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0x1579a40, 0xc82000e080)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/vmware/vic/lib/apiservers/engine/backends.EP2Alias(0x0, 0x0, 0x0, 0x0)
	/C/Users/georg/Documents/VMware/VIC/src/github.com/vmware/vic/lib/apiservers/engine/backends/network.go:163 +0x5da
github.com/vmware/vic/lib/apiservers/engine/backends.(*Network).ConnectContainerToNetwork(0x26e4278, 0xc82034c0c0, 0x40, 0xc82012a270, 0x8, 0x0, 0x0, 0x0)
	/C/Users/georg/Documents/VMware/VIC/src/github.com/vmware/vic/lib/apiservers/engine/backends/network.go:198 +0x602
github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/network.(*networkRouter).postNetworkConnect(0xc820233cb0, 0x7fbcbf0d60d8, 0xc82038cab0, 0x7fbcbf0d1f20, 0xc82078c680, 0xc8207815e0, 0xc82038c990, 0x0, 0x0)
	/C/Users/georg/Documents/VMware/VIC/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/network/network_routes.go:124 +0x361
github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/network.(*networkRouter).(github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/network.postNetworkConnect)-fm(0x7fbcbf0d60d8, 0xc82038cab0, 0x7fbcbf0d1f20, 0xc82078c680, 0xc8207815e0, 0xc82038c990, 0x0, 0x0)
	/C/Users/georg/Documents/VMware/VIC/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/network/network.go:32 +0x74
github.com/vmware/vic/vendor/github.com/docker/docker/api/server/middleware.NewVersionMiddleware.func1.1(0x7fbcbf0d60d8, 0xc82038cab0, 0x7fbcbf0d1f20, 0xc82078c680, 0xc8207815e0, 0xc82038c990, 0x0, 0x0)
	/C/Users/georg/Documents/VMware/VIC/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/middleware/version.go:42 +0xa43
github.com/vmware/vic/vendor/github.com/docker/docker/api/server/middleware.NewUserAgentMiddleware.func1.1(0x7fbcbf0d60d8, 0xc82038ca50, 0x7fbcbf0d1f20, 0xc82078c680, 0xc8207815e0, 0xc82038c990, 0x0, 0x0)
	/C/Users/georg/Documents/VMware/VIC/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/middleware/user_agent.go:34 +0x6a9
github.com/vmware/vic/vendor/github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7fbcbf0d1f20, 0xc82078c680, 0xc8207815e0)
	/C/Users/georg/Documents/VMware/VIC/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/server.go:132 +0x138
net/http.HandlerFunc.ServeHTTP(0xc82041a940, 0x7fbcbf0d1f20, 0xc82078c680, 0xc8207815e0)
	/usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/vmware/vic/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc8202310e0, 0x7fbcbf0d1f20, 0xc82078c680, 0xc8207815e0)
	/C/Users/georg/Documents/VMware/VIC/src/github.com/vmware/vic/vendor/github.com/gorilla/mux/mux.go:103 +0x270
github.com/vmware/vic/vendor/github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc8202183e0, 0x7fbcbf0d1f20, 0xc82078c680, 0xc8207815e0)
	/C/Users/georg/Documents/VMware/VIC/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router_swapper.go:29 +0x72
net/http.serverHandler.ServeHTTP(0xc82027ae80, 0x7fbcbf0d1f20, 0xc82078c680, 0xc8207815e0)
	/usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820363d80)
	/usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2137 +0x44e
```

Adding a simple guard for nil around the `EP2Alias` call seems to work around that and network connect works as expected, however aliases do not:

```
vagrant@devbox:~/vic$ docker -H 192.168.78.212:2376 --tls run --link=e554b5ec7bf7fa5762296af044561c1996bb313a080e881eabf75cf66dee826a:mine -it busybox
/ # ping mine
ping: bad address 'mine'
/ #
/ # ping notthere
ping: bad address 'notthere'
/ #
```

from the PL log we can see that the first should work but is not:
```
time="2016-07-13T10:52:28Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/dns.(*Server).ServeDNS] ;; opcode: QUERY, status: NOERROR, id: 2\n;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0\n\n;; QUESTION SECTION:\n;mine.\tIN\t AAAA\n" 
time="2016-07-13T10:52:28Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/dns.(*Server).SeenBefore] ;; opcode: QUERY, status: NOERROR, id: 2\n;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0\n\n;; QUESTION SECTION:\n;mine.\tIN\t AAAA\n" 
time="2016-07-13T10:52:28Z" level=debug msg="Cache hit for \";; opcode: QUERY, status: NOERROR, id: 2\\n;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0\\n\\n;; QUESTION SECTION:\\n;mine.\\tIN\\t AAAA\\n\"" 
time="2016-07-13T10:52:28Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/dns.(*Server).SeenBefore] [536.152µs] ;; opcode: QUERY, status: NOERROR, id: 2\n;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0\n\n;; QUESTION SECTION:\n;mine.\tIN\t AAAA\n" 
time="2016-07-13T10:52:28Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/dns.(*Server).ServeDNS] [944.962µs] ;; opcode: QUERY, status: NOERROR, id: 2\n;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0\n\n;; QUESTION SECTION:\n;mine.\tIN\t AAAA\n" 
time="2016-07-13T10:52:28Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/dns.(*Server).ServeDNS] ;; opcode: QUERY, status: NOERROR, id: 3\n;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0\n\n;; QUESTION SECTION:\n;mine.\tIN\t A\n" 
time="2016-07-13T10:52:28Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/dns.(*Server).SeenBefore] ;; opcode: QUERY, status: NOERROR, id: 3\n;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0\n\n;; QUESTION SECTION:\n;mine.\tIN\t A\n" 
time="2016-07-13T10:52:28Z" level=debug msg="Cache hit for \";; opcode: QUERY, status: NOERROR, id: 3\\n;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0\\n\\n;; QUESTION SECTION:\\n;mine.\\tIN\\t A\\n\"" 
time="2016-07-13T10:52:28Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/dns.(*Server).SeenBefore] [85.356µs] ;; opcode: QUERY, status: NOERROR, id: 3\n;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0\n\n;; QUESTION SECTION:\n;mine.\tIN\t A\n" 
time="2016-07-13T10:52:28Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/dns.(*Server).ServeDNS] [160.294µs] ;; opcode: QUERY, status: NOERROR, id: 3\n;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0\n\n;; QUESTION SECTION:\n;mine.\tIN\t A\n" 
time="2016-07-13T10:55:49Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/dns.(*Server).ServeDNS] ;; opcode: QUERY, status: NOERROR, id: 2\n;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0\n\n;; QUESTION SECTION:\n;notthere.\tIN\t AAAA\n" 
time="2016-07-13T10:55:49Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/dns.(*Server).SeenBefore] ;; opcode: QUERY, status: NOERROR, id: 2\n;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0\n\n;; QUESTION SECTION:\n;notthere.\tIN\t AAAA\n" 
time="2016-07-13T10:55:49Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/dns.(*Server).SeenBefore] [27.25µs] ;; opcode: QUERY, status: NOERROR, id: 2\n;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0\n\n;; QUESTION SECTION:\n;notthere.\tIN\t AAAA\n" 
time="2016-07-13T10:55:49Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/dns.(*Server).HandleVIC] ;; opcode: QUERY, status: NOERROR, id: 2\n;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0\n\n;; QUESTION SECTION:\n;notthere.\tIN\t AAAA\n" 
time="2016-07-13T10:55:49Z" level=debug msg="RemoteAddr: 172.16.0.8" 
time="2016-07-13T10:55:49Z" level=debug msg="Found the scope, using bridge" 
time="2016-07-13T10:55:49Z" level=debug msg="Can't find the container: \"bridge:notthere\"" 
time="2016-07-13T10:55:49Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/dns.(*Server).HandleVIC] [857.931µs] ;; opcode: QUERY, status: NOERROR, id: 2\n;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0\n\n;; QUESTION SECTION:\n;notthere.\tIN\t AAAA\n" 
time="2016-07-13T10:55:49Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/dns.(*Server).HandleForwarding] ;; opcode: QUERY, status: NOERROR, id: 2\n;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0\n\n;; QUESTION SECTION:\n;notthere.\tIN\t AAAA\n" 
time="2016-07-13T10:55:49Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/dns.(*Server).HandleForwarding] [26.162466ms] ;; opcode: QUERY, status: NOERROR, id: 2\n;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0\n\n;; QUESTION SECTION:\n;notthere.\tIN\t AAAA\n" 
time="2016-07-13T10:55:49Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/dns.(*Server).ServeDNS] [28.875048ms] ;; opcode: QUERY, status: NOERROR, id: 2\n;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0\n\n;; QUESTION SECTION:\n;notthere.\tIN\t AAAA\n" 
time="2016-07-13T10:55:49Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/dns.(*Server).ServeDNS] ;; opcode: QUERY, status: NOERROR, id: 3\n;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0\n\n;; QUESTION SECTION:\n;notthere.\tIN\t A\n" 
time="2016-07-13T10:55:49Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/dns.(*Server).SeenBefore] ;; opcode: QUERY, status: NOERROR, id: 3\n;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0\n\n;; QUESTION SECTION:\n;notthere.\tIN\t A\n" 
time="2016-07-13T10:55:49Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/dns.(*Server).SeenBefore] [2.332µs] ;; opcode: QUERY, status: NOERROR, id: 3\n;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0\n\n;; QUESTION SECTION:\n;notthere.\tIN\t A\n" 
time="2016-07-13T10:55:49Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/dns.(*Server).HandleVIC] ;; opcode: QUERY, status: NOERROR, id: 3\n;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0\n\n;; QUESTION SECTION:\n;notthere.\tIN\t A\n" 
time="2016-07-13T10:55:49Z" level=debug msg="RemoteAddr: 172.16.0.8" 
time="2016-07-13T10:55:49Z" level=debug msg="Found the scope, using bridge" 
time="2016-07-13T10:55:49Z" level=debug msg="Can't find the container: \"bridge:notthere\"" 
time="2016-07-13T10:55:49Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/dns.(*Server).HandleVIC] [28.988µs] ;; opcode: QUERY, status: NOERROR, id: 3\n;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0\n\n;; QUESTION SECTION:\n;notthere.\tIN\t A\n" 
time="2016-07-13T10:55:49Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/dns.(*Server).HandleForwarding] ;; opcode: QUERY, status: NOERROR, id: 3\n;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0\n\n;; QUESTION SECTION:\n;notthere.\tIN\t A\n" 
time="2016-07-13T10:55:49Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/dns.(*Server).HandleForwarding] [1.153434ms] ;; opcode: QUERY, status: NOERROR, id: 3\n;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0\n\n;; QUESTION SECTION:\n;notthere.\tIN\t A\n" 
time="2016-07-13T10:55:49Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/dns.(*Server).ServeDNS] [1.272365ms] ;; opcode: QUERY, status: NOERROR, id: 3\n;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0\n\n;; QUESTION SECTION:\n;notthere.\tIN\t A\n" 
```

Not sure why the DNs queries are doubling up - some sort of retry in ping?

**Comment by hickeng** [comment]
The reason for this issue is the following block of code that attempts to emulate docker specific behaviour:
https://github.com/vmware/vic/commit/bd666d8422573c02712e22514f98a5467da12f66#diff-6e989557b980355774bd4187364245fbR768

I'm not going to remove it for now, but I would like to know which of the following the intent was:
1. suppress alias resolution and support for the default bridge network
2. suppress returning the alias data in inspect output

I'm of the opinion that we should support links in the default bridge env irrespective of dockers behaviour in this case. We **must** either support it or return an error that links are not supported on the default network as this silent squash has caused me significant frustration and will do so for users.

@mlh78750 for opinion on which solution.

**Comment by mlh78750** [comment]
@hickeng: At least one person wants to mix new and legacy and still have stuff work.
https://github.com/docker/docker/issues/22803

That being said, I am not sure how allowing the link commands to work on the default network will result in backwards compatibility issues. Docker claims that it will cause issues because the --link code is not dns based. Since all of our resolution is DNS based and we are not banging stuff into /etc/hosts I think diverging from docker in this case and supporting --link in "legacy" default bridge is fine. If it does become a backwards compatible issue in the future, we could always make that a feature that can be turned off via VCH config.

**Comment by corrieb** [comment]
Since this is unresolved for TP3, it will need to move to onsite

**Comment by sflxn** [comment]
https://github.com/vmware/vic/pull/1480 will fix this.

**Comment by caglar10ur** [comment]
Unfortunately we can't do this without changing docker client code as they filter out links in the client side (https://github.com/docker/docker/blob/de64324109d2694b1525e62b5c0072267282a36c/runconfig/opts/parse.go#L613)

**Comment by caglar10ur** [comment]
https://github.com/docker/docker/blob/792adb7199634941d1151c798a267918d9a6aa7a/api/client/container/create.go#L62 

https://github.com/docker/docker/blob/792adb7199634941d1151c798a267918d9a6aa7a/api/client/container/run.go#L80

**Comment by caglar10ur** [comment]
Cleared the milestone target

**Comment by hickeng** [comment]
@caglar10ur @hmahmood Do we _have_ to have our networks be of type "bridge"? Do you know what other behaviour is hung off that predicate?

**Comment by hmahmood** [comment]
There is also a "external" network type, but I do not believe links/aliases are supported for that type (and neither should they be in my opinion). So yes, for now "bridge" is required for this to work. I have been looking at this for the past few days via #2294

**Comment by dougm** [comment]
Robot tests need to be updated:

```
tests/test-cases/Group1-Docker-Commands/1-4-Docker-Create.robot:74:    ${status}=  Get State Of Github Issue  1459
tests/test-cases/Group1-Docker-Commands/1-4-Docker-Create.robot:75:    Run Keyword If  '${status}' == 'closed'  Fail  Test 1-4-Docker-Create.robot needs to be updated now that Issue #1459 has been resolved
tests/test-cases/Group1-Docker-Commands/1-4-Docker-Create.robot:76:    Log  Issue \#1459 is blocking implementation  WARN
tests/test-cases/Group1-Docker-Commands/1-6-Docker-Run.robot:50:    ${status}=  Get State Of Github Issue  1459
tests/test-cases/Group1-Docker-Commands/1-6-Docker-Run.robot:51:    Run Keyword If  '${status}' == 'closed'  Fail  Test 1-6-Docker-Run.robot needs to be updated now that Issue #1459 has been resolved
tests/test-cases/Group1-Docker-Commands/1-6-Docker-Run.robot:52:    Log  Issue \#1459 is blocking implementation  WARN
```

**Comment by dougm** [comment]
https://ci.vmware.run/vmware/vic/5099
