### ISSUE TITLE
docker api server needs to check imagec binary before trying to use it

### ISSUE THREAD

**Issue by caglar10ur** [vmware/vic#162]
```
serving docker at http://127.0.0.1:2376
serving docker at https://127.0.0.1:55193
2016/02/26 11:58:57 http: panic serving 127.0.0.1:55200: runtime error: invalid memory address or nil pointer dereference
goroutine 34 [running]:
net/http.(*conn).serve.func1(0xc82001ad00)
	/usr/local/Cellar/go/1.6/libexec/src/net/http/server.go:1389 +0xc1
panic(0x4db760, 0xc820012110)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:426 +0x4e9
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.(*errorResp).WriteResponse(0xc820217c00, 0x9bef78, 0xc82047b790, 0x0, 0x0)
	/opt/go/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/not_implemented.go:40 +0x288
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.(*Context).Respond(0xc8202fb500, 0x9bef78, 0xc82047b790, 0xc82034d260, 0xc820427760, 0x2, 0x2, 0xc82034d340, 0x4b7c20, 0xc820217c00)
	/opt/go/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/context.go:384 +0x674
github.com/vmware/vic/apiservers/docker/restapi/operations/misc.(*GetSystemInformation).ServeHTTP(0xc820356da0, 0x9bef78, 0xc82047b790, 0xc82034d260)
	/opt/go/src/github.com/vmware/vic/apiservers/docker/restapi/operations/misc/get_system_information.go:52 +0x20b
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.newOperationExecutor.func1(0x9bef78, 0xc82047b790, 0xc82034d260)
	/opt/go/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/operation.go:23 +0x6f
net/http.HandlerFunc.ServeHTTP(0xc8200f8ad0, 0x9bef78, 0xc82047b790, 0xc82034d260)
	/usr/local/Cellar/go/1.6/libexec/src/net/http/server.go:1618 +0x3a
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.newRouter.func1(0x9bef78, 0xc82047b790, 0xc82034d260)
	/opt/go/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/router.go:85 +0x663
net/http.HandlerFunc.ServeHTTP(0xc820342280, 0x9bef78, 0xc82047b790, 0xc82034d260)
	/usr/local/Cellar/go/1.6/libexec/src/net/http/server.go:1618 +0x3a
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.specMiddleware.func1(0x9bef78, 0xc82047b790, 0xc82034d260)
	/opt/go/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/spec.go:36 +0x1d1
net/http.HandlerFunc.ServeHTTP(0xc820289f00, 0x9bef78, 0xc82047b790, 0xc82034d260)
	/usr/local/Cellar/go/1.6/libexec/src/net/http/server.go:1618 +0x3a
net/http.serverHandler.ServeHTTP(0xc820310b00, 0x9bef78, 0xc82047b790, 0xc82034d260)
	/usr/local/Cellar/go/1.6/libexec/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc82001ad00)
	/usr/local/Cellar/go/1.6/libexec/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.6/libexec/src/net/http/server.go:2137 +0x44e
2016/02/26 11:58:57 Error starting /vmware/vic/binary/imagec - fork/exec /vmware/vic/binary/imagec: no such file or directory
```

**Comment by mdubya66** [comment]
Closing as not an issue. Let's re-open this if we see it again.
