### ISSUE TITLE
ValueError: Container 05efd8b1a0 does not have a com.docker.compose.container-number label

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#1734]
Running docker compose with a LEMP server yml file, caused the following error:
```
 	Pulling vic.mysql (mysql:latest)...
latest: Pulling from library/mysql
Digest: sha256:0d8465f6e13e7f56680e47a24159e8ebbe93c1c3c679e15bb44511e7bfcac5a9
Status: Downloaded newer image for library/mysql:latest
Creating vic.mysql
Pulling vic.php (php:7.0-fpm)...
7.0-fpm: Pulling from library/php
Digest: sha256:ac5cfcef5ba3874cbc68d17b159e48ab76170171ddd8f6e960e9918ced55e4f7
Status: Downloaded newer image for library/php:7.0-fpm
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.5.2', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 54, in main
    command.sys_dispatch()
  File "/usr/lib/python2.7/dist-packages/compose/cli/docopt_command.py", line 23, in sys_dispatch
    self.dispatch(sys.argv[1:], None)
  File "/usr/lib/python2.7/dist-packages/compose/cli/docopt_command.py", line 26, in dispatch
    self.perform_command(*self.parse(argv, global_options))
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 171, in perform_command
    handler(project, command_options)
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 546, in up
    detached=detached
  File "/usr/lib/python2.7/dist-packages/compose/project.py", line 264, in up
    detached=detached
  File "/usr/lib/python2.7/dist-packages/compose/service.py", line 389, in execute_convergence_plan
    container = self.create_container(do_build=do_build)
  File "/usr/lib/python2.7/dist-packages/compose/service.py", line 292, in create_container
    number or self._next_container_number(one_off=one_off),
  File "/usr/lib/python2.7/dist-packages/compose/service.py", line 523, in _next_container_number
    numbers = [c.number for c in containers]
  File "/usr/lib/python2.7/dist-packages/compose/container.py", line 87, in number
    self.short_id, LABEL_CONTAINER_NUMBER))
ValueError: Container 05efd8b1a0 does not have a com.docker.compose.container-number label
```

Attaching logs as well.
[VCH-0-3949-container-logs.tar.gz](https://github.com/vmware/vic/files/389506/VCH-0-3949-container-logs.tar.gz)

[robot-logs.zip](https://github.com/vmware/vic/files/389510/robot-logs.zip)

**Comment by hickeng** [comment]
We're lacking both:
* compose support #431 
* label support

This is most likely an artifact of those two issues. Until #431 is complete it's hard to determine what the actual issue is here.
Assigning to @caglar10ur for follow up as he's been looking at compose.

**Comment by sflxn** [comment]
I have a fix for this.  I had to fix it to get basic compose to work.
