### ISSUE TITLE
docker ps panic traces in port-layer.log

### ISSUE THREAD

**Issue by caglar10ur** [vmware/vic#1767]
```
time="2016-08-01T22:56:16Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).GetContainerListHandler] [19.573791ms] Containers.GetContainerListHandler" 
2016/08/01 22:56:16 http: panic serving 10.118.69.159:42728: runtime error: invalid memory address or nil pointer dereference
goroutine 361 [running]:
net/http.(*conn).serve.func1(0xc420486180)
	/usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0xdcecc0, 0xc42000e050)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/vmware/vic/lib/portlayer/exec.convertInfraContainers(0xc4206b8000, 0x3, 0x4, 0xc420b7100d, 0x3, 0x4, 0x0)
	/opt/go/src/github.com/vmware/vic/lib/portlayer/exec/container.go:414 +0x137
github.com/vmware/vic/lib/portlayer/exec.List(0x7f97fc549908, 0xc42000e468, 0xc4202a0690, 0xc420b7100d, 0xc42000e468, 0x71, 0xecf31ca90, 0x2ba6e7bb, 0x192cba0)
	/opt/go/src/github.com/vmware/vic/lib/portlayer/exec/container.go:354 +0x7e
github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).GetContainerListHandler(0xc42042c078, 0xc42036a000, 0xc420b7100d, 0x0, 0x0)
	/opt/go/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers/containers_handlers.go:250 +0x127
github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).GetContainerListHandler-fm(0xc42036a000, 0xc420b7100d, 0x30003c420320201, 0xc420b71060)
	/opt/go/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers/containers_handlers.go:54 +0x3e
github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/containers.GetContainerListHandlerFunc.Handle(0xc42065ee50, 0xc42036a000, 0xc420b7100d, 0x18fa1a0, 0xc420b71060)
	/opt/go/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/containers/get_container_list.go:17 +0x3a
github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/containers.(*GetContainerList).ServeHTTP(0xc420ac4c20, 0x1906860, 0xc4200db790, 0xc42036a000)
	/opt/go/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/containers/get_container_list.go:49 +0x18f
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.newOperationExecutor.func1(0x1906860, 0xc4200db790, 0xc42036a000)
	/opt/go/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/operation.go:23 +0x69
net/http.HandlerFunc.ServeHTTP(0xc420746200, 0x1906860, 0xc4200db790, 0xc42036a000)
	/usr/local/go/src/net/http/server.go:1726 +0x44
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.newRouter.func1(0x1906860, 0xc4200db790, 0xc42036a000)
	/opt/go/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/router.go:78 +0x555
net/http.HandlerFunc.ServeHTTP(0xc42079b100, 0x1906860, 0xc4200db790, 0xc42036a000)
	/usr/local/go/src/net/http/server.go:1726 +0x44
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.specMiddleware.func1(0x1906860, 0xc4200db790, 0xc42036a000)
	/opt/go/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/spec.go:36 +0x7b
net/http.HandlerFunc.ServeHTTP(0xc420827ae0, 0x1906860, 0xc4200db790, 0xc42036a000)
	/usr/local/go/src/net/http/server.go:1726 +0x44
net/http.serverHandler.ServeHTTP(0xc4205a2c00, 0x1906860, 0xc4200db790, 0xc42036a000)
	/usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc420486180, 0x19073e0, 0xc4205fae00)
	/usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2295 +0x447
time="2016-08-01T22:56:20Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/portlayer/exec.(*Container).Commit] [21.301155681s] Committing handle" 
time="2016-08-01T22:56:20Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).CommitHandler] 
```

**Comment by caglar10ur** [comment]
we observed this failure after restarting the container vm manually via vc ui and run docker ps

**Comment by cgtexmex** [comment]
Closing as I'm unable to recreate.

**Comment by stuclem** [comment]
This is unreproduceable. Removing kind/note.
