### ISSUE TITLE
Close of closed channel

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#1790]
Follow on issue from #1788 

From journalctl output - when looking into why vic-init didn't keep relaunching the components:
```

Aug 03 03:47:56 VCH-3578-1398 vic-init[204]: time="2016-08-03T03:47:56Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/tether.(*tether).handleSessionExit] [69.953462ms] handling exit of session docker-personality"
Aug 03 03:47:56 VCH-3578-1398 vic-init[204]: panic: close of closed channel
Aug 03 03:47:56 VCH-3578-1398 vic-init[204]: goroutine 8 [running]:
Aug 03 03:47:56 VCH-3578-1398 vic-init[204]: panic(0xc479e0, 0xc8202e1200)
Aug 03 03:47:56 VCH-3578-1398 vic-init[204]: /usr/local/go/src/runtime/panic.go:481 +0x3e6
Aug 03 03:47:56 VCH-3578-1398 vic-init[204]: github.com/vmware/vic/lib/tether.(*tether).handleSessionExit(0xc820201880, 0xc8200718c0)
Aug 03 03:47:56 VCH-3578-1398 vic-init[204]: /drone/src/github.com/vmware/vic/lib/tether/tether.go:325 +0x6d5
Aug 03 03:47:56 VCH-3578-1398 vic-init[204]: github.com/vmware/vic/lib/tether.(*tether).childReaper.func1.1(0xc820223f64, 0xc820201880)
Aug 03 03:47:56 VCH-3578-1398 vic-init[204]: /drone/src/github.com/vmware/vic/lib/tether/tether_linux.go:96 +0x5f9
Aug 03 03:47:56 VCH-3578-1398 vic-init[204]: github.com/vmware/vic/lib/tether.(*tether).childReaper.func1(0xc820201880)
Aug 03 03:47:56 VCH-3578-1398 vic-init[204]: /drone/src/github.com/vmware/vic/lib/tether/tether_linux.go:106 +0x7d
Aug 03 03:47:56 VCH-3578-1398 vic-init[204]: created by github.com/vmware/vic/lib/tether.(*tether).childReaper
Aug 03 03:47:56 VCH-3578-1398 vic-init[204]: /drone/src/github.com/vmware/vic/lib/tether/tether_linux.go:108 +0x2bc
Aug 03 03:47:56 VCH-3578-1398 systemd[1]: vic-init.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 03 03:47:56 VCH-3578-1398 systemd[1]: vic-init.service: Unit entered failed state.
Aug 03 03:47:56 VCH-3578-1398 systemd[1]: vic-init.service: Failed with result 'exit-code'.
```

**Comment by hickeng** [comment]
@dougm Not sure what the path is to hit this, but it's happening...
