### ISSUE TITLE
Re-launch failure in cmd/tether unit test

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#1801]
cmd/tether issue from build:
```
time="2016-08-03T21:14:04Z" level=warning msg="Re-launching process for session pathlookup (count: 11)" 
time="2016-08-03T21:14:04Z" level=info msg="Passing config to mocker" 
time="2016-08-03T21:14:04Z" level=info msg="pathlookup exit code: 0" 
time="2016-08-03T21:14:04Z" level=error msg="unable to encode []*executor.ExitLog (slice) for guestinfo..sessions|pathlookup.diagnostics.exitlogs: *executor.ExitLog is an unhandled type" 
time="2016-08-03T21:14:04Z" level=info msg="Reload triggered" 
time="2016-08-03T21:14:04Z" level=info msg="Loading main configuration" 
time="2016-08-03T21:14:04Z" level=info msg="Loaded executor config" 
time="2016-08-03T21:14:04Z" level=warning msg="Re-launching process for session pathlookup (count: 12)" 
time="2016-08-03T21:14:04Z" level=info msg="Reaped zombie process PID 15060\n" 
Failed to run date for comparison data: wait: no child processestime="2016-08-03T21:14:04Z" level=info msg="Passing config to mocker" 
time="2016-08-03T21:14:04Z" level=info msg="pathlookup exit code: 0" 
time="2016-08-03T21:14:04Z" level=error msg="unable to encode []*executor.ExitLog (slice) for guestinfo..sessions|pathlookup.diagnostics.exitlogs: *executor.ExitLog is an unhandled type" 
SIGQUIT: quit
PC=0x462d63 m=2

goroutine 0 [idle]:
runtime.futex(0x1bbec90, 0x0, 0x7f9f1e188db8, 0x0, 0x0, 0x462b6c, 0x3c, 0x0, 0x410bdb, 0x1bbec90, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:307 +0x23
runtime.futexsleep(0x1bbec90, 0x0, 0xdf8475800)
	/usr/local/go/src/runtime/os1_linux.go:57 +0xf0
runtime.notetsleep_internal(0x1bbec90, 0xdf8475800, 0xc820000900)
	/usr/local/go/src/runtime/lock_futex.go:174 +0x12b
runtime.notetsleep(0x1bbec90, 0xdf8475800, 0x45a43178ea17e)
	/usr/local/go/src/runtime/lock_futex.go:194 +0x6b
runtime.sysmon()
	/usr/local/go/src/runtime/proc.go:3480 +0x487
runtime.mstart1()
	/usr/local/go/src/runtime/proc.go:1098 +0xec
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1068 +0x72

goroutine 1 [chan receive, 9 minutes]:
testing.RunTests(0x144ae60, 0x1b9ec00, 0x1, 0x1, 0x4bed01)
	/usr/local/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc820034f08, 0xc8201f5e30)
	/usr/local/go/src/testing/testing.go:515 +0x81
github.com/vmware/vic/cmd/vic-init.TestMain(0xc820034f08)
	/drone/src/github.com/vmware/vic/cmd/vic-init/tether_test.go:168 +0x41
main.main()
	github.com/vmware/vic/cmd/vic-init/_test/_testmain.go:100 +0x253

goroutine 17 [syscall, 9 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [syscall, 9 minutes]:
os/signal.signal_recv(0x7f9f1e8d8078)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 18 [chan receive, 9 minutes]:
github.com/vmware/vic/cmd/vic-init.testTeardown(0xc82021a000)
	/drone/src/github.com/vmware/vic/cmd/vic-init/tether_test.go:242 +0x75
github.com/vmware/vic/cmd/vic-init.TestRestart(0xc82021a000)
	/drone/src/github.com/vmware/vic/cmd/vic-init/restart_test.go:98 +0x113e
testing.tRunner(0xc82021a000, 0x1b9ec00)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892

goroutine 19 [chan receive, 9 minutes]:
github.com/vmware/vic/lib/tether.(*tether).Start(0xc82011a980, 0x0, 0x0)
	/drone/src/github.com/vmware/vic/lib/tether/tether.go:170 +0x1e9
github.com/vmware/vic/cmd/vic-init.StartTether.func1(0xc82021a000)
	/drone/src/github.com/vmware/vic/cmd/vic-init/tether_test.go:186 +0x2f
created by github.com/vmware/vic/cmd/vic-init.StartTether
	/drone/src/github.com/vmware/vic/cmd/vic-init/tether_test.go:190 +0x307

goroutine 20 [select, 9 minutes, locked to thread]:
runtime.gopark(0x144b648, 0xc82001e728, 0x11517d0, 0x6, 0x18, 0x2)
	/usr/local/go/src/runtime/proc.go:262 +0x163
runtime.selectgoImpl(0xc82001e728, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa67
runtime.selectgo(0xc82001e728)
	/usr/local/go/src/runtime/select.go:215 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:279 +0x358
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 21 [chan send, 9 minutes]:
github.com/vmware/vic/cmd/vic-init.(*Mocker).HandleSessionExit.func1()
	/drone/src/github.com/vmware/vic/cmd/vic-init/tether_test.go:117 +0x3f
github.com/vmware/vic/lib/tether.(*tether).handleSessionExit(0xc82011a980, 0xc82012e480)
	/drone/src/github.com/vmware/vic/lib/tether/tether.go:321 +0x6bd
github.com/vmware/vic/lib/tether.(*tether).childReaper.func1.1(0xc820035f84, 0xc82011a980)
	/drone/src/github.com/vmware/vic/lib/tether/tether_linux.go:96 +0x5f9
github.com/vmware/vic/lib/tether.(*tether).childReaper.func1(0xc82011a980)
	/drone/src/github.com/vmware/vic/lib/tether/tether_linux.go:106 +0x7d
created by github.com/vmware/vic/lib/tether.(*tether).childReaper
	/drone/src/github.com/vmware/vic/lib/tether/tether_linux.go:108 +0x2bc

goroutine 22 [IO wait, 9 minutes]:
net.runtime_pollWait(0x7f9f1e8ddac0, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8200161b0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200161b0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820016150, 0x0, 0x7f9f1e8ddbb8, 0xc8200bd060)
	/usr/local/go/src/net/fd_unix.go:426 +0x27c
net.(*TCPListener).AcceptTCP(0xc820026038, 0x5e55b1, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc820026038, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2427 +0x41
net/http.(*Server).Serve(0xc82007e200, 0x7f9f1e8ddb80, 0xc820026038, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2117 +0x129
net/http.(*Server).ListenAndServe(0xc82007e200, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2098 +0x136
net/http.ListenAndServe(0x1155f00, 0xc, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2195 +0x98
github.com/vmware/vic/cmd/vic-init.(*Mocker).Start.func1()
	/drone/src/github.com/vmware/vic/cmd/vic-init/tether_test.go:74 +0x3c
created by github.com/vmware/vic/cmd/vic-init.(*Mocker).Start
	/drone/src/github.com/vmware/vic/cmd/vic-init/tether_test.go:75 +0x37

goroutine 23 [chan send (nil chan), 9 minutes]:
os/exec.(*Cmd).Start.func1(0xc82012e4f0, 0xc82023e740)
	/usr/local/go/src/os/exec/exec.go:344 +0x5b
created by os/exec.(*Cmd).Start
	/usr/local/go/src/os/exec/exec.go:345 +0x967

rax    0xfffffffffffffffc
rbx    0x7f9f1e188db8
rcx    0x462d63
rdx    0x0
rdi    0x1bbec90
rsi    0x0
rbp    0x0
rsp    0x7f9f1e188d80
r8     0x0
r9     0x0
r10    0x7f9f1e188db8
r11    0x246
r12    0x2c
r13    0x1449168
r14    0x0
r15    0x8
rip    0x462d63
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
*** Test killed with quit: ran too long (10m0s).
FAIL	github.com/vmware/vic/cmd/vic-init	600.005s
make: *** [test] Error 1
Makefile:223: recipe for target 'test' failed
[info] build failed (exit code 2)
```

**Comment by caglar10ur** [comment]
should be fixed with #2702 - closing
