### ISSUE TITLE
nil pointer in vicadmin

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#1836]
Unable to get a log bundle due to nil pointers in vicadmin:

```
root@VCH-3703-1037 [ /var/log/vic ]# cat vicadmin.log
time="2016-08-05T21:35:36Z" level=info msg="Launching vicadmin server on 127.0.0.1:6061"
time="2016-08-05T21:35:36Z" level=info msg="Current UID/GID = 1000/1000"
time="2016-08-05T21:35:36Z" level=debug msg="[ END ] [main.init.1] [278.254908ms] "
time="2016-08-05T21:35:36Z" level=debug msg="[BEGIN] [main.(*server).listen]"
time="2016-08-05T21:35:36Z" level=debug msg="[ END ] [main.(*server).listen] [2.890002ms] "
time="2016-08-05T21:35:36Z" level=info msg="listening on :2378"
time="2016-08-05T21:35:36Z" level=debug msg="[BEGIN] [main.(*server).serve]"
time="2016-08-05T21:35:36Z" level=debug msg="[BEGIN] [main.(*server).handleFunc]"
time="2016-08-05T21:35:36Z" level=debug msg="[ END ] [main.(*server).handleFunc] [1.13µs] "
time="2016-08-05T21:35:36Z" level=debug msg="[BEGIN] [main.(*server).handleFunc]"
time="2016-08-05T21:35:36Z" level=debug msg="[ END ] [main.(*server).handleFunc] [728ns] "
time="2016-08-05T21:35:36Z" level=debug msg="[BEGIN] [main.logFiles]"
time="2016-08-05T21:35:36Z" level=debug msg="[ END ] [main.logFiles] [4.19µs] "
time="2016-08-05T21:35:36Z" level=debug msg="[BEGIN] [main.(*server).handleFunc]"
time="2016-08-05T21:35:36Z" level=debug msg="[ END ] [main.(*server).handleFunc] [635ns] "
time="2016-08-05T21:35:36Z" level=debug msg="[BEGIN] [main.(*server).handleFunc]"
time="2016-08-05T21:35:36Z" level=debug msg="[ END ] [main.(*server).handleFunc] [707ns] "
time="2016-08-05T21:35:36Z" level=debug msg="[BEGIN] [main.(*server).handleFunc]"
time="2016-08-05T21:35:36Z" level=debug msg="[ END ] [main.(*server).handleFunc] [686ns] "
time="2016-08-05T21:35:36Z" level=debug msg="[BEGIN] [main.(*server).handleFunc]"
time="2016-08-05T21:35:36Z" level=debug msg="[ END ] [main.(*server).handleFunc] [2.176µs] "
time="2016-08-05T21:35:36Z" level=debug msg="[BEGIN] [main.(*server).handleFunc]"
time="2016-08-05T21:35:36Z" level=debug msg="[ END ] [main.(*server).handleFunc] [662ns] "
time="2016-08-05T21:35:36Z" level=debug msg="[BEGIN] [main.(*server).handleFunc]"
time="2016-08-05T21:35:36Z" level=debug msg="[ END ] [main.(*server).handleFunc] [465ns] "
time="2016-08-05T21:35:36Z" level=debug msg="[BEGIN] [main.(*server).handleFunc]"
time="2016-08-05T21:35:36Z" level=debug msg="[ END ] [main.(*server).handleFunc] [493ns] "
time="2016-08-05T21:35:36Z" level=debug msg="[BEGIN] [main.(*server).handleFunc]"
time="2016-08-05T21:35:36Z" level=debug msg="[ END ] [main.(*server).handleFunc] [490ns] "
time="2016-08-05T21:35:36Z" level=debug msg="[BEGIN] [main.(*server).handleFunc]"
time="2016-08-05T21:35:36Z" level=debug msg="[ END ] [main.(*server).handleFunc] [538ns] "
time="2016-08-05T21:35:36Z" level=debug msg="[BEGIN] [main.(*server).handleFunc]"
time="2016-08-05T21:35:36Z" level=debug msg="[ END ] [main.(*server).handleFunc] [492ns] "
time="2016-08-05T21:35:36Z" level=debug msg="[BEGIN] [main.configureReaders]"
time="2016-08-05T21:35:36Z" level=debug msg="[BEGIN] [main.logFiles]"
time="2016-08-05T21:35:36Z" level=debug msg="[ END ] [main.logFiles] [3.34µs] "
time="2016-08-05T21:35:36Z" level=debug msg="[BEGIN] [main.findDatastore]"
time="2016-08-05T21:35:36Z" level=debug msg="[BEGIN] [main.client]"
time="2016-08-05T21:35:41Z" level=debug msg="[ END ] [main.client] [4.927418654s] "
time="2016-08-05T21:35:41Z" level=debug msg="[ END ] [main.findDatastore] [4.927452739s] "
time="2016-08-05T21:35:41Z" level=warning msg="Failed to log in to https://192.168.31.13/sdk: ServerFaultCode: Cannot complete login due to an incorrect user name or password."
time="2016-08-05T21:35:41Z" level=debug msg="[ END ] [main.configureReaders] [4.927532766s] "
2016/08/05 22:09:39 http: TLS handshake error from 192.168.89.2:64582: tls: first record does not look like a TLS handshake
time="2016-08-05T22:09:48Z" level=debug msg="[BEGIN] [main.(*server).index]"
time="2016-08-05T22:09:48Z" level=debug msg="[BEGIN] [main.client]"
2016/08/05 22:09:49 http: TLS handshake error from 192.168.89.2:64583: EOF
time="2016-08-05T22:09:55Z" level=debug msg="[ END ] [main.client] [6.924460893s] "
time="2016-08-05T22:09:55Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/vicadmin.NewValidator]"
time="2016-08-05T22:09:55Z" level=info msg="Creating new validator"
time="2016-08-05T22:09:55Z" level=info msg="Setting version to "
time="2016-08-05T22:09:55Z" level=info msg="Setting hostname to VCH-3703-1037"
time="2016-08-05T22:09:55Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/install/validate.CreateFromVCHConfig]"
time="2016-08-05T22:09:55Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/install/validate.CreateFromVCHConfig] [870ns] "
time="2016-08-05T22:09:55Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).CheckFirewall]"
time="2016-08-05T22:09:55Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).CheckFirewall] [27.834µs] "
time="2016-08-05T22:09:55Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/vicadmin.NewValidator] [184.631µs] "
time="2016-08-05T22:09:55Z" level=debug msg="[ END ] [main.(*server).index] [6.924935384s] "
2016/08/05 22:09:55 http: panic serving 192.168.89.2:64732: runtime error: invalid memory address or nil pointer dereference
goroutine 21 [running]:
net/http.(*conn).serve.func1(0xc82026ab80)
        /usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0x1076120, 0xc82000e080)
        /usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/vmware/vic/lib/install/validate.(*Validator).sessionValid(0xc82024a9a0, 0x13d46d0, 0x16, 0x0)
        /drone/src/github.com/vmware/vic/lib/install/validate/validator.go:221 +0x63
github.com/vmware/vic/lib/install/validate.(*Validator).CheckFirewall(0xc82024a9a0, 0x7fa5961a5de8, 0xc82000ef38)
        /drone/src/github.com/vmware/vic/lib/install/validate/config.go:48 +0x1ea
github.com/vmware/vic/lib/vicadmin.NewValidator(0x7fa5961a5de8, 0xc82000ef38, 0x1e36540, 0x0, 0x0)
        /drone/src/github.com/vmware/vic/lib/vicadmin/validate.go:62 +0x63d
main.(*server).index(0xc820237440, 0x7fa5961b2440, 0xc8200bc340, 0xc82024a460)
        /drone/src/github.com/vmware/vic/cmd/vicadmin/server.go:259 +0x174
main.(*server).(main.index)-fm(0x7fa5961b2440, 0xc8200bc340, 0xc82024a460)
        /drone/src/github.com/vmware/vic/cmd/vicadmin/server.go:136 +0x3e
net/http.HandlerFunc.ServeHTTP(0xc820282030, 0x7fa5961b2440, 0xc8200bc340, 0xc82024a460)
        /usr/local/go/src/net/http/server.go:1618 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc820276a20, 0x7fa5961b2440, 0xc8200bc340, 0xc82024a460)
        /usr/local/go/src/net/http/server.go:1910 +0x17d
net/http.serverHandler.ServeHTTP(0xc82026a380, 0x7fa5961b2440, 0xc8200bc340, 0xc82024a460)
        /usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc82026ab80)
        /usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2137 +0x44e
time="2016-08-05T22:09:56Z" level=debug msg="[BEGIN] [main.(*server).index]"
time="2016-08-05T22:09:56Z" level=debug msg="[BEGIN] [main.client]"
time="2016-08-05T22:10:03Z" level=debug msg="[ END ] [main.client] [6.682047489s] "
time="2016-08-05T22:10:03Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/vicadmin.NewValidator]"
time="2016-08-05T22:10:03Z" level=info msg="Creating new validator"
time="2016-08-05T22:10:03Z" level=info msg="Setting version to "
time="2016-08-05T22:10:03Z" level=info msg="Setting hostname to VCH-3703-1037"
time="2016-08-05T22:10:03Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/install/validate.CreateFromVCHConfig]"
time="2016-08-05T22:10:03Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/install/validate.CreateFromVCHConfig] [1.313µs] "
time="2016-08-05T22:10:03Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).CheckFirewall]"
time="2016-08-05T22:10:03Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).CheckFirewall] [18.357µs] "
time="2016-08-05T22:10:03Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/vicadmin.NewValidator] [118.463µs] "
time="2016-08-05T22:10:03Z" level=debug msg="[ END ] [main.(*server).index] [6.682266622s] "
2016/08/05 22:10:03 http: panic serving 192.168.89.2:64917: runtime error: invalid memory address or nil pointer dereference
goroutine 27 [running]:
net/http.(*conn).serve.func1(0xc8203fca80)
        /usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0x1076120, 0xc82000e080)
        /usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/vmware/vic/lib/install/validate.(*Validator).sessionValid(0xc82024b340, 0x13d46d0, 0x16, 0x0)
        /drone/src/github.com/vmware/vic/lib/install/validate/validator.go:221 +0x63
github.com/vmware/vic/lib/install/validate.(*Validator).CheckFirewall(0xc82024b340, 0x7fa5961a5de8, 0xc82000ef38)
        /drone/src/github.com/vmware/vic/lib/install/validate/config.go:48 +0x1ea
github.com/vmware/vic/lib/vicadmin.NewValidator(0x7fa5961a5de8, 0xc82000ef38, 0x1e36540, 0x0, 0x0)
        /drone/src/github.com/vmware/vic/lib/vicadmin/validate.go:62 +0x63d
main.(*server).index(0xc820237440, 0x7fa5961b2440, 0xc8200bc8f0, 0xc82024ae00)
        /drone/src/github.com/vmware/vic/cmd/vicadmin/server.go:259 +0x174
main.(*server).(main.index)-fm(0x7fa5961b2440, 0xc8200bc8f0, 0xc82024ae00)
        /drone/src/github.com/vmware/vic/cmd/vicadmin/server.go:136 +0x3e
net/http.HandlerFunc.ServeHTTP(0xc820282030, 0x7fa5961b2440, 0xc8200bc8f0, 0xc82024ae00)
        /usr/local/go/src/net/http/server.go:1618 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc820276a20, 0x7fa5961b2440, 0xc8200bc8f0, 0xc82024ae00)
        /usr/local/go/src/net/http/server.go:1910 +0x17d
net/http.serverHandler.ServeHTTP(0xc82026a380, 0x7fa5961b2440, 0xc8200bc8f0, 0xc82024ae00)
        /usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc8203fca80)
        /usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2137 +0x44e
time="2016-08-05T22:10:09Z" level=debug msg="[BEGIN] [main.(*server).index]"
time="2016-08-05T22:10:09Z" level=debug msg="[BEGIN] [main.client]"
time="2016-08-05T22:10:15Z" level=debug msg="[ END ] [main.client] [5.994881788s] "
time="2016-08-05T22:10:15Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/vicadmin.NewValidator]"
time="2016-08-05T22:10:15Z" level=info msg="Creating new validator"
time="2016-08-05T22:10:15Z" level=info msg="Setting version to "
time="2016-08-05T22:10:15Z" level=info msg="Setting hostname to VCH-3703-1037"
time="2016-08-05T22:10:15Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/install/validate.CreateFromVCHConfig]"
time="2016-08-05T22:10:15Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/install/validate.CreateFromVCHConfig] [17.808µs] "
time="2016-08-05T22:10:15Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).CheckFirewall]"
time="2016-08-05T22:10:15Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).CheckFirewall] [44.023µs] "
time="2016-08-05T22:10:15Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/vicadmin.NewValidator] [2.790921ms] "
time="2016-08-05T22:10:15Z" level=debug msg="[ END ] [main.(*server).index] [5.999446791s] "
2016/08/05 22:10:15 http: panic serving 192.168.89.2:64919: runtime error: invalid memory address or nil pointer dereference
goroutine 33 [running]:
net/http.(*conn).serve.func1(0xc820456200)
        /usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0x1076120, 0xc82000e080)
        /usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/vmware/vic/lib/install/validate.(*Validator).sessionValid(0xc82024bdc0, 0x13d46d0, 0x16, 0x0)
        /drone/src/github.com/vmware/vic/lib/install/validate/validator.go:221 +0x63
github.com/vmware/vic/lib/install/validate.(*Validator).CheckFirewall(0xc82024bdc0, 0x7fa5961a5de8, 0xc82000ef38)
        /drone/src/github.com/vmware/vic/lib/install/validate/config.go:48 +0x1ea
github.com/vmware/vic/lib/vicadmin.NewValidator(0x7fa5961a5de8, 0xc82000ef38, 0x1e36540, 0x0, 0x0)
        /drone/src/github.com/vmware/vic/lib/vicadmin/validate.go:62 +0x63d
main.(*server).index(0xc820237440, 0x7fa5961b2440, 0xc8200bcdd0, 0xc82024b7a0)
        /drone/src/github.com/vmware/vic/cmd/vicadmin/server.go:259 +0x174
main.(*server).(main.index)-fm(0x7fa5961b2440, 0xc8200bcdd0, 0xc82024b7a0)
        /drone/src/github.com/vmware/vic/cmd/vicadmin/server.go:136 +0x3e
net/http.HandlerFunc.ServeHTTP(0xc820282030, 0x7fa5961b2440, 0xc8200bcdd0, 0xc82024b7a0)
        /usr/local/go/src/net/http/server.go:1618 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc820276a20, 0x7fa5961b2440, 0xc8200bcdd0, 0xc82024b7a0)
        /usr/local/go/src/net/http/server.go:1910 +0x17d
net/http.serverHandler.ServeHTTP(0xc82026a380, 0x7fa5961b2440, 0xc8200bcdd0, 0xc82024b7a0)
        /usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820456200)
        /usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2137 +0x44e
time="2016-08-05T22:10:46Z" level=debug msg="[BEGIN] [main.(*server).index]"
time="2016-08-05T22:10:46Z" level=debug msg="[BEGIN] [main.client]"
```

**Comment by mdubya66** [comment]
adding hasan as this is an issue being seen that's blocked successful CI runs

**Comment by fdawg4l** [comment]
I hit this yesterday on an unhappy VC setup.  The following `govc` command exhibited the same behavior.

```
fahmed@hasselhoff: ~/src/vic/src/github.com/vmware/vic/bin$ govc firewall.ruleset.find -host=/dc1/host/cluster1/10.118.66.150                                                                                                                                                                                                                                                                                                            
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x50dec2]

goroutine 1 [running]:
panic(0x1233b00, 0xc82000e130)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/vmware/govmomi/govc/host/firewall.(*find).Run(0xc8200746c0, 0x7fa6aef345b8, 0xc8200761e0, 0xc820074840, 0x0, 0x0)
        /home/fahmed/src/go/src/github.com/vmware/govmomi/govc/host/firewall/find.go:116 +0x7d2
github.com/vmware/govmomi/govc/cli.Run(0xc82007a0d0, 0x2, 0x2, 0x1634bd0)
        /home/fahmed/src/go/src/github.com/vmware/govmomi/govc/cli/command.go:139 +0x6ec
main.main()
        /home/fahmed/src/go/src/github.com/vmware/govmomi/govc/main.go:67 +0x60
```

The host referenced was an a very unhappy state.  I needed to nuke and recreate it (which itself is not a workaround).  But, something was up with the host.  I couldn't tell what was wrong with it or how it got in that state, but all attempts to fix it weren't helping.  Just FYI.

**Comment by fdawg4l** [comment]
I added some debug statements in `vic-machine` in case this is useful.

```
INFO[2016-08-10T10:48:33-07:00] fs = &object.HostFirewallSystem{Common:object.Common{InventoryPath:"", c:(*vim25.Client)(0xc820178a00), r:types.ManagedObjectReference{Type:"HostFirewallSystem", Value:"firewallSystem-16"}}} info = (*types.HostFirewallInfo)(nil) 

waitingERRO[2016-08-10T10:48:33-07:00] run time panic: runtime error: invalid memory address or nil pointer dereference : goroutine 1 [running]:
```
