### ISSUE TITLE
vic-machine panics

### ISSUE THREAD

**Issue by caglar10ur** [vmware/vic#1938]
```
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(1578)] /opt/go/src/github.com/vmware/vic/infra/machines/vcsa/install.sh -a -i
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5a3b08]

goroutine 1 [running]:
panic(0xb94260, 0xc4200100d0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/vmware/vic/pkg/flags.(*optionalString).String(0xc4200260e0, 0xc21f40, 0xc4200260e0)
        /opt/go/src/github.com/vmware/vic/pkg/flags/optional_string.go:38 +0x8
flag.isZeroValue(0xc420019340, 0xd3fc7b, 0x5, 0xd53045)
        /usr/local/go/src/flag/flag.go:393 +0x12d
flag.(*FlagSet).PrintDefaults.func1(0xc420019340)
        /usr/local/go/src/flag/flag.go:467 +0x1d5
flag.(*FlagSet).VisitAll(0xc420014ae0, 0xc420153160)
        /usr/local/go/src/flag/flag.go:323 +0x67
flag.(*FlagSet).PrintDefaults(0xc420014ae0)
        /usr/local/go/src/flag/flag.go:476 +0x46
flag.defaultUsage(0xc420014ae0)
        /usr/local/go/src/flag/flag.go:509 +0x96
flag.(*FlagSet).usage(0xc420014ae0)
        /usr/local/go/src/flag/flag.go:825 +0x55
flag.(*FlagSet).failf(0xc420014ae0, 0xd69cab, 0x22, 0xc420153368, 0x1, 0x1, 0x18, 0x0)
        /usr/local/go/src/flag/flag.go:814 +0x116
flag.(*FlagSet).parseOne(0xc420014ae0, 0x1, 0x0, 0x0)
        /usr/local/go/src/flag/flag.go:873 +0xad8
flag.(*FlagSet).Parse(0xc420014ae0, 0xc4200016e0, 0x18, 0x18, 0x1576d38, 0x0)
        /usr/local/go/src/flag/flag.go:915 +0x60
github.com/vmware/vic/vendor/github.com/urfave/cli.Command.Run(0xd4052a, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd42125, 0xa, 0x0, ...)
        /opt/go/src/github.com/vmware/vic/vendor/github.com/urfave/cli/command.go:120 +0x69c
github.com/vmware/vic/vendor/github.com/urfave/cli.(*App).Run(0xc420192000, 0xc4200016c0, 0x1a, 0x1a, 0x0, 0x0)
        /opt/go/src/github.com/vmware/vic/vendor/github.com/urfave/cli/app.go:236 +0x60c
main.main()
        /opt/go/src/github.com/vmware/vic/cmd/vic-machine/main.go:98 +0x1756
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(1578)]
```

following is how that script uses vic-machine
```
        /opt/go/src/github.com/vmware/vic/bin/vic-machine-linux create \
            -t ${host} \
            -u ${user} \
            -p ${pass} \
            -n ZzZ \
            -r /dc1/host/cluster1/Resources \
            --image-datastore vsanDatastore \
            --volume-store vsanDatastore:default \
            --external-network /dc1/network/ExternalNetwork \
            --bridge-network /dc1/network/InternalNetwork \
            --container-network /dc1/network/ExternalNetwork:external \
            --timeout 10m \
            --no-tls \
            -f
```

**Comment by emlin** [comment]
@caglar10ur 
This is really weird, the line optional_string.go:38
```
	if *b.val == nil {
```
*b.val is defined in Data.go, and used in create command, which is not possible to have nil pointer issue.

So is there any other weird thing happens before or after this error? E.g. out of memory, etc.

**Comment by caglar10ur** [comment]
Nope, nothing else is going on. Cleaned up the vm, building from scratch will let you know

**Comment by caglar10ur** [comment]
same result, this time I tried to deploy to ESXi

```
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(master)] sudo make most
...
ISO image produced: 31342 sectors
Written to medium : 31520 sectors at LBA 32
Writing to '/opt/go/src/github.com/vmware/vic/bin/bootstrap.iso' completed successfully.

building vic-machine linux...
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(master)] /opt/go/src/github.com/vmware/vic/infra/machines/vcsa/install.sh -e -i
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5a3b08]

goroutine 1 [running]:
panic(0xb95100, 0xc4200120d0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/vmware/vic/pkg/flags.(*optionalString).String(0xc4200280e0, 0xc22de0, 0xc4200280e0)
        /opt/go/src/github.com/vmware/vic/pkg/flags/optional_string.go:38 +0x8
flag.isZeroValue(0xc42001b340, 0xd40b9b, 0x5, 0xd53f73)
        /usr/local/go/src/flag/flag.go:393 +0x12d
flag.(*FlagSet).PrintDefaults.func1(0xc42001b340)
        /usr/local/go/src/flag/flag.go:467 +0x1d5
flag.(*FlagSet).VisitAll(0xc420016ae0, 0xc420155160)
        /usr/local/go/src/flag/flag.go:323 +0x67
flag.(*FlagSet).PrintDefaults(0xc420016ae0)
        /usr/local/go/src/flag/flag.go:476 +0x46
flag.defaultUsage(0xc420016ae0)
        /usr/local/go/src/flag/flag.go:509 +0x96
flag.(*FlagSet).usage(0xc420016ae0)
        /usr/local/go/src/flag/flag.go:825 +0x55
flag.(*FlagSet).failf(0xc420016ae0, 0xd6abd9, 0x22, 0xc420155368, 0x1, 0x1, 0x18, 0x0)
        /usr/local/go/src/flag/flag.go:814 +0x116
flag.(*FlagSet).parseOne(0xc420016ae0, 0x1, 0x0, 0x0)
        /usr/local/go/src/flag/flag.go:873 +0xad8
flag.(*FlagSet).Parse(0xc420016ae0, 0xc42000c180, 0x14, 0x14, 0x1578d78, 0x0)
        /usr/local/go/src/flag/flag.go:915 +0x60
github.com/vmware/vic/vendor/github.com/urfave/cli.Command.Run(0xd4144a, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd43045, 0xa, 0x0, ...)
        /opt/go/src/github.com/vmware/vic/vendor/github.com/urfave/cli/command.go:120 +0x69c
github.com/vmware/vic/vendor/github.com/urfave/cli.(*App).Run(0xc420194000, 0xc42000c160, 0x16, 0x16, 0x0, 0x0)
        /opt/go/src/github.com/vmware/vic/vendor/github.com/urfave/cli/app.go:236 +0x60c
main.main()
        /opt/go/src/github.com/vmware/vic/cmd/vic-machine/main.go:98 +0x1756
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(master)]
```

**Comment by caglar10ur** [comment]
to remove the script from the equation

```
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(master)] /opt/go/src/github.com/vmware/vic/bin/vic-machine-linux create -t 10.118.69.193 -u root -p {pass} -n ZzZ -r /ha-datacenter/host/office2-sfo2-dhcp299.eng.vmware.com/Resources --image-datastore datastore1 --volume-store datastore1:default --container-network VM Network:external --timeout 10m --no-tls -f
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5a3b08]

goroutine 1 [running]:
panic(0xb95100, 0xc4200120c0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/vmware/vic/pkg/flags.(*optionalString).String(0xc4200280e0, 0xc22de0, 0xc4200280e0)
        /opt/go/src/github.com/vmware/vic/pkg/flags/optional_string.go:38 +0x8
flag.isZeroValue(0xc42001b340, 0xd40b9b, 0x5, 0xd53f73)
        /usr/local/go/src/flag/flag.go:393 +0x12d
flag.(*FlagSet).PrintDefaults.func1(0xc42001b340)
        /usr/local/go/src/flag/flag.go:467 +0x1d5
flag.(*FlagSet).VisitAll(0xc420016ae0, 0xc420157160)
        /usr/local/go/src/flag/flag.go:323 +0x67
flag.(*FlagSet).PrintDefaults(0xc420016ae0)
        /usr/local/go/src/flag/flag.go:476 +0x46
flag.defaultUsage(0xc420016ae0)
        /usr/local/go/src/flag/flag.go:509 +0x96
flag.(*FlagSet).usage(0xc420016ae0)
        /usr/local/go/src/flag/flag.go:825 +0x55
flag.(*FlagSet).failf(0xc420016ae0, 0xd6abd9, 0x22, 0xc420157368, 0x1, 0x1, 0x18, 0x0)
        /usr/local/go/src/flag/flag.go:814 +0x116
flag.(*FlagSet).parseOne(0xc420016ae0, 0x1, 0x0, 0x0)
        /usr/local/go/src/flag/flag.go:873 +0xad8
flag.(*FlagSet).Parse(0xc420016ae0, 0xc42000c1a0, 0x15, 0x16, 0x1578d78, 0x0)
        /usr/local/go/src/flag/flag.go:915 +0x60
github.com/vmware/vic/vendor/github.com/urfave/cli.Command.Run(0xd4144a, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd43045, 0xa, 0x0, ...)
        /opt/go/src/github.com/vmware/vic/vendor/github.com/urfave/cli/command.go:120 +0x69c
github.com/vmware/vic/vendor/github.com/urfave/cli.(*App).Run(0xc42000c300, 0xc42000c180, 0x17, 0x18, 0x0, 0x0)
        /opt/go/src/github.com/vmware/vic/vendor/github.com/urfave/cli/app.go:236 +0x60c
main.main()
        /opt/go/src/github.com/vmware/vic/cmd/vic-machine/main.go:98 +0x1756
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(master)]
```

**Comment by caglar10ur** [comment]
```
commit 65392e90338f1cfde7b2a442a95f6735ecf4c894
Author: Ian Whitlock <iwhitlock@vmware.com>
Date:   Thu Aug 11 14:56:29 2016 -0500

    Allow custom image store paths (#1678)

    * Allow custom paths for image store
    * Add needed changes to vic-machine create/delete for custom imagestore paths
    * --image-datastore to --image-store
    * update docs
    * Image store directory functional test
    * Add tests for datastore with space and non-ascii char
    * Add imagestore directory example

```
renamed  --image-datastore to --image-store and that was my issue but this panic is not helpful to understand

**Comment by emlin** [comment]
```
./bin/vic-machine-linux create -t 10.118.69.193 -u root -p {pass} -n ZzZ -r /ha-datacenter/host/office2-sfo2-dhcp299.eng.vmware.com/Resources --image-datastore datastore1 --volume-store datastore1:default --container-network VM Network:external --timeout 10m --no-tls -f
Incorrect Usage.

NAME:
   vic-machine-linux create - Deploy VCH

USAGE:
   vic-machine-linux create [command options] [arguments...]

OPTIONS:
   --target value, -t value                         REQUIRED. ESXi or vCenter connection URL, specifying a datacenter if multiple exist e.g. root:password@VC-FQDN/datacenter (default: https://10.118.69.193)
   --user value, -u value                           ESX or vCenter user
   --password value, -p value                       ESX or vCenter password (default: {pass})
   --compute-resource value, -r value               Compute resource path, e.g. myCluster/Resources/myRP. Default to <default cluster>/Resources
   --name value, -n value                           The name of the Virtual Container Host (default: "virtual-container-host")
   --image-store value, -i value                    Image datastore path in format "datastore/path"
   --container-datastore value, --cs value          Container datastore name - not supported yet, default to image datastore
   --volume-store value, --vs value                 Specify location and label for volume store; path optional: "datastore/path:label" or "datastore:label"
   --bridge-network value, -b value                 The bridge network (private port group for containers)
   --external-network value, --en value             The external network (can see hub.docker.com)
   --management-network value, --mn value           The management network (provides route to target hosting vSphere)
   --client-network value, --cln value              The client network (restricts DOCKER_API access to this network)
   --container-network value, --cn value            Networks that containers can use
   --container-network-gateway value, --cng value   Gateway for the container network's subnet in CONTAINER-NETWORK:SUBNET format, e.g. a_network:172.16.0.0/16
   --container-network-ip-range value, --cnr value  IP range for the container network in CONTAINER-NETWORK:IP-RANGE format, e.g. a_network:172.16.0.0/24, a_network:172.16.0.10-20
   --container-network-dns value, --cnd value       DNS servers for the container network in CONTAINER-NETWORK:DNS format, e.g. a_network:8.8.8.8
   --pool-memory-reservation value, --pmr value     VCH Memory reservation in MB (default: 0)
   --pool-memory-limit value, --pml value           VCH Memory limit in MB (default: 0)
   --pool-memory-shares value, --pms value          VCH Memory shares in level or share number, e.g. high, normal, low, or 163840 (default: <nil>)
   --pool-cpu-reservation value, --pcr value        VCH vCPUs reservation in MHz (default: 0)
   --pool-cpu-limit value, --pcl value              VCH vCPUs limit in MHz (default: 0)
   --pool-cpu-shares value, --pcs value             VCH vCPUs shares, in level or share number, e.g. high, normal, low, or 4000 (default: <nil>)
   --bridge-network-range value, --bnr value        The ip range from which bridge networks are allocated (default: "172.16.0.0/12")
   --appliance-iso value, --ai value                The appliance iso
   --bootstrap-iso value, --bi value                The bootstrap iso
   --key value                                      Virtual Container Host private key file
   --cert value                                     Virtual Container Host x509 certificate file
   --no-tls, -k                                     Disable TLS support
   --force, -f                                      Force the install, removing existing if present
   --timeout value                                  Time to wait for appliance initialization (default: 3m0s)
   --advanced-options, -x                           Show all options
   --debug value, -v value                          [0(default),1...n], 0 is disabled, 1 is enabled, >= 1 may alter behaviour (default: 0)
   
ERRO[2016-08-11T20:55:14-05:00] --------------------                         
ERRO[2016-08-11T20:55:14-05:00] vic-machine-linux failed: flag provided but not defined: -image-datastore
```

**Comment by emlin** [comment]
There should be something wrong. The above is the result I execute your command in my env

**Comment by emlin** [comment]
I just sync the latest code and build vic-machine

**Comment by mdubya66** [comment]
@caglar10ur : are you still seeing this?

**Comment by caglar10ur** [comment]
Yep, I just did

```
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(1578)] bin/vic-machine-linux create -t vcva-clovervm.eng.vmware.com -u root -p 'PW' -n ZzZ -r /clovervm/host/bonneville/Resources  --image-datastore FC-shared01 --external-network DPortGroup  --bridge-network Bonneville --no-tls -f
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5abc18]

goroutine 1 [running]:
panic(0xb9cf60, 0xc4200100d0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/vmware/vic/pkg/flags.(*optionalString).String(0xc42002a0f0, 0xc2ac40, 0xc42002a0f0)
        /opt/go/src/github.com/vmware/vic/pkg/flags/optional_string.go:38 +0x8
flag.isZeroValue(0xc42001d2c0, 0xd48da8, 0x5, 0xd5c262)
        /usr/local/go/src/flag/flag.go:393 +0x12d
flag.(*FlagSet).PrintDefaults.func1(0xc42001d2c0)
        /usr/local/go/src/flag/flag.go:467 +0x1d5
flag.(*FlagSet).VisitAll(0xc420016b40, 0xc420154ee8)
        /usr/local/go/src/flag/flag.go:323 +0x67
flag.(*FlagSet).PrintDefaults(0xc420016b40)
        /usr/local/go/src/flag/flag.go:476 +0x46
flag.defaultUsage(0xc420016b40)
        /usr/local/go/src/flag/flag.go:509 +0x96
flag.(*FlagSet).usage(0xc420016b40)
        /usr/local/go/src/flag/flag.go:825 +0x55
flag.(*FlagSet).failf(0xc420016b40, 0xd72fcc, 0x22, 0xc4201550f0, 0x1, 0x1, 0x18, 0x0)
        /usr/local/go/src/flag/flag.go:814 +0x116
flag.(*FlagSet).parseOne(0xc420016b40, 0x1, 0x0, 0x0)
        /usr/local/go/src/flag/flag.go:873 +0xad8
flag.(*FlagSet).Parse(0xc420016b40, 0xc42000c160, 0x12, 0x12, 0x1583d38, 0x0)
        /usr/local/go/src/flag/flag.go:915 +0x60
github.com/vmware/vic/vendor/github.com/urfave/cli.Command.Run(0xd4965c, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd4b262, 0xa, 0x0, ...)
        /opt/go/src/github.com/vmware/vic/vendor/github.com/urfave/cli/command.go:120 +0x69c
github.com/vmware/vic/vendor/github.com/urfave/cli.(*App).Run(0xc420194000, 0xc42000c140, 0x14, 0x14, 0x0, 0x0)
        /opt/go/src/github.com/vmware/vic/vendor/github.com/urfave/cli/app.go:236 +0x60c
main.main()
        /opt/go/src/github.com/vmware/vic/cmd/vic-machine/main.go:106 +0x215e
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(1578)] bin/vic-machine-linux create -t vcva-clovervm.eng.vmware.com -u root -p 'PW' -n ZzZ -r /clovervm/host/bonneville/Resources  --image-store FC-shared01 --external-network DPortGroup  --bridge-network Bonneville --no-tls -f
INFO[2016-08-17T00:09:09Z] ### Installing VCH ####
WARN[2016-08-17T00:09:09Z] Configuring without TLS - to enable drop --no-tls or use --key/--cert parameters
```

**Comment by emlin** [comment]
I reproduced it as well after I update golang to 1.7.
There might have something different, will look at this after finished upgrade versioning issue.
