### ISSUE TITLE
TestLogTail ran too long

### ISSUE THREAD

**Issue by fdawg4l** [vmware/vic#2203]
```
2016/08/31 00:00:38 Testing TestLogTail
2016/08/31 00:00:38 GET https://localhost:40694/logs/tail/vicadmin.log:
time="2016-08-31T00:00:38Z" level=debug msg="[BEGIN] [github.com/vmware/vic/cmd/vicadmin.(*server).serve]" 
time="2016-08-31T00:00:38Z" level=debug msg="[BEGIN] [github.com/vmware/vic/cmd/vicadmin.(*server).handleFunc]" 
time="2016-08-31T00:00:38Z" level=debug msg="[ END ] [github.com/vmware/vic/cmd/vicadmin.(*server).handleFunc] [1.222µs] " 
time="2016-08-31T00:00:38Z" level=debug msg="[BEGIN] [github.com/vmware/vic/cmd/vicadmin.(*server).handleFunc]" 
time="2016-08-31T00:00:38Z" level=debug msg="[ END ] [github.com/vmware/vic/cmd/vicadmin.(*server).handleFunc] [740ns] " 
time="2016-08-31T00:00:38Z" level=debug msg="[BEGIN] [github.com/vmware/vic/cmd/vicadmin.logFiles]" 
time="2016-08-31T00:00:38Z" level=debug msg="[ END ] [github.com/vmware/vic/cmd/vicadmin.logFiles] [3.905µs] " 
time="2016-08-31T00:00:38Z" level=debug msg="[BEGIN] [github.com/vmware/vic/cmd/vicadmin.(*server).handleFunc]" 
time="2016-08-31T00:00:38Z" level=debug msg="[ END ] [github.com/vmware/vic/cmd/vicadmin.(*server).handleFunc] [570ns] " 
time="2016-08-31T00:00:38Z" level=debug msg="[BEGIN] [github.com/vmware/vic/cmd/vicadmin.(*server).handleFunc]" 
time="2016-08-31T00:00:38Z" level=debug msg="[ END ] [github.com/vmware/vic/cmd/vicadmin.(*server).handleFunc] [701ns] " 
time="2016-08-31T00:00:38Z" level=debug msg="[BEGIN] [github.com/vmware/vic/cmd/vicadmin.(*server).handleFunc]" 
time="2016-08-31T00:00:38Z" level=debug msg="[ END ] [github.com/vmware/vic/cmd/vicadmin.(*server).handleFunc] [482ns] " 
time="2016-08-31T00:00:38Z" level=debug msg="[BEGIN] [github.com/vmware/vic/cmd/vicadmin.(*server).handleFunc]" 
time="2016-08-31T00:00:38Z" level=debug msg="[ END ] [github.com/vmware/vic/cmd/vicadmin.(*server).handleFunc] [4.273µs] " 
time="2016-08-31T00:00:38Z" level=debug msg="[BEGIN] [github.com/vmware/vic/cmd/vicadmin.(*server).handleFunc]" 
time="2016-08-31T00:00:38Z" level=debug msg="[ END ] [github.com/vmware/vic/cmd/vicadmin.(*server).handleFunc] [597ns] " 
time="2016-08-31T00:00:38Z" level=debug msg="[BEGIN] [github.com/vmware/vic/cmd/vicadmin.(*server).handleFunc]" 
time="2016-08-31T00:00:38Z" level=debug msg="[ END ] [github.com/vmware/vic/cmd/vicadmin.(*server).handleFunc] [479ns] " 
time="2016-08-31T00:00:38Z" level=debug msg="[BEGIN] [github.com/vmware/vic/cmd/vicadmin.(*server).handleFunc]" 
time="2016-08-31T00:00:38Z" level=debug msg="[ END ] [github.com/vmware/vic/cmd/vicadmin.(*server).handleFunc] [485ns] " 
time="2016-08-31T00:00:38Z" level=debug msg="[BEGIN] [github.com/vmware/vic/cmd/vicadmin.(*server).handleFunc]" 
time="2016-08-31T00:00:38Z" level=debug msg="[ END ] [github.com/vmware/vic/cmd/vicadmin.(*server).handleFunc] [415ns] " 
time="2016-08-31T00:00:38Z" level=debug msg="[BEGIN] [github.com/vmware/vic/cmd/vicadmin.(*server).handleFunc]" 
time="2016-08-31T00:00:38Z" level=debug msg="[ END ] [github.com/vmware/vic/cmd/vicadmin.(*server).handleFunc] [535ns] " 
time="2016-08-31T00:00:38Z" level=debug msg="[BEGIN] [github.com/vmware/vic/cmd/vicadmin.(*server).handleFunc]" 
time="2016-08-31T00:00:38Z" level=debug msg="[ END ] [github.com/vmware/vic/cmd/vicadmin.(*server).handleFunc] [406ns] " 
time="2016-08-31T00:00:38Z" level=debug msg="[BEGIN] [github.com/vmware/vic/cmd/vicadmin.configureReaders]" 
time="2016-08-31T00:00:38Z" level=debug msg="[BEGIN] [github.com/vmware/vic/cmd/vicadmin.logFiles]" 
time="2016-08-31T00:00:38Z" level=debug msg="[ END ] [github.com/vmware/vic/cmd/vicadmin.logFiles] [3.024µs] " 
time="2016-08-31T00:00:38Z" level=debug msg="[BEGIN] [github.com/vmware/vic/cmd/vicadmin.findDatastore]" 
time="2016-08-31T00:00:38Z" level=debug msg="[BEGIN] [github.com/vmware/vic/cmd/vicadmin.client]" 
time="2016-08-31T00:00:38Z" level=warning msg="Unable to connect: SDK URL () could not be parsed: %!s(<nil>)" 
time="2016-08-31T00:00:38Z" level=debug msg="[ END ] [github.com/vmware/vic/cmd/vicadmin.client] [11.197µs] " 
time="2016-08-31T00:00:38Z" level=debug msg="[ END ] [github.com/vmware/vic/cmd/vicadmin.findDatastore] [26.192µs] " 
time="2016-08-31T00:00:38Z" level=warning msg="SDK URL () could not be parsed: %!s(<nil>)" 
time="2016-08-31T00:00:38Z" level=debug msg="[ END ] [github.com/vmware/vic/cmd/vicadmin.configureReaders] [114.615µs] " 
time="2016-08-31T00:00:38Z" level=debug msg="[BEGIN] [github.com/vmware/vic/cmd/vicadmin.(*server).tailFiles]" 
time="2016-08-31T00:00:38Z" level=debug msg="[BEGIN] [github.com/vmware/vic/cmd/vicadmin.tailFile] ./vicadmin.log" 
time="2016-08-31T00:00:38Z" level=debug msg="[BEGIN] [github.com/vmware/vic/cmd/vicadmin.findSeekPos]" 
time="2016-08-31T00:00:38Z" level=debug msg="[ END ] [github.com/vmware/vic/cmd/vicadmin.findSeekPos] [25.085µs] " 
2016/08/31 00:00:38 Seeked ./vicadmin.log - &{Offset:0 Whence:0}
SIGQUIT: quit
PC=0x4610a1 m=0

goroutine 0 [idle]:
runtime.futex(0x1657b30, 0x0, 0x0, 0x0, 0x7fff00000000, 0x0, 0x0, 0x0, 0x7fff5951d968, 0x4106b2, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:387 +0x21
runtime.futexsleep(0x1657b30, 0x0, 0xffffffffffffffff)
	/usr/local/go/src/runtime/os_linux.go:45 +0x62
runtime.notesleep(0x1657b30)
	/usr/local/go/src/runtime/lock_futex.go:145 +0x82
runtime.stopm()
	/usr/local/go/src/runtime/proc.go:1594 +0xad
runtime.findrunnable(0xc42001d500, 0x0)
	/usr/local/go/src/runtime/proc.go:2021 +0x228
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:2120 +0x14c
runtime.goexit0(0xc420211ba0)
	/usr/local/go/src/runtime/proc.go:2257 +0x180
runtime.mcall(0x7fff5951db10)
	/usr/local/go/src/runtime/asm_amd64.s:240 +0x5b

goroutine 1 [chan receive, 9 minutes]:
testing.(*T).Run(0xc4201e03c0, 0xdeab26, 0xb, 0xe532e8, 0xc4201ffc01)
	/usr/local/go/src/testing/testing.go:647 +0x316
testing.RunTests.func1(0xc4201e03c0)
	/usr/local/go/src/testing/testing.go:793 +0x6d
testing.tRunner(0xc4201e03c0, 0xc4201fed98)
	/usr/local/go/src/testing/testing.go:610 +0x81
testing.RunTests(0xe536c0, 0x162e4c0, 0x5, 0x5, 0x41199e)
	/usr/local/go/src/testing/testing.go:799 +0x2f5
testing.(*M).Run(0xc4201feef8, 0xe1ecb6)
	/usr/local/go/src/testing/testing.go:743 +0x85
main.main()
	github.com/vmware/vic/cmd/vicadmin/_test/_testmain.go:112 +0x1bd

goroutine 17 [syscall, 9 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 7 [select, 9 minutes]:
net/http.(*persistConn).writeLoop(0xc4201da700)
	/usr/local/go/src/net/http/transport.go:1641 +0x3bd
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1058 +0x50e

goroutine 18 [syscall, 9 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 19 [IO wait, 9 minutes]:
net.runtime_pollWait(0x7f5110257108, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc420016f40, 0x72, 0xc420039cf8, 0xc4200140c8)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc420016f40, 0x163b700, 0xc4200140c8)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).accept(0xc420016ee0, 0x0, 0x1639d80, 0xc4202241a0)
	/usr/local/go/src/net/fd_unix.go:419 +0x238
net.(*TCPListener).accept(0xc420028068, 0x29e8d60800, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:132 +0x2e
net.(*TCPListener).AcceptTCP(0xc420028068, 0xc420039e20, 0xc420039e28, 0xc420039e18)
	/usr/local/go/src/net/tcpsock.go:209 +0x49
net/http.tcpKeepAliveListener.Accept(0xc420028068, 0xe538d0, 0xc42007f880, 0x163f180, 0xc420011aa0)
	/usr/local/go/src/net/http/server.go:2608 +0x2f
net/http.(*Server).Serve(0xc42007e380, 0x163ea40, 0xc420028068, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2273 +0x1ce
net/http.(*Server).ListenAndServe(0xc42007e380, 0xc42007e380, 0x0)
	/usr/local/go/src/net/http/server.go:2219 +0xb4
net/http.ListenAndServe(0xc4201edf27, 0xe, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2351 +0xa0
github.com/vmware/vic/lib/pprof.StartPprof.func1(0xc4201edf27, 0xe)
	/drone/src/github.com/vmware/vic/lib/pprof/pprof.go:91 +0x4b
created by github.com/vmware/vic/lib/pprof.StartPprof
	/drone/src/github.com/vmware/vic/lib/pprof/pprof.go:92 +0x25a

goroutine 28 [IO wait, 9 minutes]:
net.runtime_pollWait(0x7f5110256ec8, 0x72, 0x7)
	/usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc4202556b0, 0x72, 0xc4200474c0, 0xc4200140c8)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc4202556b0, 0x163b700, 0xc4200140c8)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc420255650, 0xc42024e800, 0x400, 0x400, 0x0, 0x163b700, 0xc4200140c8)
	/usr/local/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc4201d27b0, 0xc42024e800, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:173 +0x70
crypto/tls.(*block).readFromUntil(0xc420227da0, 0x7f5110216100, 0xc4201d27b0, 0x5, 0xc4201d27b0, 0xc4200475e8)
	/usr/local/go/src/crypto/tls/conn.go:472 +0x91
crypto/tls.(*Conn).readRecord(0xc42023c700, 0xe54017, 0xc42023c800, 0x14)
	/usr/local/go/src/crypto/tls/conn.go:574 +0xc4
crypto/tls.(*Conn).Read(0xc42023c700, 0xc42024d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1109 +0x116
net/http.(*connReader).Read(0xc420303740, 0xc42024d000, 0x1000, 0x1000, 0xc4203282c0, 0x0, 0x5de6a7)
	/usr/local/go/src/net/http/server.go:586 +0x144
bufio.(*Reader).fill(0xc4201cf6e0)
	/usr/local/go/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).ReadSlice(0xc4201cf6e0, 0xa, 0x0, 0x1e, 0xc4200479c8, 0x33, 0x0)
	/usr/local/go/src/bufio/bufio.go:330 +0xb5
bufio.(*Reader).ReadLine(0xc4201cf6e0, 0xc420216000, 0xf0, 0xf0, 0xdd13c0, 0xc4201df401, 0x17f51102b2000)
	/usr/local/go/src/bufio/bufio.go:359 +0x37
net/textproto.(*Reader).readLineSlice(0xc4202265d0, 0xc420047a98, 0xc420047a98, 0x4121c8, 0xf0, 0xdd13c0)
	/usr/local/go/src/net/textproto/reader.go:55 +0x5e
net/textproto.(*Reader).ReadLine(0xc4202265d0, 0xc420216000, 0x456ba0, 0xc42025a580, 0xc420047b68)
	/usr/local/go/src/net/textproto/reader.go:36 +0x2f
net/http.readRequest(0xc4201cf6e0, 0x0, 0xc420216000, 0x0, 0x0)
	/usr/local/go/src/net/http/request.go:793 +0xa5
net/http.(*conn).readRequest(0xc4201d8e80, 0x163f0c0, 0xc42025a8c0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:765 +0x10d
net/http.(*conn).serve(0xc4201d8e80, 0x163f0c0, 0xc42025a8c0)
	/usr/local/go/src/net/http/server.go:1532 +0x3d3
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d

goroutine 99 [IO wait, 9 minutes]:
net.runtime_pollWait(0x7f5110256e08, 0x72, 0xb)
	/usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc4201d6ed0, 0x72, 0xc420315468, 0xc4200140c8)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc4201d6ed0, 0x163b700, 0xc4200140c8)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc4201d6e70, 0xc42002b400, 0x400, 0x400, 0x0, 0x163b700, 0xc4200140c8)
	/usr/local/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc4201d2000, 0xc42002b400, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:173 +0x70
crypto/tls.(*block).readFromUntil(0xc420227260, 0x7f5110216100, 0xc4201d2000, 0x5, 0xc4201d2000, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:472 +0x91
crypto/tls.(*Conn).readRecord(0xc42023ca80, 0xe54017, 0xc42023cb80, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:574 +0xc4
crypto/tls.(*Conn).Read(0xc42023ca80, 0xc420414000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1109 +0x116
net/http.(*persistConn).Read(0xc42000ac00, 0xc420414000, 0x1000, 0x1000, 0x14, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1256 +0x154
bufio.(*Reader).fill(0xc4201cf560)
	/usr/local/go/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).ReadSlice(0xc4201cf560, 0xc42022770a, 0x2, 0x2, 0x2, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:330 +0xb5
net/http/internal.readChunkLine(0xc4201cf560, 0xc4201cf560, 0xc4202277c0, 0x2, 0x2, 0x2)
	/usr/local/go/src/net/http/internal/chunked.go:110 +0x34
net/http/internal.(*chunkedReader).beginChunk(0xc4202277a0)
	/usr/local/go/src/net/http/internal/chunked.go:47 +0x32
net/http/internal.(*chunkedReader).Read(0xc4202277a0, 0xc4203d4000, 0xdd, 0x2000, 0x456aa0, 0xc420315aa0, 0xc420315aa8)
	/usr/local/go/src/net/http/internal/chunked.go:77 +0x7b
net/http.(*body).readLocked(0xc42025b5c0, 0xc4203d4000, 0xdd, 0x2000, 0xc4202580a0, 0x0, 0x0)
	/usr/local/go/src/net/http/transfer.go:651 +0x61
net/http.(*body).Read(0xc42025b5c0, 0xc4203d4000, 0xdd, 0x2000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transfer.go:643 +0xf6
net/http.(*bodyEOFSignal).Read(0xc42025b600, 0xc4203d4000, 0xdd, 0x2000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1969 +0x116
io.(*LimitedReader).Read(0xc420413700, 0xc4203d4000, 0x2000, 0x2000, 0xf, 0x0, 0x0)
	/usr/local/go/src/io/io.go:436 +0x6c
io/ioutil.devNull.ReadFrom(0x0, 0x16390c0, 0xc420413700, 0xc4a240, 0xe50801, 0x7f5110222828)
	/usr/local/go/src/io/ioutil/ioutil.go:151 +0x85
io/ioutil.(*devNull).ReadFrom(0xc420014570, 0x16390c0, 0xc420413700, 0xc420315ca0, 0x1, 0x18)
	<autogenerated>:9 +0x66
io.copyBuffer(0x163aac0, 0xc420014570, 0x16390c0, 0xc420413700, 0x0, 0x0, 0x0, 0xd01b20, 0x1639601, 0xc420413700)
	/usr/local/go/src/io/io.go:384 +0x323
io.Copy(0x163aac0, 0xc420014570, 0x16390c0, 0xc420413700, 0xc47220, 0xc71380, 0xc420315d00)
	/usr/local/go/src/io/io.go:360 +0x68
io.CopyN(0x163aac0, 0xc420014570, 0x16396c0, 0xc42025b600, 0x100, 0x0, 0xf, 0xc420124e01)
	/usr/local/go/src/io/io.go:336 +0x8c
github.com/vmware/vic/cmd/vicadmin.TestLogTail(0xc4202f0240)
	/drone/src/github.com/vmware/vic/cmd/vicadmin/vicadm_test.go:281 +0x6a1
testing.tRunner(0xc4202f0240, 0xe532e8)
	/usr/local/go/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:646 +0x2ec

goroutine 103 [select, 9 minutes]:
net/http.(*persistConn).readLoop(0xc42000ac00)
	/usr/local/go/src/net/http/transport.go:1536 +0x9c9
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1057 +0x4e9

goroutine 6 [IO wait, 9 minutes]:
net.runtime_pollWait(0x7f5110256f88, 0x72, 0x6)
	/usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc42020d090, 0x72, 0xc4200346f0, 0xc4200140c8)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc42020d090, 0x163b700, 0xc4200140c8)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc42020d030, 0xc42021c000, 0x2000, 0x2000, 0x0, 0x163b700, 0xc4200140c8)
	/usr/local/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc4201d27a8, 0xc42021c000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:173 +0x70
crypto/tls.(*block).readFromUntil(0xc420011ad0, 0x7f5110216100, 0xc4201d27a8, 0x5, 0xc4201d27a8, 0x28)
	/usr/local/go/src/crypto/tls/conn.go:472 +0x91
crypto/tls.(*Conn).readRecord(0xc42023c380, 0xe54017, 0xc42023c480, 0xc420210ea0)
	/usr/local/go/src/crypto/tls/conn.go:574 +0xc4
crypto/tls.(*Conn).Read(0xc42023c380, 0xc420089000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1109 +0x116
net/http.(*persistConn).Read(0xc4201da700, 0xc420089000, 0x1000, 0x1000, 0x66f990, 0xc420034b58, 0x405f1d)
	/usr/local/go/src/net/http/transport.go:1256 +0x154
bufio.(*Reader).fill(0xc420018a80)
	/usr/local/go/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).Peek(0xc420018a80, 0x1, 0xc420034bbd, 0x1, 0x0, 0xc420018ae0, 0x0)
	/usr/local/go/src/bufio/bufio.go:129 +0x62
net/http.(*persistConn).readLoop(0xc4201da700)
	/usr/local/go/src/net/http/transport.go:1413 +0x1a1
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1057 +0x4e9

goroutine 104 [select, 9 minutes]:
net/http.(*persistConn).writeLoop(0xc42000ac00)
	/usr/local/go/src/net/http/transport.go:1641 +0x3bd
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1058 +0x50e

goroutine 100 [IO wait, 9 minutes]:
net.runtime_pollWait(0x7f5110257048, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc420254c30, 0x72, 0xc420049c48, 0xc4200140c8)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc420254c30, 0x163b700, 0xc4200140c8)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).accept(0xc420254bd0, 0x0, 0x1639d80, 0xc420249340)
	/usr/local/go/src/net/fd_unix.go:419 +0x238
net.(*TCPListener).accept(0xc420028030, 0xc4201d2008, 0xc42045c000, 0x7f51102b24b0)
	/usr/local/go/src/net/tcpsock_posix.go:132 +0x2e
net.(*TCPListener).Accept(0xc420028030, 0x435fbe, 0xc420049d50, 0x658d4d, 0x457410)
	/usr/local/go/src/net/tcpsock.go:222 +0x49
crypto/tls.(*listener).Accept(0xc4204124a0, 0xe538d0, 0xc4201d8500, 0x163f180, 0xc42020f2c0)
	/usr/local/go/src/crypto/tls/tls.go:52 +0x37
net/http.(*Server).Serve(0xc4201d8100, 0x163e280, 0xc4204124a0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2273 +0x1ce
github.com/vmware/vic/cmd/vicadmin.(*server).serve(0xc42025a800, 0x0, 0x0)
	github.com/vmware/vic/cmd/vicadmin/_test/_obj_test/server.go:182 +0x916
created by github.com/vmware/vic/cmd/vicadmin.TestLogTail
	/drone/src/github.com/vmware/vic/cmd/vicadmin/vicadm_test.go:242 +0x23a

goroutine 91 [chan receive, 9 minutes]:
github.com/vmware/vic/cmd/vicadmin.(*server).tailFiles(0xc42025a800, 0x163e580, 0xc42005c8f0, 0xc4200c0690, 0xc420035c68, 0x1, 0x1)
	github.com/vmware/vic/cmd/vicadmin/_test/_obj_test/server.go:318 +0x311
github.com/vmware/vic/cmd/vicadmin.(*server).serve.func2(0x163e580, 0xc42005c8f0, 0xc4200c0690)
	github.com/vmware/vic/cmd/vicadmin/_test/_obj_test/server.go:170 +0x9a
net/http.HandlerFunc.ServeHTTP(0xc420248840, 0x163e580, 0xc42005c8f0, 0xc4200c0690)
	/usr/local/go/src/net/http/server.go:1726 +0x44
net/http.(*ServeMux).ServeHTTP(0xc42020e090, 0x163e580, 0xc42005c8f0, 0xc4200c0690)
	/usr/local/go/src/net/http/server.go:2022 +0x7f
net/http.serverHandler.ServeHTTP(0xc4201d8100, 0x163e580, 0xc42005c8f0, 0xc4200c0690)
	/usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc4201d8500, 0x163f0c0, 0xc4201ccb40)
	/usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d

goroutine 92 [IO wait, 9 minutes]:
net.runtime_pollWait(0x7f5110256bc8, 0x72, 0xc)
	/usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc4201d6f40, 0x72, 0xc420026b98, 0xc4200140c8)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc4201d6f40, 0x163b700, 0xc4200140c8)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc4201d6ee0, 0xc4201df000, 0x400, 0x400, 0x0, 0x163b700, 0xc4200140c8)
	/usr/local/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc4201d2008, 0xc4201df000, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:173 +0x70
crypto/tls.(*block).readFromUntil(0xc42020f4a0, 0x7f5110216100, 0xc4201d2008, 0x5, 0xc4201d2008, 0x2)
	/usr/local/go/src/crypto/tls/conn.go:472 +0x91
crypto/tls.(*Conn).readRecord(0xc42023ce00, 0xe54017, 0xc42023cf00, 0x4121c8)
	/usr/local/go/src/crypto/tls/conn.go:574 +0xc4
crypto/tls.(*Conn).Read(0xc42023ce00, 0xc4201ea26c, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1109 +0x116
net/http.(*connReader).closeNotifyAwaitActivityRead(0xc4202091c0, 0xc42005e780, 0xc420209260)
	/usr/local/go/src/net/http/server.go:602 +0x71
created by net/http.(*connReader).startBackgroundRead
	/usr/local/go/src/net/http/server.go:597 +0x98

goroutine 93 [select, 9 minutes]:
github.com/vmware/vic/cmd/vicadmin.tailFile(0x1635e00, 0xc4202092a0, 0xc4202284f0, 0xe, 0xc4201d2010, 0x0, 0x0)
	github.com/vmware/vic/cmd/vicadmin/_test/_obj_test/logs.go:392 +0x4e7
created by github.com/vmware/vic/cmd/vicadmin.(*server).tailFiles
	github.com/vmware/vic/cmd/vicadmin/_test/_obj_test/server.go:314 +0x2c4

goroutine 94 [select, 9 minutes]:
github.com/vmware/vic/vendor/github.com/hpcloud/tail.(*Tail).waitForChanges(0xc4202188f0, 0xc420014170, 0x1635d40)
	/drone/src/github.com/vmware/vic/vendor/github.com/hpcloud/tail/tail.go:350 +0xe5a
github.com/vmware/vic/vendor/github.com/hpcloud/tail.(*Tail).tailFileSync(0xc4202188f0)
	/drone/src/github.com/vmware/vic/vendor/github.com/hpcloud/tail/tail.go:311 +0x313
created by github.com/vmware/vic/vendor/github.com/hpcloud/tail.TailFile
	/drone/src/github.com/vmware/vic/vendor/github.com/hpcloud/tail/tail.go:133 +0x1f8

goroutine 95 [select, 9 minutes]:
github.com/vmware/vic/vendor/github.com/hpcloud/tail/watch.(*InotifyTracker).run(0xc4201cd000)
	/drone/src/github.com/vmware/vic/vendor/github.com/hpcloud/tail/watch/inotify_tracker.go:236 +0x45b
created by github.com/vmware/vic/vendor/github.com/hpcloud/tail/watch.glob..func1
	/drone/src/github.com/vmware/vic/vendor/github.com/hpcloud/tail/watch/inotify_tracker.go:54 +0x233

goroutine 96 [syscall, 9 minutes]:
syscall.Syscall6(0xe8, 0x10, 0xc42042dc14, 0x7, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.EpollWait(0x10, 0xc42042dc14, 0x7, 0x7, 0xffffffffffffffff, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:365 +0x77
github.com/vmware/vic/vendor/github.com/hpcloud/tail/vendor/gopkg.in/fsnotify%2ev1.(*fdPoller).wait(0xc4202094e0, 0xe53300, 0xc4202094e0, 0x0)
	/drone/src/github.com/vmware/vic/vendor/github.com/hpcloud/tail/vendor/gopkg.in/fsnotify.v1/inotify_poller.go:85 +0x91
github.com/vmware/vic/vendor/github.com/hpcloud/tail/vendor/gopkg.in/fsnotify%2ev1.(*Watcher).readEvents(0xc420259c70)
	/drone/src/github.com/vmware/vic/vendor/github.com/hpcloud/tail/vendor/gopkg.in/fsnotify.v1/inotify.go:179 +0x196
created by github.com/vmware/vic/vendor/github.com/hpcloud/tail/vendor/gopkg.in/fsnotify%2ev1.NewWatcher
	/drone/src/github.com/vmware/vic/vendor/github.com/hpcloud/tail/vendor/gopkg.in/fsnotify.v1/inotify.go:58 +0x2cc

goroutine 97 [select, 9 minutes]:
github.com/vmware/vic/vendor/github.com/hpcloud/tail/watch.(*InotifyFileWatcher).ChangeEvents.func1(0xc4202093a0, 0xc420218968, 0xc420209500)
	/drone/src/github.com/vmware/vic/vendor/github.com/hpcloud/tail/watch/inotify.go:88 +0x408
created by github.com/vmware/vic/vendor/github.com/hpcloud/tail/watch.(*InotifyFileWatcher).ChangeEvents
	/drone/src/github.com/vmware/vic/vendor/github.com/hpcloud/tail/watch/inotify.go:125 +0x155

rax    0xca
rbx    0x1656cb0
rcx    0x4610a3
rdx    0x0
rdi    0x1657b30
rsi    0x0
rbp    0x7fff5951d938
rsp    0x7fff5951d8f0
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x0
r13    0xf1
r14    0x1c
r15    0x1
rip    0x4610a1
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
*** Test killed with quit: ran too long (10m0s).
FAIL	github.com/vmware/vic/cmd/vicadmin	600.016s
Makefile:227: recipe for target 'test-job-github.com/vmware/vic/cmd' failed
make: *** [test-job-github.com/vmware/vic/cmd] Error 1
[info] build failed (exit code 2)
```

**Comment by fdawg4l** [comment]
@hickeng I don't know who to give this to.   Please reassign as necessary.

**Comment by anchal-agrawal** [comment]
Possibly a dup of #2096.
