### ISSUE TITLE
docker volume ls returns EOF in some cases

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#2313]
1. docker volume create --name victest
2. docker volume ls

- success

Then do

3\. docker create -v /test busybox
4\. docker volume ls

- An error occurred trying to connect: Get http://192.168.218.128:2375/v1.23/volumes: EOF

Actually, after operation 3, docker volume operations no longer seem to work.

The only way to recover is to uninstall vic, using vic-machine, with the --force flag and reinstall vic.

**Comment by fdawg4l** [comment]
I'm seeing the same behavior.  Looks like the docker daemon is panicking.  

```
time="2016-09-13T23:36:05Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Volume).Volumes] [12.426054ms] Volume.Volumes" 
2016/09/13 23:36:05 http: panic serving 192.168.8.1:33976: runtime error: invalid memory address or nil pointer dereference
goroutine 81 [running]:
net/http.(*conn).serve.func1(0xc420366a80)
        /usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0xfca280, 0xc420010050)
        /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/vmware/vic/lib/apiservers/engine/backends.(*Volume).Volumes(0x1c884c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/vmware/vic/lib/apiservers/engine/backends/volume.go:89 +0x408
github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/volume.(*volumeRouter).getVolumesList(0xc42032bb00, 0x7fb5ed7037a8, 0xc42042d410, 0x1c4b420, 0xc4202edba0, 0xc420274a50, 0xc42042d260, 0x1c4c560, 0xc42042d410)
        /go/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/volume/volume_routes.go:17 +0x92
github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/volume.(*volumeRouter).(github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/volume.getVolumesList)-fm(0x7fb5ed7037a8, 0xc42042d410, 0x1c4b420, 0xc4202edba0, 0xc420274a50, 0xc42042d260, 0x7fb5ed7037a8, 0xc42042d410)
        /go/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/volume/volume.go:28 +0x69
github.com/vmware/vic/vendor/github.com/docker/docker/api/server/middleware.NewVersionMiddleware.func1.1(0x7fb5ed7037a8, 0xc42042d350, 0x1c4b420, 0xc4202edba0, 0xc420274a50, 0xc42042d260, 0x2, 0xc42042d350)
        /go/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/middleware/version.go:42 +0x747
github.com/vmware/vic/vendor/github.com/docker/docker/api/server/middleware.NewUserAgentMiddleware.func1.1(0x7fb5ed7037a8, 0xc42042d350, 0x1c4b420, 0xc4202edba0, 0xc420274a50, 0xc42042d260, 0xc42042d290, 0xc420717b58)
        /go/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/middleware/user_agent.go:34 +0x237
github.com/vmware/vic/vendor/github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x1c4b420, 0xc4202edba0, 0xc420274a50)
        /go/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/server.go:132 +0x107
net/http.HandlerFunc.ServeHTTP(0xc420248ae0, 0x1c4b420, 0xc4202edba0, 0xc420274a50)
        /usr/local/go/src/net/http/server.go:1726 +0x44
github.com/vmware/vic/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4203842d0, 0x1c4b420, 0xc4202edba0, 0xc420274a50)
        /go/src/github.com/vmware/vic/vendor/github.com/gorilla/mux/mux.go:103 +0x255
github.com/vmware/vic/vendor/github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc420201030, 0x1c4b420, 0xc4202edba0, 0xc420274a50)
        /go/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router_swapper.go:29 +0x70
net/http.serverHandler.ServeHTTP(0xc420366b00, 0x1c4b420, 0xc4202edba0, 0xc420274a50)
        /usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc420366a80, 0x1c4c4a0, 0xc4202d8680)
        /usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2293 +0x44d
```

**Comment by fdawg4l** [comment]
```
193 // Unmarshal the docker metadata using the docker metadata key.  The docker
194 // metadatakey.  We stash the vals we know about in that map with that key.
195 func extractDockerMetadata(metadataMap map[string]string) (*volumeMetadata,
196 »···error) {               
197 »···v, ok := metadataMap[dockerMetadataModelKey]
198 »···if !ok {               
199 »···»···return nil, nil    
200 »···}
201 
```
```

**Comment by fdawg4l** [comment]
```
176dc15c (sflxn           2016-07-25 12:55:56 -0700)|512 
176dc15c (sflxn           2016-07-25 12:55:56 -0700)|513 func processAnonymousVolumes(h *string, volumes map[string]struct{}, client *client.PortLayer) ([]volumeFields, error) {
176dc15c (sflxn           2016-07-25 12:55:56 -0700)|514 »···var volumeFields []volumeFields
176dc15c (sflxn           2016-07-25 12:55:56 -0700)|515 
176dc15c (sflxn           2016-07-25 12:55:56 -0700)|516 »···for v := range volumes {
176dc15c (sflxn           2016-07-25 12:55:56 -0700)|517 »···»···fields, err := processVolumeParam(v)
903f405a (Anchal Agrawal  2016-09-12 12:38:26 -0500)|518 »···»···log.Infof("Processed anonymous volume arguments: %#v", fields)
176dc15c (sflxn           2016-07-25 12:55:56 -0700)|519 »···»···if err != nil {
176dc15c (sflxn           2016-07-25 12:55:56 -0700)|520 »···»···»···return nil, err
176dc15c (sflxn           2016-07-25 12:55:56 -0700)|521 »···»···}
176dc15c (sflxn           2016-07-25 12:55:56 -0700)|522 »···»···//NOTE: This should be the guard for the case of an anonymous volume.
176dc15c (sflxn           2016-07-25 12:55:56 -0700)|523 »···»···//NOTE: we should not expect any driver args if the drive is anonymous.
176dc15c (sflxn           2016-07-25 12:55:56 -0700)|524 »···»···log.Infof("anonymous volume being created - Container Create - volume mount section ID: %s ", fields.ID)
176dc15c (sflxn           2016-07-25 12:55:56 -0700)|525 »···»···metadata := make(map[string]string)
176dc15c (sflxn           2016-07-25 12:55:56 -0700)|526 »···»···metadata["flags"] = fields.Flags
176dc15c (sflxn           2016-07-25 12:55:56 -0700)|527 »···»···volumeRequest := models.VolumeRequest{
176dc15c (sflxn           2016-07-25 12:55:56 -0700)|528 »···»···»···Capacity: -1,
176dc15c (sflxn           2016-07-25 12:55:56 -0700)|529 »···»···»···Driver:   "vsphere",
176dc15c (sflxn           2016-07-25 12:55:56 -0700)|530 »···»···»···Store:    "default",
176dc15c (sflxn           2016-07-25 12:55:56 -0700)|531 »···»···»···Name:     fields.ID,
176dc15c (sflxn           2016-07-25 12:55:56 -0700)|532 »···»···»···Metadata: metadata,
176dc15c (sflxn           2016-07-25 12:55:56 -0700)|533 »···»···}
c045b71b (S.Çağlar Onur   2016-08-09 16:43:21 -0700)|534 »···»···_, err = client.Storage.CreateVolume(storage.NewCreateVolumeParamsWithContext(ctx).WithVolumeRequest(&volumeRequest))
176dc15c (sflxn           2016-07-25 12:55:56 -0700)|535 »···»···if err != nil {
176dc15c (sflxn           2016-07-25 12:55:56 -0700)|536 »···»···»···return nil, err
176dc15c (sflxn           2016-07-25 12:55:56 -0700)|537 »···»···}
176dc15c (sflxn           2016-07-25 12:55:56 -0700)|538 »···»···volumeFields = append(volumeFields, fields)
176dc15c (sflxn           2016-07-25 12:55:56 -0700)|539 »···}
176dc15c (sflxn           2016-07-25 12:55:56 -0700)|540 »···return volumeFields, nil
176dc15c (sflxn           2016-07-25 12:55:56 -0700)|541 }
176dc15c (sflxn           2016-07-25 12:55:56 -0700)|542 
```

Looks like anonymous volume creation happens out of band from the `VolumeCreate` call in the docker daemon.
