### ISSUE TITLE
Get a modified Voting app working on VIC and update the integration test

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#2358]
The current docker voting app cannot work on VIC right now.  It relies on mapped volumes, network alias, and docker build.  Network alias is currently being fixed, but the other two will not be a part of 1.0/GA.  We need to redesign the voting app to work on VIC.  This will involve building custom images and pushing to a private registry.

**Comment by sflxn** [comment]
depends on #2294

**Comment by sflxn** [comment]
I got the voting app working, pulling from the global docker hub, but there were errors.

```
Creating votingapp_vote_1
Creating votingapp_redis_1
Creating votingapp_worker_1
Creating votingapp_result_1
Creating votingapp_db_1

ERROR: for vote  HTTPConnectionPool(host='192.168.218.132', port=2375): Read timed out. (read timeout=60)

ERROR: for redis  HTTPConnectionPool(host='192.168.218.132', port=2375): Read timed out. (read timeout=60)

ERROR: for db  HTTPConnectionPool(host='192.168.218.132', port=2375): Read timed out. (read timeout=60)

ERROR: for worker  HTTPConnectionPool(host='192.168.218.132', port=2375): Read timed out. (read timeout=60)

ERROR: for result  HTTPConnectionPool(host='192.168.218.132', port=2375): Read timed out. (read timeout=60)
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 61, in main
  File "compose/cli/main.py", line 113, in perform_command
  File "contextlib.py", line 35, in __exit__
  File "compose/cli/errors.py", line 56, in handle_connection_errors
TypeError: log_timeout_error() takes exactly 1 argument (0 given)
```
Even with those errors, the app "seems" to work.  I'll have to look into why it's giving all these errors.

**Comment by sflxn** [comment]
Since this is a modified voting app, and this app is itself an OSS project, the question of how do we incorporate this into VIC is the next question. @mdubya66 @hickeng and I discussed this a little last week.  An idea was to pull this project into some new examples folder.  I assume we need approval for that.  We will have to modify the files.

An alternative is to create our own app in the same vein.

Also, we can just document how to make it work.

**Comment by sflxn** [comment]
Looks like the above error is a known issue for compose.  https://github.com/docker/compose/issues/3851
