### ISSUE TITLE
invalid memory address or nil pointer dereference in portlayer.log

### ISSUE THREAD

**Issue by caglar10ur** [vmware/vic#2594]
```
2016/10/06 19:13:34 http: panic serving 10.17.109.122:34584: runtime error: invalid memory address or nil pointer dereference
goroutine 810 [running]:
net/http.(*conn).serve.func1(0xc420b48d00)
    /usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0xe2d800, 0xc42000e050)
    /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/interaction.(*ContainerGetStdoutNotFound).WriteResponse(0xc42001c460, 0x19ad620, 0xc42080f930, 0x0, 0x0)
    /home/hmahmood/go/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/interaction/container_get_stdout_responses.go:82 +0x5a
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.(*Context).Respond(0xc420204d00, 0x19ad620, 0xc42080f930, 0xc420641c20, 0xc4205e2fd0, 0x1, 0x1, 0xc420177dc0, 0xe60500, 0xc42001c460)
    /home/hmahmood/go/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/context.go:392 +0x424
github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/interaction.(*ContainerGetStdout).ServeHTTP(0xc42017f580, 0x19ad620, 0xc42080f930, 0xc420641c20)
    /home/hmahmood/go/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/interaction/container_get_stdout.go:53 +0x253
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.newOperationExecutor.func1(0x19ad620, 0xc42080f930, 0xc420641c20)
    /home/hmahmood/go/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/operation.go:23 +0x69
net/http.HandlerFunc.ServeHTTP(0xc420353a80, 0x19ad620, 0xc42080f930, 0xc420641c20)
    /usr/local/go/src/net/http/server.go:1726 +0x44
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.newRouter.func1(0x19ad620, 0xc42080f930, 0xc420641c20)
    /home/hmahmood/go/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/router.go:78 +0x555
net/http.HandlerFunc.ServeHTTP(0xc42055a1c0, 0x19ad620, 0xc42080f930, 0xc420641c20)
    /usr/local/go/src/net/http/server.go:1726 +0x44
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.specMiddleware.func1(0x19ad620, 0xc42080f930, 0xc420641c20)
    /home/hmahmood/go/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/spec.go:36 +0x7b
net/http.HandlerFunc.ServeHTTP(0xc42058ef00, 0x19ad620, 0xc42080f930, 0xc420641c20)
    /usr/local/go/src/net/http/server.go:1726 +0x44
net/http.serverHandler.ServeHTTP(0xc42062b300, 0x19ad620, 0xc42080f930, 0xc420641c20)
    /usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc420b48d00, 0x19ae1a0, 0xc4207433c0)
    /usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:2293 +0x44d
time="2016-10-06T19:13:34Z" level=info msg="attach connector:  Connection not found yet for 31a66b66af69fa65e15f4bb43da79f21ba446f2f79675750855031316c1e1a2a" 
time="2016-10-06T19:13:34Z" level=debug msg="attach connector:  Giving up on connection for 31a66b66af69fa65e15f4bb43da79f21ba446f2f79675750855031316c1e1a2a" 
time="2016-10-06T19:13:34Z" level=error msg="attach connector: Connection not found error for id:31a66b66af69fa65e15f4bb43da79f21ba446f2f79675750855031316c1e1a2a: context deadline exceeded" 
time="2016-10-06T19:13:34Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/portlayer/attach.(*Connector).Get:75] [30.000750093s] 31a66b66af69fa65e15f4bb43da79f21ba446f2f79675750855031316c1e1a2a" 
time="2016-10-06T19:13:34Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/portlayer/attach.(*Server).Get:90] [30.001194436s] 31a66b66af69fa65e15f4bb43da79f21ba446f2f79675750855031316c1e1a2a" 
time="2016-10-06T19:13:34Z" level=error msg="attach connector: Connection not found error for id:31a66b66af69fa65e15f4bb43da79f21ba446f2f79675750855031316c1e1a2a: context deadline exceeded" 
time="2016-10-06T19:13:34Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*InteractionHandlersImpl).ContainerGetStderrHandler:282] [30.00270243s] 31a66b66af69fa65e15f4bb43da79f21ba446f2f79675750855031316c1e1a2a" 
2016/10/06 19:13:34 http: panic serving 10.17.109.122:34582: runtime error: invalid memory address or nil pointer dereference
goroutine 808 [running]:
net/http.(*conn).serve.func1(0xc420b48c80)
    /usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0xe2d800, 0xc42000e050)
    /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/interaction.(*ContainerGetStderrNotFound).WriteResponse(0xc42001c468, 0x19ad620, 0xc42080f6c0, 0x0, 0x0)
    /home/hmahmood/go/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/interaction/container_get_stderr_responses.go:82 +0x5a
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.(*Context).Respond(0xc420204d00, 0x19ad620, 0xc42080f6c0, 0xc420641b30, 0xc4201d5980, 0x1, 0x1, 0xc420177ce0, 0xe60380, 0xc42001c468)
    /home/hmahmood/go/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/context.go:392 +0x424
github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/interaction.(*ContainerGetStderr).ServeHTTP(0xc42017f560, 0x19ad620, 0xc42080f6c0, 0xc420641b30)
    /home/hmahmood/go/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/interaction/container_get_stderr.go:53 +0x253
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.newOperationExecutor.func1(0x19ad620, 0xc42080f6c0, 0xc420641b30)
    /home/hmahmood/go/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/operation.go:23 +0x69
net/http.HandlerFunc.ServeHTTP(0xc420353a80, 0x19ad620, 0xc42080f6c0, 0xc420641b30)
    /usr/local/go/src/net/http/server.go:1726 +0x44
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.newRouter.func1(0x19ad620, 0xc42080f6c0, 0xc420641b30)
    /home/hmahmood/go/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/router.go:78 +0x555
net/http.HandlerFunc.ServeHTTP(0xc42055a1c0, 0x19ad620, 0xc42080f6c0, 0xc420641b30)
    /usr/local/go/src/net/http/server.go:1726 +0x44
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.specMiddleware.func1(0x19ad620, 0xc42080f6c0, 0xc420641b30)
    /home/hmahmood/go/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/spec.go:36 +0x7b
net/http.HandlerFunc.ServeHTTP(0xc42058ef00, 0x19ad620, 0xc42080f6c0, 0xc420641b30)
    /usr/local/go/src/net/http/server.go:1726 +0x44
net/http.serverHandler.ServeHTTP(0xc42062b300, 0x19ad620, 0xc42080f6c0, 0xc420641b30)
    /usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc420b48c80, 0x19ae1a0, 0xc420743040)
    /usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:2293 +0x44d
```

@hmahmood reported that he is seeing the trace above in the logs. I believe this is happening because https://github.com/vmware/vic/pull/2440#discussion_r81380590 as we started to return an error there instead of silently ignoring it.

**Comment by caglar10ur** [comment]
@sflxn do you mind checking the comment above?

**Comment by sflxn** [comment]
This looks oddly familiar, but we fixed something like this a few months ago.  Ok, maybe it wasn't a fix.  Someone bandaged it.  Is this occurring on return from that function?  Instead of returning additional errors, just return the defined Swagger defined ContainerGetStdoutNotFound.  That was the bandage from a few months back.  The panic we saw was occurring inside of the Swagger code.

**Comment by hickeng** [comment]
This piece of code is panicing, and while it says why in the comment I don't know why the recovery middleware isn't doing it's job:
```
// WriteResponse to the client
func (o *ContainerGetStdoutNotFound) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
```

**Comment by caglar10ur** [comment]
As I said above, we weren't returning an error there (https://github.com/vmware/vic/pull/2440#discussion_r81380590) and I introduced one. Looks like returning that causes swagger context to be nil hence panic.

As a workaround we can remove that error, will send a PR in a min. to do that
