### ISSUE TITLE
dio deadlock in CI

### ISSUE THREAD

**Issue by caglar10ur** [vmware/vic#2814]
from https://ci.vmware.run/vmware/vic/6065

```
time="2016-10-19T20:25:39Z" level=debug msg="[0xc420076b00] read from closed multi-reader, returning EOF" 
time="2016-10-19T20:25:39Z" level=debug msg="[0xc420076b00] read \"\" from 0 readers (err: &errors.errorString{s:\"EOF\"})" 
time="2016-10-19T20:25:39Z" level=debug msg="[0xc420077000] created multireader" 
time="2016-10-19T20:25:39Z" level=debug msg="[0xc420077000] read \"verify base multiwriter function\" from 2 readers (err: <nil>)" 
time="2016-10-19T20:25:39Z" level=debug msg="[0xc420077000] removing reader - currently 2 readers" 
time="2016-10-19T20:25:39Z" level=debug msg="[0xc420077000] removed reader - now 1 readers" 
time="2016-10-19T20:25:39Z" level=debug msg="[0xc420077000] Reader 0 [0xc42007a070]" 
time="2016-10-19T20:25:39Z" level=debug msg="[0xc420077000] removing reader due to EOF" 
time="2016-10-19T20:25:39Z" level=debug msg="[0xc420077000] removing reader - currently 1 readers" 
time="2016-10-19T20:25:39Z" level=debug msg="[0xc420077000] removed reader - now 0 readers" 
time="2016-10-19T20:25:39Z" level=debug msg="[0xc420077000] All of the readers returned EOF (1)" 
time="2016-10-19T20:25:39Z" level=debug msg="[0xc420077000] read \"\" from 1 readers (err: <nil>)" 
time="2016-10-19T20:25:39Z" level=debug msg="[0xc420077000] Going into sleep with 0 readers" 
time="2016-10-19T20:25:39Z" level=debug msg="[0xc420077000] read \"verify dynamic remove\" from 1 readers (err: <nil>)" 
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive]:
testing.(*T).Run(0xc42006e0c0, 0x528b52, 0xe, 0x537990, 0xc42003bc01)
    /usr/local/go/src/testing/testing.go:647 +0x316
testing.RunTests.func1(0xc42006e0c0)
    /usr/local/go/src/testing/testing.go:793 +0x6d
testing.tRunner(0xc42006e0c0, 0xc42003bd88)
    /usr/local/go/src/testing/testing.go:610 +0x81
testing.RunTests(0x5379c0, 0x5b9b40, 0x8, 0x8, 0x40edae)
    /usr/local/go/src/testing/testing.go:799 +0x2f5
testing.(*M).Run(0xc42003bee8, 0x52dd80)
    /usr/local/go/src/testing/testing.go:743 +0x85
main.main()
    github.com/vmware/vic/pkg/dio/_test/_testmain.go:118 +0x1bd

goroutine 30 [semacquire]:
sync.runtime_notifyListWait(0xc420077050, 0xc400000000)
    /usr/local/go/src/runtime/sema.go:267 +0x122
sync.(*Cond).Wait(0xc420077040)
    /usr/local/go/src/sync/cond.go:57 +0x80
github.com/vmware/vic/pkg/dio.(*multiReader).Read(0xc420077000, 0xc420097400, 0x15, 0x200, 0x0, 0x0, 0x0)
    github.com/vmware/vic/pkg/dio/_test/_obj_test/reader.go:76 +0x279
io.(*LimitedReader).Read(0xc42007cde0, 0xc420097400, 0x200, 0x200, 0x0, 0x0, 0x0)
    /usr/local/go/src/io/io.go:436 +0x6c
bytes.(*Buffer).ReadFrom(0xc4200a4230, 0x5a7480, 0xc42007cde0, 0xc420089cb0, 0x1, 0x18)
    /usr/local/go/src/bytes/buffer.go:176 +0x155
io.copyBuffer(0x5a7340, 0xc4200a4230, 0x5a7480, 0xc42007cde0, 0x0, 0x0, 0x0, 0x50c040, 0x7fa8f6d74001, 0xc42007cde0)
    /usr/local/go/src/io/io.go:384 +0x323
io.Copy(0x5a7340, 0xc4200a4230, 0x5a7480, 0xc42007cde0, 0x507c80, 0x50b200, 0xc420089d00)
    /usr/local/go/src/io/io.go:360 +0x68
io.CopyN(0x5a7340, 0xc4200a4230, 0x7fa8f6d74078, 0xc420077000, 0x15, 0xc420077000, 0xc4200a4230, 0xc420078cc0)
    /usr/local/go/src/io/io.go:336 +0x8c
github.com/vmware/vic/pkg/dio.TestReadRemove(0xc420078cc0)
    /drone/src/github.com/vmware/vic/pkg/dio/multi_test.go:359 +0x8c8
testing.tRunner(0xc420078cc0, 0x537990)
    /usr/local/go/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
    /usr/local/go/src/testing/testing.go:646 +0x2ec

goroutine 17 [semacquire]:
sync.runtime_notifyListWait(0xc420078040, 0x0)
    /usr/local/go/src/runtime/sema.go:267 +0x122
sync.(*Cond).Wait(0xc420078030)
    /usr/local/go/src/sync/cond.go:57 +0x80
io.(*pipe).read(0xc420078000, 0xc420098020, 0x5e0, 0x5e0, 0x0, 0x0, 0x0)
    /usr/local/go/src/io/pipe.go:47 +0x102
io.(*PipeReader).Read(0xc42007a000, 0xc420098020, 0x5e0, 0x5e0, 0x20, 0x0, 0x0)
    /usr/local/go/src/io/pipe.go:129 +0x4c
bytes.(*Buffer).ReadFrom(0xc4200820e0, 0x5a74c0, 0xc42007a000, 0xc420025ef8, 0xc420078001, 0x0)
    /usr/local/go/src/bytes/buffer.go:176 +0x155
io.copyBuffer(0x5a7340, 0xc4200820e0, 0x5a74c0, 0xc42007a000, 0x0, 0x0, 0x0, 0xc42007a008, 0x5a7500, 0xc42007a018)
    /usr/local/go/src/io/io.go:384 +0x323
io.Copy(0x5a7340, 0xc4200820e0, 0x5a74c0, 0xc42007a000, 0x0, 0x0, 0x0)
    /usr/local/go/src/io/io.go:360 +0x68
created by github.com/vmware/vic/pkg/dio.TestMultiWrite
    /drone/src/github.com/vmware/vic/pkg/dio/multi_test.go:43 +0x322

goroutine 18 [semacquire]:
sync.runtime_notifyListWait(0xc420078100, 0x1)
    /usr/local/go/src/runtime/sema.go:267 +0x122
sync.(*Cond).Wait(0xc4200780f0)
    /usr/local/go/src/sync/cond.go:57 +0x80
io.(*pipe).read(0xc4200780c0, 0xc420098620, 0x5e0, 0x5e0, 0x0, 0x0, 0x0)
    /usr/local/go/src/io/pipe.go:47 +0x102
io.(*PipeReader).Read(0xc42007a010, 0xc420098620, 0x5e0, 0x5e0, 0x20, 0x0, 0x0)
    /usr/local/go/src/io/pipe.go:129 +0x4c
bytes.(*Buffer).ReadFrom(0xc420082150, 0x5a74c0, 0xc42007a010, 0xc4200206f8, 0x1, 0x0)
    /usr/local/go/src/bytes/buffer.go:176 +0x155
io.copyBuffer(0x5a7340, 0xc420082150, 0x5a74c0, 0xc42007a010, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/io/io.go:384 +0x323
io.Copy(0x5a7340, 0xc420082150, 0x5a74c0, 0xc42007a010, 0x0, 0x0, 0x0)
    /usr/local/go/src/io/io.go:360 +0x68
created by github.com/vmware/vic/pkg/dio.TestMultiWrite
    /drone/src/github.com/vmware/vic/pkg/dio/multi_test.go:44 +0x36c

goroutine 20 [semacquire]:
sync.runtime_notifyListWait(0xc420078340, 0x1)
    /usr/local/go/src/runtime/sema.go:267 +0x122
sync.(*Cond).Wait(0xc420078330)
    /usr/local/go/src/sync/cond.go:57 +0x80
io.(*pipe).read(0xc420078300, 0xc420098c32, 0x5ce, 0x5ce, 0x0, 0x0, 0x0)
    /usr/local/go/src/io/pipe.go:47 +0x102
io.(*PipeReader).Read(0xc42007a020, 0xc420098c32, 0x5ce, 0x5ce, 0x12, 0x0, 0x0)
    /usr/local/go/src/io/pipe.go:129 +0x4c
bytes.(*Buffer).ReadFrom(0xc4200823f0, 0x5a74c0, 0xc42007a020, 0xc420020ef8, 0x1, 0x0)
    /usr/local/go/src/bytes/buffer.go:176 +0x155
io.copyBuffer(0x5a7340, 0xc4200823f0, 0x5a74c0, 0xc42007a020, 0x0, 0x0, 0x0, 0x485f52, 0x5807d6c3, 0xc41ef17ce3)
    /usr/local/go/src/io/io.go:384 +0x323
io.Copy(0x5a7340, 0xc4200823f0, 0x5a74c0, 0xc42007a020, 0x0, 0x0, 0x0)
    /usr/local/go/src/io/io.go:360 +0x68
created by github.com/vmware/vic/pkg/dio.TestWriteAdd
    /drone/src/github.com/vmware/vic/pkg/dio/multi_test.go:76 +0x2fa

goroutine 21 [semacquire]:
sync.runtime_notifyListWait(0xc420078400, 0x1)
    /usr/local/go/src/runtime/sema.go:267 +0x122
sync.(*Cond).Wait(0xc4200783f0)
    /usr/local/go/src/sync/cond.go:57 +0x80
io.(*pipe).read(0xc4200783c0, 0xc420099212, 0x5ee, 0x5ee, 0x0, 0x0, 0x0)
    /usr/local/go/src/io/pipe.go:47 +0x102
io.(*PipeReader).Read(0xc42007a030, 0xc420099212, 0x5ee, 0x5ee, 0x12, 0x0, 0x0)
    /usr/local/go/src/io/pipe.go:129 +0x4c
bytes.(*Buffer).ReadFrom(0xc420082460, 0x5a74c0, 0xc42007a030, 0xc4200216f8, 0x1, 0x0)
    /usr/local/go/src/bytes/buffer.go:176 +0x155
io.copyBuffer(0x5a7340, 0xc420082460, 0x5a74c0, 0xc42007a030, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/io/io.go:384 +0x323
io.Copy(0x5a7340, 0xc420082460, 0x5a74c0, 0xc42007a030, 0x0, 0x0, 0x0)
    /usr/local/go/src/io/io.go:360 +0x68
created by github.com/vmware/vic/pkg/dio.TestWriteAdd
    /drone/src/github.com/vmware/vic/pkg/dio/multi_test.go:77 +0x344

goroutine 23 [semacquire]:
sync.runtime_notifyListWait(0xc420078580, 0x1)
    /usr/local/go/src/runtime/sema.go:267 +0x122
sync.(*Cond).Wait(0xc420078570)
    /usr/local/go/src/sync/cond.go:57 +0x80
io.(*pipe).read(0xc420078540, 0xc420099835, 0x5cb, 0x5cb, 0x0, 0x0, 0x0)
    /usr/local/go/src/io/pipe.go:47 +0x102
io.(*PipeReader).Read(0xc42007a040, 0xc420099835, 0x5cb, 0x5cb, 0x15, 0x0, 0x0)
    /usr/local/go/src/io/pipe.go:129 +0x4c
bytes.(*Buffer).ReadFrom(0xc420082a10, 0x5a74c0, 0xc42007a040, 0xc420021ef8, 0x1, 0x0)
    /usr/local/go/src/bytes/buffer.go:176 +0x155
io.copyBuffer(0x5a7340, 0xc420082a10, 0x5a74c0, 0xc42007a040, 0x0, 0x0, 0x0, 0xc42007a048, 0x5a7500, 0xc42007a058)
    /usr/local/go/src/io/io.go:384 +0x323
io.Copy(0x5a7340, 0xc420082a10, 0x5a74c0, 0xc42007a040, 0x0, 0x0, 0x0)
    /usr/local/go/src/io/io.go:360 +0x68
created by github.com/vmware/vic/pkg/dio.TestWriteRemove
    /drone/src/github.com/vmware/vic/pkg/dio/multi_test.go:131 +0x322

goroutine 24 [semacquire]:
sync.runtime_notifyListWait(0xc420078640, 0x1)
    /usr/local/go/src/runtime/sema.go:267 +0x122
sync.(*Cond).Wait(0xc420078630)
    /usr/local/go/src/sync/cond.go:57 +0x80
io.(*pipe).read(0xc420078600, 0xc4200a0020, 0x5e0, 0x5e0, 0x0, 0x0, 0x0)
    /usr/local/go/src/io/pipe.go:47 +0x102
io.(*PipeReader).Read(0xc42007a050, 0xc4200a0020, 0x5e0, 0x5e0, 0x20, 0x0, 0x0)
    /usr/local/go/src/io/pipe.go:129 +0x4c
bytes.(*Buffer).ReadFrom(0xc420082a80, 0x5a74c0, 0xc42007a050, 0xc4200226f8, 0x1, 0x0)
    /usr/local/go/src/bytes/buffer.go:176 +0x155
io.copyBuffer(0x5a7340, 0xc420082a80, 0x5a74c0, 0xc42007a050, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/io/io.go:384 +0x323
io.Copy(0x5a7340, 0xc420082a80, 0x5a74c0, 0xc42007a050, 0x0, 0x0, 0x0)
    /usr/local/go/src/io/io.go:360 +0x68
created by github.com/vmware/vic/pkg/dio.TestWriteRemove
    /drone/src/github.com/vmware/vic/pkg/dio/multi_test.go:132 +0x36c

goroutine 34 [chan receive]:
github.com/vmware/vic/pkg/dio.TestReadRemove.func4(0xc420080f40, 0xc420090960, 0x5a8500, 0xc420077000, 0xc4200a4230, 0xc420078cc0)
    /drone/src/github.com/vmware/vic/pkg/dio/multi_test.go:349 +0x78
created by github.com/vmware/vic/pkg/dio.TestReadRemove
    /drone/src/github.com/vmware/vic/pkg/dio/multi_test.go:356 +0x852
FAIL    github.com/vmware/vic/pkg/dio   0.009s
make: *** [test-job-github.com/vmware/vic/pkg] Error 1
make: *** Waiting for unfinished jobs....
Makefile:242: recipe for target 'test-job-github.com/vmware/vic/pkg' failed
```

**Comment by caglar10ur** [comment]
logs: https://console.cloud.google.com/m/cloudstorage/b/vic-ci-logs/o/integration_logs_6065_dbcf4e9844781044b819400b52347beda198ac7f.zip?authuser=1

**Comment by caglar10ur** [comment]
Removed the kind/bug/p0 label. As far as I see this is a test problem which will be fixed with a PR shortly

**Comment by mhagen-vmware** [comment]
moving to .9 as technical debt, on the understanding this is a test issue
