### ISSUE TITLE
`docker-compose logs` fails, but `docker logs` is fine

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#2858]
When running docker-compose logs in the 3-03 test I see the following:
```
root@94ee0653f0d3:/tmp# docker-compose --file basic-compose.yml logs
Attaching to mp_web_2, mp_redis_1
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 61, in main
  File "compose/cli/main.py", line 113, in perform_command
  File "contextlib.py", line 35, in __exit__
  File "compose/cli/errors.py", line 56, in handle_connection_errors
TypeError: log_timeout_error() takes exactly 1 argument (0 given)
docker-compose returned -1
root@94ee0653f0d3:/tmp# docker-compose --file basic-compose.yml logs
Attaching to mp_web_2, mp_redis_1
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 61, in main
  File "compose/cli/main.py", line 113, in perform_command
  File "contextlib.py", line 35, in __exit__
  File "compose/cli/errors.py", line 56, in handle_connection_errors
TypeError: log_timeout_error() takes exactly 1 argument (0 given)
docker-compose returned -1
root@94ee0653f0d3:/tmp#
```

However I can see in the port layer log that we finished sending both logs.
I've run the plain `docker logs` command in parallel for the two containers, in a tight loop with no problems:
```
while true; do
   docker logs tmp_web_2 || break & docker logs tmp_redis_1 || break;
done
```

The last log collection in the log bundle is from a failing `docker-compose logs` attempt.
[container-logs (10).zip](https://github.com/vmware/vic/files/546081/container-logs.10.zip)

**Comment by hickeng** [comment]
Turns out this was an issue with copying the container struct to avoid inspection of a live object. The embedded mutex may have been locked (which illustrates that our inspection was previously interleaving with another operation VERY FREQUENTLY) and would therefore never be unlocked in the copy.

#2820 addresses this in a very mediocre fashion - a clear separation between structure returned for inspection and the live object used for internal manipulations is needed, but this change is too pervasive to undertake until we move the cache out of exec and to a general port layer service for hosted component, in a similar fashion to events and vmomi gateway.

**Comment by hickeng** [comment]
This specific behaviour was introduced in the branch, while addressing a consistency problem. Not present in this form in master.
