### ISSUE TITLE
Nimbus ESX 5.5 build 3029944 fails to deploy

### ISSUE THREAD

**Issue by rajanashok** [vmware/vic#2962]
Full Name:	5-5-Heterogenous-ESXi.Test
Start / End / Elapsed:	20161101 00:14:13.966 / 20161101 00:19:11.231 / 00:04:57.265
Status:	FAIL (critical)
Message:	'2016-10-31 22:19:09 -0700: Deploying build 3029944 to /mts/home5/rashok/public_html/pxe/3029944...
2016-10-31 22:19:09 -0700: Checking if no body else is doing the job for us...may wait for 20 minutes
2016-10-31 22:19:09 -0700: Lock check finished, 0
2016-10-31 22:19:09 -0700: Running "/build/apps/bin/pxe-deploy  preferredDeploy=copy force_tftp=True  pxedir=/mts/home5/rashok/public_html/pxe/3029944 buildnum=3029944 pxe_abspath=True 2>&1"...
[2016-10-31 22:19:10,045] process.py:15 - Execute: i d   - u n
[2016-10-31 22:19:10,257] __init__.py:78 - get_params: Process plugin: DeployPlugin
[2016-10-31 22:19:10,257] __init__.py:78 - get_params: Process plugin: Defaults
[2016-10-31 22:19:10,257] __init__.py:78 - get_params: Process plugin: Files
[2016-10-31 22:19:10,257] __init__.py:78 - get_params: Process plugin: DevLogin
[2016-10-31 22:19:10,258] __init__.py:78 - get_params: Process plugin: StaticIP
[2016-10-31 22:19:10,258] __init__.py:78 - get_params: Process plugin: NFSMount
    [ Message content over the limit has been removed. ]
...olchain/lin64/ruby/2.2.0/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
2016-10-31 22:19:11 -0700: /mts/git/nimbus-toolchain/lin64/ruby/2.2.0/lib/ruby/2.2.0/timeout.rb:34:in `block in catch'
2016-10-31 22:19:11 -0700: /mts/git/nimbus-toolchain/lin64/ruby/2.2.0/lib/ruby/2.2.0/timeout.rb:34:in `catch'
2016-10-31 22:19:11 -0700: /mts/git/nimbus-toolchain/lin64/ruby/2.2.0/lib/ruby/2.2.0/timeout.rb:34:in `catch'
2016-10-31 22:19:11 -0700: /mts/git/nimbus-toolchain/lin64/ruby/2.2.0/lib/ruby/2.2.0/timeout.rb:104:in `timeout'
2016-10-31 22:19:11 -0700: /mts/git/nimbus-toolchain/lin64/ruby/2.2.0/lib/ruby/2.2.0/timeout.rb:125:in `timeout'
2016-10-31 22:19:11 -0700: /mts/git/nimbus/lib/nimbus/base_deploy.rb:537:in `run_cli'
2016-10-31 22:19:11 -0700: /mts/git/bin/../nimbus/lib/nimbus/deploys/esx/esx_deploy.rb:1497:in `<main>'
2016-10-31 22:19:11 -0700: Writing deployment results...
2016-10-31 22:19:11 -0700: Exception: RbVmomiUtils::PxeDeployError: pxe-deploy failed : /build/apps/bin/pxe-deploy  preferredDeploy=copy force_tftp=True  pxedir=/mts/home5/rashok/public_html/pxe/3029944 buildnum=3029944 pxe_abspath=True 2>&1' does not contain 'To manage this VM use'

**Comment by rajanashok** [comment]
Cleaning up the pxe folder resolved this, not an issue anymore.
