### ISSUE TITLE
registering a vm causes portlayer panic

### ISSUE THREAD

**Issue by cgtexmex** [vmware/vic#3201]
registering a vm in vsphere (standalone or cluster) will result in a portlayer panic.  

```
govc ls vm
/dc-florence/vm/vickie
/dc-florence/vm/jojoTest
/dc-florence/vm/Discovered virtual machine

govc vm.unregister jojoTest
govc vm.register "/jojoTest/jojoTest.vmx"
```

results in:
```
time=2016-11-16T20:32:53.399909397Z level=debug msg=[ END ] [github.com/vmware/vic/lib/portlayer/exec.registeredVMCallback:177] [2.820165ms] Event(Registered) Ref(VirtualMachine:13) 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7d8e34]

goroutine 54 [running]:
panic(0xe7fc00, 0xc420014040)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/vmware/vic/lib/portlayer/exec.isManagedbyVCH(0xc42023a000, 0xc4206e10a0, 0xe, 0xc4206e10af, 0x2, 0xc4203e8a00)
	/go/src/github.com/vmware/vic/lib/portlayer/exec/exec.go:226 +0x444
github.com/vmware/vic/lib/portlayer/exec.registeredVMCallback(0xc42023a000, 0x1a359a0, 0xc42041c1a0)
	/go/src/github.com/vmware/vic/lib/portlayer/exec/exec.go:192 +0x32e
github.com/vmware/vic/lib/portlayer/exec.Init.func1.2(0x1a359a0, 0xc42041c1a0)
	/go/src/github.com/vmware/vic/lib/portlayer/exec/exec.go:104 +0x3e
github.com/vmware/vic/lib/portlayer/event.(*Manager).Publish.func1(0xc420856c00, 0x1a359a0, 0xc42041c1a0)
	/go/src/github.com/vmware/vic/lib/portlayer/event/manager.go:151 +0x35a
created by github.com/vmware/vic/lib/portlayer/event.(*Manager).Publish
	/go/src/github.com/vmware/vic/lib/portlayer/event/manager.go:153 +0x53
```

**Comment by cgtexmex** [comment]
#3203 will create a regression / integration test for the issue

**Comment by cgtexmex** [comment]
PR comment incorrectly identified issue that was fixed...fix has been merged.
