### ISSUE TITLE
CI failure: portlayer panic while handling docker logs request

### ISSUE THREAD

**Issue by vburenin** [vmware/vic#3254]
Test failure:
```
==============================================================================
Test-Cases.Group1-Docker-Commands.1-07-Docker-Stop :: Test 1-07 - Docker Stop 
==============================================================================
Stop a container with SIGKILL using specific grace period             | FAIL |
'' does not contain 'StopSignalHUP'
```

The container's `output.log` has the output but `docker logs` didn't grab it. From portlayer logs:
```
time=2016-11-20T16:01:09.067864996Z level=debug msg=[BEGIN] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).GetContainerLogsHandler:336] 4a8b138affcce24660732dcf47fb540e8b72a4e8270f3218e9f5dc7df284500b 
time=2016-11-20T16:01:09.067935766Z level=debug msg=[ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).GetContainerLogsHandler:336] [70.399µs] 4a8b138affcce24660732dcf47fb540e8b72a4e8270f3218e9f5dc7df284500b 
2016/11/20 16:01:09 http: panic serving 192.168.31.234:36466: runtime error: invalid memory address or nil pointer dereference
goroutine 182 [running]:
net/http.(*conn).serve.func1(0xc4203f9780)
    /usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0xe7ffe0, 0xc420016040)
    /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/containers.(*GetContainerLogsNotFound).WriteResponse(0xc42041cb98, 0x1a333e0, 0xc4206a4f70, 0x0, 0x0)
    /drone/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/containers/get_container_logs_responses.go:82 +0x5a
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.(*Context).Respond(0xc4208148c0, 0x1a333e0, 0xc4206a4f70, 0xc4204a1770, 0xc42057f1c0, 0x1, 0x1, 0xc420123340, 0xeb2e40, 0xc42041cb98)
    /drone/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/context.go:392 +0x424
github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/containers.(*GetContainerLogs).ServeHTTP(0xc420137e20, 0x1a333e0, 0xc4206a4f70, 0xc4204a1770)
    /drone/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/containers/get_container_logs.go:53 +0x313
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.newOperationExecutor.func1(0x1a333e0, 0xc4206a4f70, 0xc4204a1770)
    /drone/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/operation.go:23 +0x69
net/http.HandlerFunc.ServeHTTP(0xc420592b80, 0x1a333e0, 0xc4206a4f70, 0xc4204a1770)
    /usr/local/go/src/net/http/server.go:1726 +0x44
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.newRouter.func1(0x1a333e0, 0xc4206a4f70, 0xc4204a1770)
    /drone/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/router.go:78 +0x555
net/http.HandlerFunc.ServeHTTP(0xc420885200, 0x1a333e0, 0xc4206a4f70, 0xc4204a1770)
    /usr/local/go/src/net/http/server.go:1726 +0x44
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.specMiddleware.func1(0x1a333e0, 0xc4206a4f70, 0xc4204a1770)
    /drone/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/spec.go:36 +0x7b
net/http.HandlerFunc.ServeHTTP(0xc4205ecda0, 0x1a333e0, 0xc4206a4f70, 0xc4204a1770)
    /usr/local/go/src/net/http/server.go:1726 +0x44
net/http.serverHandler.ServeHTTP(0xc420458600, 0x1a333e0, 0xc4206a4f70, 0xc4204a1770)
    /usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc4203f9780, 0x1a33f60, 0xc420236fc0)
    /usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:2293 +0x44d
```

[Test-Cases.Group1-Docker-Commands.1-07-Docker-Stop-VCH-7124-8900-container-logs.zip](https://github.com/vmware/vic/files/602242/Test-Cases.Group1-Docker-Commands.1-07-Docker-Stop-VCH-7124-8900-container-logs.zip)
Container ID: `4a8b138affcce24660732dcf47fb540e8b72a4e8270f3218e9f5dc7df284500b`

**Comment by mdubya66** [comment]
From build https://ci.vmware.run/vmware/vic/7124
[integration_logs_7124_dcd7d2ec1e794f2b65112de8c514e4c39f9674c9.zip](https://github.com/vmware/vic/files/602231/integration_logs_7124_dcd7d2ec1e794f2b65112de8c514e4c39f9674c9.zip)

**Comment by anchal-agrawal** [comment]
Dup of #3261
