### ISSUE TITLE
vic-admin times out and prevents re-login

### ISSUE THREAD

**Issue by mdubya66** [vmware/vic#3258]
Using  vic-machine-darwin version v0.7.0-7115-d58eb98

<img width="1092" alt="screen shot 2016-11-20 at 3 00 21 pm" src="https://cloud.githubusercontent.com/assets/15821624/20466125/87f205de-af32-11e6-9eb2-8cb5835f67e5.png">

Panic seen in vicadmin.log

ime="2016-11-20T21:00:48Z" level=info msg="Setting hostname to vch7115"
time=2016-11-20T21:00:48.976850527Z level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.CreateFromVCHConfig:62]
time=2016-11-20T21:00:48.976856811Z level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.CreateFromVCHConfig:62] [4.53µs]
time="2016-11-20T21:00:48Z" level=info msg="Using management IP {172.16.127.199 ffffff00} for firewall check"
time="2016-11-20T21:00:48Z" level=error msg="Unable to get the list of hosts attached to given storage: NotAuthenticated"
time="2016-11-20T21:00:49Z" level=info msg="FirewallStatus set to: <i class=\"icon-attention\"></i>"
time="2016-11-20T21:00:49Z" level=info msg="FirewallIssues set to: <span class=\"error-message\">NotAuthenticated</span>\n"
time="2016-11-20T21:00:49Z" level=info msg="LicenseStatus set to: <i class=\"icon-attention\"></i>"
time="2016-11-20T21:00:49Z" level=info msg="LicenseIssues set to: <span class=\"error-message\">NotAuthenticated</span>\n"
time="2016-11-20T21:00:49Z" level=info msg="NetworkStatus set to: <i class=\"icon-ok\"></i>"
time="2016-11-20T21:00:49Z" level=info msg="NetworkIssues set to: "
time="2016-11-20T21:00:49Z" level=error msg="Unable to collect information for datastore datastore1: NotAuthenticated"
time=2016-11-20T21:00:49.181227079Z level=debug msg=[ END ] [github.com/vmware/vic/lib/vicadmin.NewValidator:106] [204.405796ms]
time=2016-11-20T21:00:49.181247539Z level=debug msg=[ END ] [main.(*server).index:551] [204.446849ms]
2016/11/20 21:00:49 http: panic serving 172.16.127.1:57050: runtime error: invalid memory address or nil pointer dereference
goroutine 482 [running]:
net/http.(*conn).serve.func1(0xc42052b080)
        /usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0xccc320, 0xc420010060)
        /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/vmware/vic/vendor/github.com/vmware/govmomi/property.(*Collector).Retrieve(0xc42030ca60, 0x17470c0, 0xc420010288, 0x177b410, 0x0, 0x0, 0x0, 0x0, 0x0, 0xcf7900, ...)
        /drone/src/github.com/vmware/vic/vendor/github.com/vmware/govmomi/property/collector.go:157 +0x53b
github.com/vmware/vic/lib/vicadmin.(*Validator).QueryDatastore(0xc4203045a0, 0x17470c0, 0xc420010288, 0x175f3e0, 0xc4202fa500)
        /drone/src/github.com/vmware/vic/lib/vicadmin/validate.go:256 +0x8fe
github.com/vmware/vic/lib/vicadmin.NewValidator(0x17470c0, 0xc420010288, 0x175f3e0, 0xc4202fa500, 0x0)
        /drone/src/github.com/vmware/vic/lib/vicadmin/validate.go:212 +0xc22
main.(*server).index(0xc42026f9b0, 0x1746540, 0xc4203b28f0, 0xc4203044b0)
        /drone/src/github.com/vmware/vic/cmd/vicadmin/server.go:554 +0x114
main.(*server).(main.index)-fm(0x1746540, 0xc4203b28f0, 0xc4203044b0)
        /drone/src/github.com/vmware/vic/cmd/vicadmin/server.go:396 +0x48
main.(*server).Authenticated.func1(0x1746540, 0xc4203b28f0, 0xc4203044b0)
        /drone/src/github.com/vmware/vic/cmd/vicadmin/server.go:261 +0x1198
net/http.HandlerFunc.ServeHTTP(0xc4202a08e0, 0x1746540, 0xc4203b28f0, 0xc4203044b0)
        /usr/local/go/src/net/http/server.go:1726 +0x44
github.com/vmware/vic/vendor/github.com/gorilla/context.ClearHandler.func1(0x1746540, 0xc4203b28f0, 0xc4203044b0)
        /drone/src/github.com/vmware/vic/vendor/github.com/gorilla/context/context.go:141 +0x8b
net/http.HandlerFunc.ServeHTTP(0xc4202a0900, 0x1746540, 0xc4203b28f0, 0xc4203044b0)
        /usr/local/go/src/net/http/server.go:1726 +0x44
net/http.(*ServeMux).ServeHTTP(0xc4202985a0, 0x1746540, 0xc4203b28f0, 0xc4203044b0)
        /usr/local/go/src/net/http/server.go:2022 +0x7f
net/http.serverHandler.ServeHTTP(0xc42006f600, 0x1746540, 0xc4203b28f0, 0xc4203044b0)
        /usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc42052b080, 0x1747080, 0xc42044e780)
        /usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2293 +0x44d

[vicadmin.log.zip](https://github.com/vmware/vic/files/602332/vicadmin.log.zip)

**Comment by mdubya66** [comment]
Actually this is happening even without a timeout. I select a log to view and then click back and I get the above screen. A shift reload works around it. There is no panic in this instance so we might have two issues here.

**Comment by mdubya66** [comment]
clearing the session cookie in my browser for 172.16.127.199 enabled login again.

**Comment by mdubya66** [comment]
Here's the log after clearing the session cookie. 
[vicadmin.log.txt](https://github.com/vmware/vic/files/602346/vicadmin.log.txt)

**Comment by mdubya66** [comment]
Closing as #3270 was merged
