### ISSUE TITLE
[port-layer] panic: sync: negative WaitGroup counter

### ISSUE THREAD

**Issue by caglar10ur** [vmware/vic#3489]
@hickeng reported following panic while testing some stuff

```
time="2016-12-12T22:46:24Z" level=warning msg="Re-launching process for session port-layer (count: 3304)" ^M
panic: sync: negative WaitGroup counter^M
^M
goroutine 16 [running]:^M
panic(0xae02e0, 0xc4204d9900)^M
        /usr/local/go/src/runtime/panic.go:500 +0x1a1^M
sync.(*WaitGroup).Add(0xc420128da0, 0xffffffffffffffff)^M
        /usr/local/go/src/sync/waitgroup.go:75 +0x1fe^M
sync.(*WaitGroup).Done(0xc420128da0)^M
        /usr/local/go/src/sync/waitgroup.go:100 +0x34^M
github.com/vmware/vic/lib/tether.establishNonPty.func2(0xc4200bd600)^M
        /home/vagrant/vicsmb/src/github.com/vmware/vic/lib/tether/tether_linux.go:296 +0x217^M
created by github.com/vmware/vic/lib/tether.establishNonPty^M
        /home/vagrant/vicsmb/src/github.com/vmware/vic/lib/tether/tether_linux.go:297 +0x2eb^M
```

**Comment by caglar10ur** [comment]
HEAD is at commit 1a3035694a0212ed2bfbd9bf4a37dbbaef1df701

**Comment by caglar10ur** [comment]
This is fixed long ago
