### ISSUE TITLE
ValidateCreateConfig fails if HostConfig is not specified in the form data of docker rest api call

### ISSUE THREAD

**Issue by chengwang86** [vmware/vic#3709]
**VIC version:**

0.8

**Steps to reproduce:**

1. create a network alp-network
2. pull image alpine
3. curl --insecure --cert cert.pem --key key.pem -H "Content-Type: application/json" -d '{"Image": "alpine", "Cmd": ["ping", "127.0.0.1"], "NetworkMode": "alp-network"}' https://$IP:2376/containers/create?name=alp-1

**Actual behavior:**
Panic:
```
time=2016-12-13T14:00:51.474679848Z level=debug msg=[BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.validateCreateConfig:1336] Container.validateCreateConfig 
time=2016-12-13T14:00:51.474750805Z level=debug msg=[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.validateCreateConfig:1336] [67.144µs] Container.validateCreateConfig 
time=2016-12-13T14:00:51.474758553Z level=debug msg=[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerCreate:223] [226.937µs]  
2016/12/13 14:00:51 http: panic serving 192.168.60.129:59356: runtime error: invalid memory address or nil pointer dereference
goroutine 199 [running]:
net/http.(*conn).serve.func1(0xc420c9af00)
    /usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0x1073680, 0xc42000e060)
    /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/vmware/vic/lib/apiservers/engine/backends.validateCreateConfig(0xc4207b1540, 0x0, 0x0)
    /home/wangcheng/go/src/github.com/vmware/vic/lib/apiservers/engine/backends/container.go:1342 +0xac
github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerCreate(0xc420468910, 0xc42047390d, 0x5, 0xc420ccb440, 0x0, 0xc42001cec0, 0x0, 0x0, 0x0, 0x0, ...)
    /home/wangcheng/go/src/github.com/vmware/vic/lib/apiservers/engine/backends/container.go:246 +0x1fd
github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/container.(*containerRouter).postContainersCreate(0xc4203c62d0, 0x7f8b86506938, 0xc42043e030, 0x1d8fb60, 0xc420cab1e0, 0xc420cce870, 0xc420473b90, 0x1d90d60, 0xc42043e030)
```

**Expected behavior:**
The container is created successfully as on regular docker.

I think the culprit is
https://github.com/vmware/vic/blame/master/lib/apiservers/engine/backends/container.go#L1342
https://github.com/vmware/vic/blame/master/lib/apiservers/engine/backends/container.go#L1384
If HostConfig is not specified, we throw an error with "invalid config" instead of creating a default one.

This relates to https://github.com/vmware/vic/issues/2557

**Comment by chengwang86** [comment]
Fixed by #3831
