### ISSUE TITLE
Panic when trying to start a container that is supposed to connect to a deleted network

### ISSUE THREAD

**Issue by hmahmood** [vmware/vic#3948]
Steps to reproduce:
1. Create a new network with `docker network create`
2. Create and run a container connected to the network in (1.)
3. Stop the container in (2.)
4. Delete the network created in (1.) with `docker network rm`
5. Start the container in (2.) with `docker start`

Stack trace:
```
2017/02/14 18:51:03 http: panic serving 172.16.127.178:44738: runtime error: invalid memory address or nil pointer dereference
goroutine 51 [running]:
net/http.(*conn).serve.func1(0xc420be8d00)
	/usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0xf43580, 0xc420014040)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/vmware/vic/lib/portlayer/network.(*ResourceNotFoundError).Error(0xc4208788f0, 0x412488, 0x8)
	<autogenerated>:18 +0x3b
github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.errorPayload(0x1b823a0, 0xc4208788f0, 0x0)
	/home/hmahmood/go/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers/scopes_handlers.go:100 +0x35
github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ScopesHandlersImpl).ScopesBindContainer(0xc42042e900, 0xc420970870, 0xc4204a95a8, 0x20, 0x0, 0x0)
	/home/hmahmood/go/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers/scopes_handlers.go:269 +0x41a
github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ScopesHandlersImpl).ScopesBindContainer-fm(0xc420970870, 0xc4204a95a8, 0x20, 0x30003c420615e01, 0xc42087a460)
	/home/hmahmood/go/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers/scopes_handlers.go:50 +0x48
github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/scopes.BindContainerHandlerFunc.Handle(0xc420502310, 0xc420970870, 0xc4204a95a8, 0x20, 0xc42087a460, 0x0)
	/home/hmahmood/go/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/scopes/bind_container.go:17 +0x44
github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/scopes.(*BindContainer).ServeHTTP(0xc4205a7240, 0x1b8e560, 0xc420d72c30, 0xc420970870)
	/home/hmahmood/go/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/scopes/bind_container.go:49 +0x1a1
github.com/vmware/vic/vendor/github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1(0x1b8e560, 0xc420d72c30, 0xc420970870)
	/home/hmahmood/go/src/github.com/vmware/vic/vendor/github.com/go-openapi/runtime/middleware/operation.go:24 +0x69
net/http.HandlerFunc.ServeHTTP(0xc4204d2fc0, 0x1b8e560, 0xc420d72c30, 0xc420970870)
	/usr/local/go/src/net/http/server.go:1726 +0x44
github.com/vmware/vic/vendor/github.com/go-openapi/runtime/middleware.NewRouter.func1(0x1b8e560, 0xc420d72c30, 0xc420970870)
	/home/hmahmood/go/src/github.com/vmware/vic/vendor/github.com/go-openapi/runtime/middleware/router.go:75 +0xe2
net/http.HandlerFunc.ServeHTTP(0xc42065e540, 0x1b8e560, 0xc420d72c30, 0xc420970870)
	/usr/local/go/src/net/http/server.go:1726 +0x44
github.com/vmware/vic/vendor/github.com/go-openapi/runtime/middleware.Redoc.func1(0x1b8e560, 0xc420d72c30, 0xc420970870)
	/home/hmahmood/go/src/github.com/vmware/vic/vendor/github.com/go-openapi/runtime/middleware/redoc.go:72 +0xac
net/http.HandlerFunc.ServeHTTP(0xc420bb8600, 0x1b8e560, 0xc420d72c30, 0xc420970870)
	/usr/local/go/src/net/http/server.go:1726 +0x44
github.com/vmware/vic/vendor/github.com/go-openapi/runtime/middleware.Spec.func1(0x1b8e560, 0xc420d72c30, 0xc420970870)
	/home/hmahmood/go/src/github.com/vmware/vic/vendor/github.com/go-openapi/runtime/middleware/spec.go:45 +0x8b
net/http.HandlerFunc.ServeHTTP(0xc420bb8680, 0x1b8e560, 0xc420d72c30, 0xc420970870)
	/usr/local/go/src/net/http/server.go:1726 +0x44
net/http.serverHandler.ServeHTTP(0xc420be8800, 0x1b8e560, 0xc420d72c30, 0xc420970870)
	/usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc420be8d00, 0x1b8f0e0, 0xc420bb8cc0)
	/usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d
```

**Comment by chengwang86** [comment]
@hmahmood I have tried the above steps on regular docker, and it outputs the following error msg:
```
Error response from daemon: network networkName not found
Error: failed to start containers: containerID
```

On both vic and regular docker, when I re-create the network and then start the container, both work as expected.

So is it just a matter of printing an appropriate error msg instead of throwing panic?

**Comment by hmahmood** [comment]
Yes; we need to get rid of the panic and return an error.
