### ISSUE TITLE
Repeated portlayer panics during datastore operations

### ISSUE THREAD

**Issue by jzt** [vmware/vic#4191]
**VIC version:**

0.8.0

**Deployment details:**

What was the vic-machine create command used to deploy the VCH?

```
vic-machine-linux create --no-tlsverify --target 'customer-host/Cluster Test' --user 'root' --password 'password' --name VCHtest-customer --compute-resource customer-Test --image-store datastore/VCHtest-customer --bridge-network dvPortGroup-internal --force --public-network customer-network --client-network customer-network --management-network customer-network --volume-store datastore/VCHtest-customer:default
```

**Steps to reproduce:**

`docker -H 10.12.133.16:2376 --tls pull debian`

**Actual behavior:**
port-layer.log
```
2017/02/03 18:39:57 http: panic serving <host>: runtime error: invalid memory address or nil pointer dereference
goroutine 65867 [running]:
net/http.(*conn).serve.func1(0xc4211a6000)
    /usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0xec2640, 0xc420010050)
    /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/vmware/vic/vendor/github.com/vmware/govmomi/task.(*taskCallback).fn(0xc420b1ef60, 0x0, 0x0, 0x0, 0xc420b1f380)
    /drone/src/github.com/vmware/vic/vendor/github.com/vmware/govmomi/task/wait.go:74 +0x29f
github.com/vmware/vic/vendor/github.com/vmware/govmomi/task.(*taskCallback).(github.com/vmware/vic/vendor/github.com/vmware/govmomi/task.fn)-fm(0x0, 0x0, 0x0, 0x0)
    /drone/src/github.com/vmware/vic/vendor/github.com/vmware/govmomi/task/wait.go:121 +0x48
github.com/vmware/vic/vendor/github.com/vmware/govmomi/property.Wait.func1(0xc4207a38f8, 0x4, 0xc4207a3910, 0xa, 0x0, 0x0, 0x0, 0x0)
    /drone/src/github.com/vmware/vic/vendor/github.com/vmware/govmomi/property/wait.go:69 +0x43
github.com/vmware/vic/vendor/github.com/vmware/govmomi/property.waitLoop(0x1abede0, 0xc420010458, 0xc420b66a80, 0xc420c292b0, 0x0, 0x0)
    /drone/src/github.com/vmware/vic/vendor/github.com/vmware/govmomi/property/wait.go:142 +0x1e5
github.com/vmware/vic/vendor/github.com/vmware/govmomi/property.Wait(0x1abede0, 0xc420010458, 0xc420c29420, 0xc4207a2d40, 0x4, 0xc4207a2d60, 0xa, 0xc4207a2db0, 0x1, 0x1, ...)
    /drone/src/github.com/vmware/vic/vendor/github.com/vmware/govmomi/property/wait.go:70 +0x30a
github.com/vmware/vic/vendor/github.com/vmware/govmomi/task.Wait(0x1abede0, 0xc420010458, 0xc4207a2d40, 0x4, 0xc4207a2d60, 0xa, 0xc420c29420, 0x0, 0x0, 0x0, ...)
    /drone/src/github.com/vmware/vic/vendor/github.com/vmware/govmomi/task/wait.go:121 +0x152
github.com/vmware/vic/vendor/github.com/vmware/govmomi/object.(*Task).WaitForResult(0xc42061e580, 0x1abede0, 0xc420010458, 0x0, 0x0, 0x0, 0x1, 0xc4208235f0)
    /drone/src/github.com/vmware/vic/vendor/github.com/vmware/govmomi/object/task.go:52 +0x135
github.com/vmware/vic/pkg/vsphere/tasks.WaitForResult(0x1abede0, 0xc420010458, 0xc420c296a0, 0xc420c29640, 0x2, 0x2)
    /drone/src/github.com/vmware/vic/pkg/vsphere/tasks/waiter.go:67 +0x2ca
github.com/vmware/vic/pkg/vsphere/tasks.Wait(0x1abede0, 0xc420010458, 0xc420c296a0, 0x2, 0x2)
    /drone/src/github.com/vmware/vic/pkg/vsphere/tasks/waiter.go:49 +0x3f
github.com/vmware/vic/pkg/vsphere/datastore.(*Helper).Mv(0xc420112900, 0x1abede0, 0xc420010458, 0xc42085aec0, 0xd, 0xc42085ae70, 0x9, 0x0, 0x0)
    /drone/src/github.com/vmware/vic/pkg/vsphere/datastore/datastore.go:239 +0x317
github.com/vmware/vic/pkg/kvstore.(*dsBackend).Save(0xc42041e668, 0x1abede0, 0xc420010458, 0x1aae6e0, 0xc420c13740, 0xc42085ae70, 0x9, 0xc42080b4e8, 0x100000000)
    /drone/src/github.com/vmware/vic/pkg/kvstore/backend.go:51 +0x191
github.com/vmware/vic/pkg/kvstore.(*kv).save(0xc42080b4c0, 0x1abede0, 0xc420010458, 0xc420c298d8, 0x218fa)
    /drone/src/github.com/vmware/vic/pkg/kvstore/kvstore.go:211 +0x14e
github.com/vmware/vic/pkg/kvstore.(*kv).Put(0xc42080b4c0, 0x1abede0, 0xc420010458, 0xc42085ac40, 0xd, 0xc420c5e000, 0x218fa, 0x22000, 0x0, 0x0)
    /drone/src/github.com/vmware/vic/pkg/kvstore/kvstore.go:131 +0x1ae
github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*KvHandlersImpl).PutValueHandler(0xc420445470, 0xc420b18b40, 0xc420ac6488, 0xd, 0xc42085abf0, 0x0, 0x0)
    /drone/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers/kv_handlers.go:74 +0x136
github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*KvHandlersImpl).PutValueHandler-fm(0xc420b18b40, 0xc420ac6488, 0xd, 0xc42085abf0, 0x30003c420c29a01, 0xc420ac6560)
```

```
2017/01/13 19:48:21 http: panic serving <host>: runtime error: invalid memory address or nil pointer dereference
goroutine 724 [running]:
net/http.(*conn).serve.func1(0xc420b3cd80)
	/usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0xec2640, 0xc420010050)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/vmware/vic/vendor/github.com/vmware/govmomi/task.(*taskCallback).fn(0xc420746240, 0x0, 0x0, 0x0, 0xc420746ae0)
	/drone/src/github.com/vmware/vic/vendor/github.com/vmware/govmomi/task/wait.go:74 +0x29f
github.com/vmware/vic/vendor/github.com/vmware/govmomi/task.(*taskCallback).(github.com/vmware/vic/vendor/github.com/vmware/govmomi/task.fn)-fm(0x0, 0x0, 0x0, 0x0)
	/drone/src/github.com/vmware/vic/vendor/github.com/vmware/govmomi/task/wait.go:121 +0x48
github.com/vmware/vic/vendor/github.com/vmware/govmomi/property.Wait.func1(0xc4207d3678, 0x4, 0xc4207d3690, 0xa, 0x0, 0x0, 0x0, 0x0)
	/drone/src/github.com/vmware/vic/vendor/github.com/vmware/govmomi/property/wait.go:69 +0x43
github.com/vmware/vic/vendor/github.com/vmware/govmomi/property.waitLoop(0x1ac0520, 0xc4205fd400, 0xc420366300, 0xc420aaee68, 0x0, 0x0)
	/drone/src/github.com/vmware/vic/vendor/github.com/vmware/govmomi/property/wait.go:142 +0x1e5
github.com/vmware/vic/vendor/github.com/vmware/govmomi/property.Wait(0x1ac0520, 0xc4205fd400, 0xc420aaefd8, 0xc4207d29c0, 0x4, 0xc4207d29e0, 0xa, 0xc4207d2a50, 0x1, 0x1, ...)
	/drone/src/github.com/vmware/vic/vendor/github.com/vmware/govmomi/property/wait.go:70 +0x30a
github.com/vmware/vic/vendor/github.com/vmware/govmomi/task.Wait(0x1ac0520, 0xc4205fd400, 0xc4207d29c0, 0x4, 0xc4207d29e0, 0xa, 0xc420aaefd8, 0x0, 0x0, 0x0, ...)
	/drone/src/github.com/vmware/vic/vendor/github.com/vmware/govmomi/task/wait.go:121 +0x152
github.com/vmware/vic/vendor/github.com/vmware/govmomi/object.(*Task).WaitForResult(0xc4205ccdc0, 0x1ac0520, 0xc4205fd400, 0x0, 0x0, 0x0, 0x1, 0xc420823f50)
	/drone/src/github.com/vmware/vic/vendor/github.com/vmware/govmomi/object/task.go:52 +0x135
github.com/vmware/vic/pkg/vsphere/tasks.WaitForResult(0x1ac0520, 0xc4205fd400, 0xc420aaf258, 0xc420aaf1f8, 0x2, 0x2)
	/drone/src/github.com/vmware/vic/pkg/vsphere/tasks/waiter.go:67 +0x2ca
github.com/vmware/vic/pkg/vsphere/tasks.Wait(0x1ac0520, 0xc4205fd400, 0xc420aaf258, 0x2, 0x2)
	/drone/src/github.com/vmware/vic/pkg/vsphere/tasks/waiter.go:49 +0x3f
github.com/vmware/vic/pkg/vsphere/datastore.(*Helper).Mv(0xc420297d10, 0x1ac0520, 0xc4205fd400, 0xc4205fd240, 0x32, 0xc4203a1b30, 0x2e, 0x0, 0x0)
	/drone/src/github.com/vmware/vic/pkg/vsphere/datastore/datastore.go:239 +0x317
github.com/vmware/vic/lib/portlayer/storage/vsphere.(*parentM).Save(0xc4203a1ad0, 0x1abee60, 0xc4208b11a0, 0xc420b32240, 0x1, 0x1, 0xc420832e10, 0x6, 0x0, 0x0)
	/drone/src/github.com/vmware/vic/lib/portlayer/storage/vsphere/parent.go:110 +0x4e3
github.com/vmware/vic/lib/portlayer/storage/vsphere.(*ImageStore).WriteImage(0xc4202d0200, 0x1abee60, 0xc4208b11a0, 0xc420b32240, 0x1, 0x1, 0xc420832e10, 0x6, 0xc4208b1290, 0xc420b3923c, ...)
	/drone/src/github.com/vmware/vic/lib/portlayer/storage/vsphere/image.go:249 +0x16f
github.com/vmware/vic/lib/portlayer/storage.(*NameLookupCache).WriteImage(0xc4202d0240, 0x1abee60, 0xc4208b11a0, 0xc420b32240, 0x1, 0x1, 0xc420832e10, 0x6, 0xc420aaf7c8, 0xc420b3923c, ...)
	/drone/src/github.com/vmware/vic/lib/portlayer/storage/image_cache.go:218 +0x1f3
github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*StorageHandlersImpl).WriteImage(0xc420445450, 0xc4200d45a0, 0x1abc0e0, 0xc420b32100, 0xc420b3923c, 0x40, 0xc420832d60, 0xc420832d70, 0xc420b3943e, 0x40, ...)
	/drone/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers/storage_handlers.go:277 +0x3dc
github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*StorageHandlersImpl).WriteImage-fm(0xc4200d45a0, 0x1abc0e0, 0xc420b32100, 0xc420b3923c, 0x40, 0xc420832d60, 0xc420832d70, 0xc420b3943e, 0x40, 0xc420b3920e, ...)
	/drone/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers/storage_handlers.go:107 +0x65
github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/storage.WriteImageHandlerFunc.Handle(0xc42085b610, 0xc4200d45a0, 0x1abc0e0, 0xc420b32100, 0xc420b3923c, 0x40, 0xc420832d60, 0xc420832d70, 0xc420b3943e, 0x40, ...)
	/drone/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/storage/write_image.go:17 +0x59
github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/storage.(*WriteImage).ServeHTTP(0xc4208432c0, 0x1abe220, 0xc420645790, 0xc4200d45a0)
	/drone/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/storage/write_image.go:51 +0x276
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.newOperationExecutor.func1(0x1abe220, 0xc420645790, 0xc4200d45a0)
	/drone/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/operation.go:23 +0x69
net/http.HandlerFunc.ServeHTTP(0xc42085bc30, 0x1abe220, 0xc420645790, 0xc4200d45a0)
	/usr/local/go/src/net/http/server.go:1726 +0x44
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.newRouter.func1(0x1abe220, 0xc420645790, 0xc4200d45a0)
	/drone/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/router.go:78 +0x555
net/http.HandlerFunc.ServeHTTP(0xc4205cd700, 0x1abe220, 0xc420645790, 0xc4200d45a0)
	/usr/local/go/src/net/http/server.go:1726 +0x44
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.specMiddleware.func1(0x1abe220, 0xc420645790, 0xc4200d45a0)
	/drone/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/spec.go:36 +0x7b
net/http.HandlerFunc.ServeHTTP(0xc42050ebe0, 0x1abe220, 0xc420645790, 0xc4200d45a0)
	/usr/local/go/src/net/http/server.go:1726 +0x44
net/http.serverHandler.ServeHTTP(0xc42024ee00, 0x1abe220, 0xc420645790, 0xc4200d45a0)
	/usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc420b3cd80, 0x1abeda0, 0xc420b2a840)
	/usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d
```
**Expected behavior:**

Image is pulled/extracted normally.

Bugzilla link:

https://bugzilla.eng.vmware.com/show_bug.cgi?id=1812324

**Comment by jzt** [comment]
Looking at the portlayer logs, I see repeated panics like these during what appear to be operations on the datastore, usually seen when moving `parentMap.tmp` to `parentMap`, or when attempting to put values into the persisted key/value store.

**Comment by mhagen-vmware** [comment]
Please estimate work and move to backlog when ready.

**Comment by jzt** [comment]
Closing as this issue was in reference to https://github.com/vmware/vic/issues/3868 which was opened by the customer outside the bugzilla discussion unbeknownst to myself and the GSS engineer assigned to the issue.
