### ISSUE TITLE
Unit test failure in tether: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#5240]
https://ci.vcna.io/vmware/vic/10887

```
panic: runtime error: invalid memory address or nil pointer dereference
1034s
6926
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x85fb8e]
1034s
6928
goroutine 1268 [running]:
1034s
6929
github.com/vmware/vic/cmd/tether.backchannel.func1(0xdbf340, 0xc420284440, 0x0, 0x0)
1034s
6930
	github.com/vmware/vic/cmd/tether/_test/_obj_test/attach.go:283 +0x7e
1034s
6931
created by github.com/vmware/vic/cmd/tether.backchannel
1034s
6932
	github.com/vmware/vic/cmd/tether/_test/_obj_test/attach.go:285 +0x109
1034s
6933
FAIL	github.com/vmware/vic/cmd/tether	14.478s
1034s
6934
make: *** [test-job-github.com/vmware/vic/cmd] Error 1
1034s
6935
make: *** Waiting for unfinished jobs....
1034s
6936
Makefile:261: recipe for target 'test-job-github.com/vmware/vic/cmd' failed
```

**Comment by anchal-agrawal** [comment]
#4130 has some discussion on this bug.

**Comment by mhagen-vmware** [comment]
dupe of #4130
