### ISSUE TITLE
Nightly failures due to no available resources on Nimbus 

### ISSUE THREAD

**Issue by anchal-agrawal** [vmware/vic#5277]
From `output.xml` (attached):
```
2017-05-25 20:16:12 -0700: ********************************************************************************
*
* Nimbus currently has no available resources to run this workload.
* 
* Nimbus is running with context general, 44 pods (vCenters with ESX hosts) were
* contacted to see if they were running above or below the maximum configured
* load, but none of them had enough free resources to run this workload.
*
* You can try running in a different Nimbus context if there's one available to
* you (talk to coworkers or ask your manager). Otherwise, the only solution at
* this time is to wait and try again.
*
* Nimbus resources are finite. Please try to avoid leaving VMs running in Nimbus
* that don't need to be powered on. Please encourage your coworkers to try to
* clean up their VMs and not waste resources.
*
* For any additional questions/concerns, please contact the nimbus@vmware.com
* mailing list. Please do not file any bug for this.
*
********************************************************************************
2017-05-25 20:16:12 -0700: No pod returned from Load Balancer for context: general. Nimbus might be out of infrastructure.
2017-05-25 20:16:12 -0700: Nimbus checker pipeline broken: No pod returned from load balancer. Extra info: HDRS returned no pod for context 'general'
2017-05-25 20:16:12 -0700: NimbusExceptionNoPod: No pod returned from load balancer. Extra info: HDRS returned no pod for context 'general'
2017-05-25 20:16:12 -0700: /mts/git/nimbus/lib/nimbus/loadbalancer/pod_selector.rb:213:in `select_pod'
2017-05-25 20:16:12 -0700: /mts/git/nimbus/lib/nimbus/admission_control/admission_control_loadbalancer.rb:51:in `select_pod'
2017-05-25 20:16:12 -0700: /mts/git/nimbus/lib/nimbus/admission_control/admission_control_loadbalancer.rb:8:in `do_check'
2017-05-25 20:16:12 -0700: /mts/git/nimbus/lib/nimbus/admission_control.rb:85:in `block in check'
2017-05-25 20:16:12 -0700: /mts/git/nimbus/lib/nimbus/admission_control.rb:79:in `each'
2017-05-25 20:16:12 -0700: /mts/git/nimbus/lib/nimbus/admission_control.rb:79:in `check'
2017-05-25 20:16:12 -0700: /mts/git/nimbus/lib/nimbus.rb:1232:in `initialize'
2017-05-25 20:16:12 -0700: /mts/git/nimbus/lib/nimbus/base_deploy.rb:881:in `new'
2017-05-25 20:16:12 -0700: /mts/git/nimbus/lib/nimbus/base_deploy.rb:881:in `init_deployer'
2017-05-25 20:16:12 -0700: /mts/git/nimbus/lib/nimbus/base_deploy.rb:927:in `_deploy'
2017-05-25 20:16:12 -0700: /mts/git/nimbus/lib/nimbus/base_deploy.rb:620:in `run'
2017-05-25 20:16:12 -0700: /mts/git/nimbus/lib/nimbus/base_deploy.rb:550:in `block in run_cli'
2017-05-25 20:16:12 -0700: /mts/git/nimbus-toolchain/lin64/ruby/2.2.0/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
2017-05-25 20:16:12 -0700: /mts/git/nimbus-toolchain/lin64/ruby/2.2.0/lib/ruby/2.2.0/timeout.rb:34:in `block in catch'
2017-05-25 20:16:12 -0700: /mts/git/nimbus-toolchain/lin64/ruby/2.2.0/lib/ruby/2.2.0/timeout.rb:34:in `catch'
2017-05-25 20:16:12 -0700: /mts/git/nimbus-toolchain/lin64/ruby/2.2.0/lib/ruby/2.2.0/timeout.rb:34:in `catch'
2017-05-25 20:16:12 -0700: /mts/git/nimbus-toolchain/lin64/ruby/2.2.0/lib/ruby/2.2.0/timeout.rb:104:in `timeout'
2017-05-25 20:16:12 -0700: /mts/git/nimbus-toolchain/lin64/ruby/2.2.0/lib/ruby/2.2.0/timeout.rb:125:in `timeout'
2017-05-25 20:16:12 -0700: /mts/git/nimbus/lib/nimbus/base_deploy.rb:550:in `run_cli'
2017-05-25 20:16:12 -0700: /mts/git/bin/../nimbus/lib/nimbus/deploys/nfs/nfs_deploy.rb:209:in `<main>'
2017-05-25 20:16:12 -0700: Writing deployment results...
2017-05-25 20:16:12 -0700: Terminating VIM connection ...
2017-05-25 20:16:12 -0700: Exception: NimbusExceptionNoPod: No pod returned from load balancer. Extra info: HDRS returned no pod for context 'general'' does not contain 'To manage this VM use'
```

Seen while deploying NFS, vCenter and ESX servers in:

vSphere 6.5:
[5-4-High-Availability.zip](https://github.com/vmware/vic/files/1032991/5-4-High-Availability.zip)

vSphere 6.0:
[5-1-Distributed-Switch.zip](https://github.com/vmware/vic/files/1032994/5-1-Distributed-Switch.zip)
[5-2-Cluster.zip](https://github.com/vmware/vic/files/1032995/5-2-Cluster.zip)

**Comment by anchal-agrawal** [comment]
vSphere 6.0:
[5-13-Invalid-ESXi-Install.zip](https://github.com/vmware/vic/files/1053366/5-13-Invalid-ESXi-Install.zip)
[13-1-vMotion-VCH-Appliance.zip](https://github.com/vmware/vic/files/1053365/13-1-vMotion-VCH-Appliance.zip)
[13-2-vMotion-Container.zip](https://github.com/vmware/vic/files/1053367/13-2-vMotion-Container.zip)

**Comment by anchal-agrawal** [comment]
This is a Nimbus-related issue. Closing due to age.
