### ISSUE TITLE
VCH Panic: close of closed channel

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic#5290]
On a VCH with about 600+  containers, docker-personality.log-20170524-1495643563 says:

May 24 2017 16:28:27.214Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*SystemProxy).VCHInfo:109] [163.407585ms] VCHInfo
May 24 2017 16:28:27.214Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*ContainerProxy).StreamContainerStats:527] 674e2876001f674d23214f96b105960ab5ff7d7958cca70e71b459f20bdaa940
May 24 2017 16:28:27.215Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*ContainerProxy).StreamContainerStats:527] [684.045µs] 674e2876001f674d22
3214f96b105960ab5ff7d7958cca70e71b459f20bdaa940
May 24 2017 16:28:27.216Z ERROR error while streaming container (674e2876001f674d23214f96b105960ab5ff7d7958cca70e71b459f20bdaa940) stats: Server error from portlayer: Unknown error from the interaction port layer: Get http://127.0.0.1:2377/containers/674e2876001f674d23214f96b105960ab5ff7d7958cca70e71b459f20bdaa940/stats?stream=false: dial tcp 127.0.0.1:2377: socket: too many open files
May 24 2017 16:28:27.216Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerStats:1343] [165.397603ms] 674e2876001f674d23214f96b105960ab5ff7d7958cca70e71b459f20bdaa940
panic: close of closed channel

goroutine 829517 [running]:
github.com/vmware/vic/lib/apiservers/engine/backends/convert.(*ContainerStats).Listen.func1(0xc43d500510, 0xc43d73b4a0, 0xc43d73b440, 0xc43cf3b6c0, 0xc43d73b8c0)
        /drone/src/github.com/vmware/vic/lib/apiservers/engine/backends/convert/stats.go:114 +0xe3
created by github.com/vmware/vic/lib/apiservers/engine/backends/convert.(*ContainerStats).Listen
        /drone/src/github.com/vmware/vic/lib/apiservers/engine/backends/convert/stats.go:132 +0x2c4

goroutine 1 [chan receive, 7506 minutes]:
main.main()
        /drone/src/github.com/vmware/vic/cmd/docker/main.go:119 +0x2b3

goroutine 17 [syscall, 7506 minutes, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 18 [IO wait, 7506 minutes]:
net.runtime_pollWait(0x7faff15e9f28, 0x72, 0x2fe6600)
        /usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc42046e148, 0x72, 0x2fd3e50, 0xc420570540)
        /usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc42046e148, 0xffffffffffffffff, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).accept(0xc42046e0e0, 0x0, 0x2fe14c0, 0xc420570540)
        /usr/local/go/src/net/fd_unix.go:430 +0x1e5
net.(*TCPListener).accept(0xc42000e008, 0xc4202165d0, 0xc42002fe48, 0x562efd)
        /usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
...
Log bundle can be downloaded from :  https://10.197.37.187:2378/ - administrator@vsphere.local/Admin!23
rootpw: Admin!23

**Comment by lgayatri** [comment]
[Panic.zip](https://github.com/vmware/vic/files/1039288/Panic.zip)

Required log files attached.

**Comment by anchal-agrawal** [comment]
@lgayatri I see this is `docker stats` related - were you running `stats` on just one container or multiple?

**Comment by lgayatri** [comment]
@anchal-agrawal I am not running stats explicitly. This VCH is managed by Admiral so it could be due to that.

**Comment by mdubya66** [comment]
Marking high as was found in system test. @mhagen-vmware please triage if test blocker

**Comment by cgtexmex** [comment]
#5699 will add tracing to the stats flow that will make these types of issues easier to troubleshoot...I am concerned about the number of container VMs and the current use of `performanceManager`, but I need to do some additional investigation there.

**Comment by cgtexmex** [comment]
The vSphere developers guide suggests that a query to `performanceManager` should generally contain 10 - 50 objects.  The current vic implementation will create a single query for _ALL_ of the containerVMs managed by the VCH, so in this case 600.  That size query would most likely result in a considerable slow down (or failure) of stats collection.  I think the first plan of attack should be to fix vic's use of the `performanceManager` to be in line with the suggested guidelines.

**Comment by cgtexmex** [comment]
@lgayatri what version of Admiral was being used during this test and have you seen it happen again?  Do we have a complete set of logs?

**Comment by lgayatri** [comment]
@cgtexmex due to product PR I am blocked on testing, will provide an update after the fix.

**Comment by cgtexmex** [comment]
I have attempted to recreate the error by reducing the number of open files allowed on the portLayer to 25 -- I am able to recreate the open file limit error, but not the panic, etc shown in the attached logs.

I'm moving this to the backlog and reducing the priority to medium.  If we see more occurrences then bump the priority back to `High`.
