### ISSUE TITLE
syslogd hook firing when not configured

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#5485]
Found as part of #5445

When running stress loads to recreate #5445 we occasionally get into a state where we're firing the syslogd hook, despite it not being configured.
Need to check what the defaults are - the panic from below was injected into the error paths in `log/syslog/writer.go:queueWrite`.
```
Jun 15 2017 18:22:41.075Z DEBUG HandshakeClient: Sending syn with pos 182
Jun 15 2017 18:22:41.075Z ERROR syn: write failed
panic: unexpected

goroutine 775 [running]:
github.com/vmware/vic/pkg/log/syslog.(*writer).queueWrite(0xc420068990, 0x3, 0x7ffe54d06f18, 0x11, 0xc4208a3bc0, 0x53, 0xc420b74af8, 0x40220e)
	/home/vagrant/vicsmb/src/github.com/vmware/vic/pkg/log/syslog/writer.go:165 +0x152
github.com/vmware/vic/pkg/log/syslog.(*writer).Err(0xc420068990, 0xc4208a3bc0, 0x53, 0x40a3be, 0xc420b74b77)
	/home/vagrant/vicsmb/src/github.com/vmware/vic/pkg/log/syslog/writer.go:130 +0x5a
github.com/vmware/vic/pkg/log/syslog.(*Hook).writeEntry(0xc4202f5c70, 0xc42082ea50, 0xc4204b6540, 0x1d08560)
	/home/vagrant/vicsmb/src/github.com/vmware/vic/pkg/log/syslog/hook.go:61 +0x9c
github.com/vmware/vic/pkg/log/syslog.(*Hook).Fire(0xc4202f5c70, 0xc42082ea50, 0xc420b74b77, 0xc4204b6580)
	/home/vagrant/vicsmb/src/github.com/vmware/vic/pkg/log/syslog/hook.go:45 +0x35
github.com/vmware/vic/vendor/github.com/Sirupsen/logrus.LevelHooks.Fire(0xc420010210, 0xc4047b3e02, 0xc42082ea50, 0x53, 0xc420b74c18)
	/home/vagrant/vicsmb/src/github.com/vmware/vic/vendor/github.com/Sirupsen/logrus/hooks.go:28 +0x8b
github.com/vmware/vic/vendor/github.com/Sirupsen/logrus.Entry.log(0xc42004a0a0, 0xc421024c90, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420bfcd02, ...)
	/home/vagrant/vicsmb/src/github.com/vmware/vic/vendor/github.com/Sirupsen/logrus/entry.go:96 +0x109
github.com/vmware/vic/vendor/github.com/Sirupsen/logrus.(*Entry).Error(0xc4209a2af0, 0xc420b74d38, 0x1, 0x1)
	/home/vagrant/vicsmb/src/github.com/vmware/vic/vendor/github.com/Sirupsen/logrus/entry.go:156 +0xaa
github.com/vmware/vic/vendor/github.com/Sirupsen/logrus.(*Entry).Errorf(0xc4209a2af0, 0x12a8286, 0x13, 0xc420b74ec8, 0x1, 0x1)
	/home/vagrant/vicsmb/src/github.com/vmware/vic/vendor/github.com/Sirupsen/logrus/entry.go:204 +0xf9
github.com/vmware/vic/vendor/github.com/Sirupsen/logrus.(*Logger).Errorf(0xc42004a0a0, 0x12a8286, 0x13, 0xc420b74ec8, 0x1, 0x1)
	/home/vagrant/vicsmb/src/github.com/vmware/vic/vendor/github.com/Sirupsen/logrus/logger.go:155 +0x87
github.com/vmware/vic/vendor/github.com/Sirupsen/logrus.Errorf(0x12a8286, 0x13, 0xc420b74ec8, 0x1, 0x1)
	/home/vagrant/vicsmb/src/github.com/vmware/vic/vendor/github.com/Sirupsen/logrus/exported.go:142 +0x5f
github.com/vmware/vic/lib/portlayer/attach/communication.(*Connector).processIncoming(0xc420c06180, 0x1d266a0, 0xc420444498)
	/home/vagrant/vicsmb/src/github.com/vmware/vic/lib/portlayer/attach/communication/connector.go:301 +0x339
created by github.com/vmware/vic/lib/portlayer/attach/communication.(*Connector).serve
	/home/vagrant/vicsmb/src/github.com/vmware/vic/lib/portlayer/attach/communication/connector.go:256 +0x227
```

I think the opening portion of the portlayer log is sufficient as it shows _successfully_ connecting to an unconfigured syslog server:
```
time="2017-06-15T18:19:41Z" level=info msg="{Formatter:0xc4202f5b20 Level:debug Syslog:0xc420805540}" 
Jun 15 2017 18:19:41.540Z DEBUG log cfg: {Formatter:0xc4202f5b20 Level:debug Syslog:0xc420805540}
Jun 15 2017 18:19:41.540Z DEBUG syslog cfg: {Network: RAddr: Tag: Priority:30}
Jun 15 2017 18:19:41.541Z DEBUG secret key decoded from guestinfo.ovfEnv
Jun 15 2017 18:19:41.541Z DEBUG GuestInfoSource: key: guestinfo.vice./init/common/ExecutionEnvironment, value: "", error: %!s(<nil>)
Jun 15 2017 18:19:41.541Z DEBUG GuestInfoSource: key: guestinfo.vice./init/common/id, value: "VirtualMachine:1550", error: %!s(<nil>)
Jun 15 2017 18:19:41.542Z DEBUG GuestInfoSource: key: init/common/name, value: "", error: key not found
Jun 15 2017 18:19:41.544Z DEBUG GuestInfoSource: key: init/common/notes, value: "", error: key not found
Jun 15 2017 18:19:41.545Z DEBUG GuestInfoSource: key: guestinfo.vice..init.createtime, value: "0", error: %!s(<nil>)
Jun 15 2017 18:19:41.545Z DEBUG GuestInfoSource: key: guestinfo.vice./init/diagnostics/debug, value: "3", error: %!s(<nil>)
Jun 15 2017 18:19:41.545Z DEBUG GuestInfoSource: key: guestinfo.vice..init.diagnostics.resurrections, value: "0", error: %!s(<nil>)
Jun 15 2017 18:19:41.545Z DEBUG GuestInfoSource: key: guestinfo.vice..init.diagnostics.exitlogs, value: "", error: key not found
Jun 15 2017 18:19:41.546Z DEBUG GuestInfoSource: key: guestinfo.vice./init/diagnostics/syslog/Network, value: "", error: key not found
Jun 15 2017 18:19:41.546Z DEBUG GuestInfoSource: key: guestinfo.vice./init/diagnostics/syslog/RAddr, value: "", error: key not found
Jun 15 2017 18:19:41.546Z DEBUG GuestInfoSource: key: guestinfo.vice./init/sessions, value: "docker-personality|port-layer|vicadmin", error: %!s(<nil>)
Jun 15 2017 18:19:41.546Z DEBUG GuestInfoSource: key: guestinfo.vice./init/sessions|docker-personality/common/ExecutionEnvironment, value: "", error: %!s(<nil>)
Jun 15 2017 18:19:41.547Z DEBUG GuestInfoSource: key: guestinfo.vice./init/sessions|docker-personality/common/id, value: "docker-personality", error: %!s(<nil>)
Jun 15 2017 18:19:41.547Z DEBUG GuestInfoSource: key: guestinfo.vice./init/sessions|docker-personality/common/name, value: "docker-personality", error: %!s(<nil>)
Jun 15 2017 18:19:41.547Z DEBUG GuestInfoSource: key: init/sessions|docker-personality/common/notes, value: "", error: key not found
Jun 15 2017 18:19:41.547Z DEBUG GuestInfoSource: key: guestinfo.vice..init.sessions|docker-personality.detail.createtime, value: "0", error: %!s(<nil>)
Jun 15 2017 18:19:41.548Z DEBUG GuestInfoSource: key: guestinfo.vice..init.sessions|docker-personality.detail.starttime, value: "0", error: %!s(<nil>)
Jun 15 2017 18:19:41.548Z DEBUG GuestInfoSource: key: guestinfo.vice..init.sessions|docker-personality.detail.stoptime, value: "0", error: %!s(<nil>)
Jun 15 2017 18:19:41.548Z DEBUG GuestInfoSource: key: guestinfo.vice./init/sessions|docker-personality/cmd/Path, value: "/sbin/docker-engine-server", error: %!s(<nil>)
Jun 15 2017 18:19:41.548Z DEBUG GuestInfoSource: key: guestinfo.vice./init/sessions|docker-personality/cmd/Args, value: "2", error: %!s(<nil>)
Jun 15 2017 18:19:41.549Z DEBUG GuestInfoSource: key: guestinfo.vice./init/sessions|docker-personality/cmd/Args~, value: "/sbin/docker-engine-server|-port=2376|-port-layer-port=2377", error: %!s(<nil>)
Jun 15 2017 18:19:41.549Z DEBUG GuestInfoSource: key: guestinfo.vice./init/sessions|docker-personality/cmd/Env, value: "1", error: %!s(<nil>)
Jun 15 2017 18:19:41.549Z DEBUG GuestInfoSource: key: guestinfo.vice./init/sessions|docker-personality/cmd/Env~, value: "PATH=/sbin|GOTRACEBACK=all", error: %!s(<nil>)
Jun 15 2017 18:19:41.549Z DEBUG GuestInfoSource: key: guestinfo.vice./init/sessions|docker-personality/cmd/Dir, value: "", error: %!s(<nil>)
Jun 15 2017 18:19:41.549Z DEBUG GuestInfoSource: key: guestinfo.vice./init/sessions|docker-personality/attach, value: "false", error: %!s(<nil>)
time="2017-06-15T18:19:41Z" level=info msg="successfully connected to syslog server" 
```

**Comment by mhagen-vmware** [comment]
closing based on PR #5507
