### ISSUE TITLE
nightly test on vsphere 6.5 failed to create a vsan cluster 

### ISSUE THREAD

**Issue by chengwang86** [vmware/vic#5537]
Seen in test 13-1-vMotion-VCH and 13-2-vMotion-container

[13-1-vMotion-VCH-Appliance.zip](https://github.com/vmware/vic/files/1089135/13-1-vMotion-VCH-Appliance.zip)
[13-2-vMotion-Container.zip](https://github.com/vmware/vic/files/1089136/13-2-vMotion-Container.zip)

```
2017-06-20 00:48:52 -0700: /tmp/nimbus-test-svc.victestuser/standalone-abd7cf759/testbeds/svc.victestuser-vic-vmotion.esx.0.serial.txt is still empty
2017-06-20 00:48:52 -0700: /tmp/nimbus-test-svc.victestuser/standalone-abd7cf759/testbeds/svc.victestuser-vic-vmotion.esx.1.serial.txt is still empty
2017-06-20 00:48:52 -0700: /tmp/nimbus-test-svc.victestuser/standalone-abd7cf759/testbeds/svc.victestuser-vic-vmotion.esx.3.serial.txt is still empty
2017-06-20 00:54:00 -0700: ESX deploy failed with exit code: 1, out files:
======begin ESX deploy log: /tmp/nimbus-test-svc.victestuser/standalone-abd7cf759/testbeds/svc.victestuser-vic-vmotion.esx.1-nimbus-esxdeploy.txt=======
2017-06-20 00:34:00 -0700: Deploying build ob-4564106 to /mts/home5/svc.victestuser/public_html/pxe/ob-4564106...
2017-06-20 00:34:00 -0700: Checking if no body else is doing the job for us...may wait for 20 minutes
2017-06-20 00:54:00 -0700: Lock check finished, false
2017-06-20 00:54:00 -0700: Serial log /tmp/nimbus-test-svc.victestuser/standalone-abd7cf759/testbeds/svc.victestuser-vic-vmotion.esx.1.serialDump.json does not exist
2017-06-20 00:54:00 -0700: Error in parsing serial log JSON dump = Errno::ENOENT:No such file or directory @ rb_sysopen - /tmp/nimbus-test-svc.victestuser/standalone-abd7cf759/testbeds/svc.victestuser-vic-vmotion.esx.1.serialDump.json
2017-06-20 00:54:00 -0700: RbVmomiUtils::PxeDeployError: pxe-deploy failed : Unable to acquire lock after 20 minutes, aborting.
2017-06-20 00:54:00 -0700: /mts/git/rbvmomi-utils/lib/rbvmomi-utils/pxeconfig.rb:309:in `block in _flock'
2017-06-20 00:54:00 -0700: /mts/git/rbvmomi-utils/lib/rbvmomi-utils/pxeconfig.rb:297:in `open'
2017-06-20 00:54:00 -0700: /mts/git/rbvmomi-utils/lib/rbvmomi-utils/pxeconfig.rb:297:in `_flock'
2017-06-20 00:54:00 -0700: /mts/git/rbvmomi-utils/lib/rbvmomi-utils/pxeconfig.rb:553:in `deployBuildViaPxe'
2017-06-20 00:54:00 -0700: /mts/git/bin/../nimbus/lib/nimbus/deploys/esx/esx_deploy.rb:533:in `prepare_for_build'
2017-06-20 00:54:00 -0700: /mts/git/nimbus/lib/nimbus/base_deploy.rb:925:in `_deploy'
2017-06-20 00:54:00 -0700: /mts/git/nimbus/lib/nimbus/base_deploy.rb:620:in `run'
2017-06-20 00:54:00 -0700: /mts/git/nimbus/lib/nimbus/base_deploy.rb:550:in `block in run_cli'
2017-06-20 00:54:00 -0700: /mts/git/nimbus-toolchain/lin64/ruby/2.2.0/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
2017-06-20 00:54:00 -0700: /mts/git/nimbus-toolchain/lin64/ruby/2.2.0/lib/ruby/2.2.0/timeout.rb:34:in `block in catch'
2017-06-20 00:54:00 -0700: /mts/git/nimbus-toolchain/lin64/ruby/2.2.0/lib/ruby/2.2.0/timeout.rb:34:in `catch'
2017-06-20 00:54:00 -0700: /mts/git/nimbus-toolchain/lin64/ruby/2.2.0/lib/ruby/2.2.0/timeout.rb:34:in `catch'
2017-06-20 00:54:00 -0700: /mts/git/nimbus-toolchain/lin64/ruby/2.2.0/lib/ruby/2.2.0/timeout.rb:104:in `timeout'
2017-06-20 00:54:00 -0700: /mts/git/nimbus-toolchain/lin64/ruby/2.2.0/lib/ruby/2.2.0/timeout.rb:125:in `timeout'
2017-06-20 00:54:00 -0700: /mts/git/nimbus/lib/nimbus/base_deploy.rb:550:in `run_cli'
2017-06-20 00:54:00 -0700: /mts/git/bin/../nimbus/lib/nimbus/deploys/esx/esx_deploy.rb:1614:in `<main>'
2017-06-20 00:54:00 -0700: Writing deployment results...
2017-06-20 00:54:00 -0700: Terminating VIM connection ...
2017-06-20 00:54:00 -0700: Exception: RbVmomiUtils::PxeDeployError: pxe-deploy failed : Unable to acquire lock after 20 minutes, aborting.

=======end ESX deploy log: /tmp/nimbus-test-svc.victestuser/standalone-abd7cf759/testbeds/svc.victestuser-vic-vmotion.esx.1-nimbus-esxdeploy.txt========
======begin ESX error log: /tmp/nimbus-test-svc.victestuser/standalone-abd7cf759/testbeds/svc.victestuser-vic-vmotion.esx.1-nimbus-esxdeploy_err.txt=======

=======end ESX error log: /tmp/nimbus-test-svc.victestuser/standalone-abd7cf759/testbeds/svc.victestuser-vic-vmotion.esx.1-nimbus-esxdeploy_err.txt========
2017-06-20 00:54:00 -0700: ESX VM (svc.victestuser-vic-vmotion.esx.1) box done.
2017-06-20 00:54:00 -0700: Dumping failure information into /tmp/nimbus-test-svc.victestuser/standalone-abd7cf759/failure_dump.json
2017-06-20 00:54:00 -0700: svc.victestuser-vic-vmotion.esx.1 creation failed, abort other running deployments.
2017-06-20 00:54:00 -0700: Since aborted VMs' status are uncertain, please ignore these VMs' errors in following procedures
2017-06-20 00:54:00 -0700: VM: esx.0 deployment is aborted
2017-06-20 00:54:00 -0700: VM: esx.2 deployment is aborted
2017-06-20 00:54:00 -0700: VM: esx.3 deployment is aborted
2017-06-20 00:54:00 -0700: VM: svc.victestuser-vic-vmotion.vcva-ob-4602587 deployment is aborted
2017-06-20 00:54:01 -0700: Skipping fetching log bundles by users request
2017-06-20 00:54:01 -0700: Testbed vic-vmotion failed ...
```

**Comment by corrieb** [comment]
Same problem occured on June 26th, but for a different reason. It failed to set up the testbed and reported that it couldn't get an IP address. Likely due to a provisioning failure.

```
 Got an exception while refreshing the ip: NimbusExceptionNoIp: Failed to get IP 2017-06-26 01:29:25 -0700: /mts/git/nimbus/lib/nimbus_ip_listener.rb:279:in `_raise_if_no_ip' 2017-06-26 01:29:25 -0700: /mts/git/nimbus/lib/nimbus_ip_listener.rb:217:in `start' 2017-06-26 01:29:25 -0700: /mts/git/nimbus/lib/nimbus_ip_listener.rb:470:in `wait_for_ip' 2017-06-26 01:29:25 -0700: /mts/git/nimbus/lib/nimbus_ip_listener.rb:527:in `wait_for_vm_tools_ip' 2017-06-26 01:29:25 -0700: /mts/git/bin/../nimbus/lib/nimbus/deploys/vc/vcva_deploy.rb:867:in `_retry_for_ip' 2017-06-26 01:29:25 -0700: /mts/git/bin/../nimbus/lib/nimbus/deploys/vc/vcva_deploy.rb:1805:in `rescue in block in phase_configure_base_vm' 2017-06-26 01:29:25 -0700: /mts/git/bin/../nimbus/lib/nimbus/deploys/vc/vcva_deploy.rb:1789:in `block in phase_configure_base_vm' 2017-06-26 01:29:25 -0700: /mts/git/bin/../nimbus/lib/nimbus/deploys/vc/vcva_deploy.rb:914:in `_block_timer' 2017-06-26 01:29:25 -0700: /mts/git/bin/../nimbus/lib/nimbus/deploys/vc/vcva_deploy.rb:1783:in `phase_configure_base_vm' 2017-06-26 01:29:25 -0700: /mts/git/bin/../nimbus/lib/nimbus/deploys/vc/vcva_deploy.rb:591:in `block in _deploy' 2017-06-26 01:29:25 -0700: /mts/git/nimbus-toolchain/lin64/ruby/2.2.0/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout' 2017-06-26 01:29:25 -0700: /mts/git/nimbus-toolchain/lin64/ruby/2.2.0/lib/ruby/2.2.0/timeout.rb:34:in `block in catch' 2017-06-26 01:29:25 -0700: /mts/git/nimbus-toolchain/lin64/ruby/2.2.0/lib/ruby/2.2.0/timeout.rb:34:in `catch' 2017-06-26 01:29:25 -0700: /mts/git/nimbus-toolchain/lin64/ruby/2.2.0/lib/ruby/2.2.0/timeout.rb:34:in `catch' 2017-06-26 01:29:25 -0700: /mts/git/nimbus-toolchain/lin64/ruby/2.2.0/lib/ruby/2.2.0/timeout.rb:104:in `timeout' 2017-06-26 01:29:25 -0700: /mts/git/nimbus-toolchain/lin64/ruby/2.2.0/lib/ruby/2.2.0/timeout.rb:125:in `timeout' 2017-06-26 01:29:25 -0700: /mts/git/bin/../nimbus/lib/nimbus/deploys/vc/vcva_deploy.rb:590:in `_deploy' 2017-06-26 01:29:25 -0700: /mts/git/nimbus/lib/nimbus/base_deploy.rb:620:in `run' 2017-06-26 01:29:25 -0700: /mts/git/nimbus/lib/nimbus/base_deploy.rb:550:in `block in run_cli' 2017-06-26 01:29:25 -0700: /mts/git/nimbus-toolchain/lin64/ruby/2.2.0/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout' 2017-06-26 01:29:25 -0700: /mts/git/nimbus-toolchain/lin64/ruby/2.2.0/lib/ruby/2.2.0/timeout.rb:34:in `block in catch' 2017-06-26 01:29:25 -0700: /mts/git/nimbus-toolchain/lin64/ruby/2.2.0/lib/ruby/2.2.0/timeout.rb:34:in `catch' 2017-06-26 01:29:25 -0700: /mts/git/nimbus-toolchain/lin64/ruby/2.2.0/lib/ruby/2.2.0/timeout.rb:34:in `catch' 2017-06-26 01:29:25 -0700: /mts/git/nimbus-toolchain/lin64/ruby/2.2.0/lib/ruby/2.2.0/timeout.rb:104:in `timeout' 2017-06-26 01:29:25 -0700: /mts/git/nimbus-toolchain/lin64/ruby/2.2.0/lib/ruby/2.2.0/timeout.rb:125:in `timeout' 2017-06-26 01:29:25 -0700: /mts/git/nimbus/lib/nimbus/base_deploy.rb:550:in `run_cli' 2017-06-26 01:29:25 -0700: /mts/git/bin/../nimbus/lib/nimbus/deploys/vc/vcva_deploy.rb:2436:in `<main>' 2017-06-26 01:29:25 -0700: Screenshot saved as /tmp/nimbus-test-svc.victestuser/standalone-1e236dc15/testbeds/svc.victestuser-vic-vmotion.vcva-ob-4602587-no-ip.png.
```
