### ISSUE TITLE
vic-ui build fails with "VicContainerViewComponent should render the data grid with properly formatted data"

### ISSUE THREAD

**Issue by willsherwood** [vmware/vic#5706]
Seen in https://ci.vcna.io/vmware/vic/12254. Marking this as high priority as it blocks PR builds until the build failure is resolved.

Partial Log:
```
[exec] HeadlessChrome 0.0.0 (Linux 0.0.0) VicContainerViewComponent should render the data grid with properly formatted data FAILED
[exec] 	TypeError: Cannot create property '__creationTrace__' on string '__zone_symbol__optimizedZoneEventTask'
[exec] 	    at Object.onScheduleTask (http://localhost:9876/_karma_webpack_/vendor.bundle.js:36231:38)
[exec] 	    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask (http://localhost:9876/_karma_webpack_/polyfills.bundle.js:6170:51)
[exec] 	    at Object.onScheduleTask (http://localhost:9876/_karma_webpack_/polyfills.bundle.js:6066:29)
[exec] 	    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask (http://localhost:9876/_karma_webpack_/polyfills.bundle.js:6170:51)
[exec] 	    at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleTask (http://localhost:9876/_karma_webpack_/polyfills.bundle.js:6001:43)
[exec] 	    at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleEventTask (http://localhost:9876/_karma_webpack_/polyfills.bundle.js:6027:25)
[exec] 	    at HTMLElement.addEventListener (http://localhost:9876/_karma_webpack_/polyfills.bundle.js:7327:29)
[exec] 	    at DomEventsPlugin.webpackJsonp.../../../platform-browser/@angular/platform-browser.es5.js.DomEventsPlugin.addEventListener (http://localhost:9876/_karma_webpack_/vendor.bundle.js:98142:17)
[exec] 	    at EventManager.webpackJsonp.../../../platform-browser/@angular/platform-browser.es5.js.EventManager.addEventListener (http://localhost:9876/_karma_webpack_/vendor.bundle.js:97480:23)
[exec] 	    at DefaultDomRenderer2.webpackJsonp.../../../platform-browser/@angular/platform-browser.es5.js.DefaultDomRenderer2.listen (http://localhost:9876/_karma_webpack_/vendor.bundle.js:98001:36)
[exec] 	Failed: Cannot read property 'componentInstance' of undefined
[exec] 	TypeError: Cannot read property 'componentInstance' of undefined
[exec] 	    at Object.<anonymous> (http://localhost:9876/_karma_webpack_/main.bundle.js:284:16)
[exec] 	    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/polyfills.bundle.js:6157:26)
[exec] 	    at AsyncTestZoneSpec.webpackJsonp.../../../../zone.js/dist/async-test.js.AsyncTestZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/vendor.bundle.js:35601:39)
[exec] 	    at ProxyZoneSpec.webpackJsonp.../../../../zone.js/dist/proxy.js.ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/vendor.bundle.js:36374:39)
[exec] 	    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/polyfills.bundle.js:6156:32)
     [exec] 	    at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runGuarded (http://localhost:9876/_karma_webpack_/polyfills.bundle.js:5920:47)
[exec] 	    at runInTestZone (http://localhost:9876/_karma_webpack_/vendor.bundle.js:85157:25)
[exec] 	    at Object.<anonymous> (http://localhost:9876/_karma_webpack_/vendor.bundle.js:85096:13)
[exec] 	    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/polyfills.bundle.js:6157:26)
[exec] 	    at ProxyZoneSpec.webpackJsonp.../../../../zone.js/dist/proxy.js.ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/vendor.bundle.js:36377:39)
[exec] HeadlessChrome 0.0.0 (Linux 0.0.0): Executed 2 of 39 (1 FAILED) (0 secs / 1.319 secs)
[exec] HeadlessChrome 0.0.0 (Linux 0.0.0) VicContainerViewComponent should render the data grid with properly formatted data FAILED
[exec] 	TypeError: Cannot create property '__creationTrace__' on string '__zone_symbol__optimizedZoneEventTask'
[exec] 	    at Object.onScheduleTask (http://localhost:9876/_karma_webpack_/vendor.bundle.js:36231:38)
[exec] 	    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask (http://localhost:9876/_karma_webpack_/polyfills.bundle.js:6170:51)
[exec] 	    at Object.onScheduleTask (http://localhost:9876/_karma_webpack_/polyfills.bundle.js:6066:29)
     [exec] 	    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask (http://localhost:9876/_karma_webpack_/polyfills.bundle.js:6170:51)
[exec] 	    at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleTask (http://localhost:9876/_karma_webpack_/polyfills.bundle.js:6001:43)
[exec] 	    at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleEventTask (http://localhost:9876/_karma_webpack_/polyfills.bundle.js:6027:25)
[exec] 	    at HTMLElement.addEventListener (http://localhost:9876/_karma_webpack_/polyfills.bundle.js:7327:29)
[exec] 	    at DomEventsPlugin.webpackJsonp.../../../platform-browser/@angular/platform-browser.es5.js.DomEventsPlugin.addEventListener (http://localhost:9876/_karma_webpack_/vendor.bundle.js:98142:17)
[exec] 	    at EventManager.webpackJsonp.../../../platform-browser/@angular/platform-browser.es5.js.EventManager.addEventListener (http://localhost:9876/_karma_webpack_/vendor.bundle.js:97480:23)
[exec] 	    at DefaultDomRenderer2.webpackJsonp.../../../platform-browser/@angular/platform-browser.es5.js.DefaultDomRenderer2.listen (http://localhost:9876/_karma_webpack_/vendor.bundle.js:98001:36)
[exec] 	Failed: Cannot read property 'componentInstance' of undefined
[exec] 	TypeError: Cannot read property 'componentInstance' of undefined
[exec] 	    at Object.<anonymous> (http://localhost:9876/_karma_webpack_/main.bundle.js:284:16)
[exec] 	    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/polyfills.bundle.js:6157:26)
[exec] 	    at AsyncTestZoneSpec.webpackJsonp.../../../../zone.js/dist/async-test.js.AsyncTestZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/vendor.bundle.js:35601:39)
[exec] 	    at ProxyZoneSpec.webpackJsonp.../../../../zone.js/dist/proxy.js.ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/vendor.bundle.js:36374:39)
[exec] 	    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/polyfills.bundle.js:6156:32)
[exec] 	    at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runGuarded (http://localhost:9876/_karma_webpack_/polyfills.bundle.js:5920:47)
[exec] 	    at runInTestZone (http://localhost:9876/_karma_webpack_/vendor.bundle.js:85157:25)
[exec] 	    at Object.<anonymous> (http://localhost:9876/_karma_webpack_/vendor.bundle.js:85096:13)
[exec] 	    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/polyfills.bundle.js:6157:26)
[exec] 	    at ProxyZoneSpec.webpackJsonp.../../../../zone.js/dist/proxy.js.ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/vendor.bundle.js:36377:39)
...
```

**Comment by jooskim** [comment]
I just tried to build a new UI plugin packages and it failed for the same issue (but failed 6 times) so I can confirm this is a regression introduced by some updated npm dependency. I'll locate it and lock it down to the latest version that works.

**Comment by jooskim** [comment]
Looks like the latest release (0.8.13) of Zone.js is causing ths issue. Will try reverting to 0.8.12.
