### ISSUE TITLE
Portlayer doesn't restart on panic

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#5727]
Observed in #5700 branch here: https://ci.vcna.io/vmware/vic/12324

In the `1-04-Create` test the first failure is a legitimate issue cause by a fix elsewhere. It triggers a panic as seen below. The problem here is that the portlayer becomes unresponsive and we simply get messages such as:
```
Server error from portlayer: Post http://127.0.0.1:2377/containers: dial tcp 127.0.0.1:2377: getsockopt: connection refused
```

What should happen is that either:
1. the portlayer recovers from the panic completely and continues business as usual - that's the case here where the panic is extremely limited in scope and doesn't impact function
2. perform the neatest fatal exit viable and let `vic-init` restart it to restore function in the case where a simple `recover` handler cannot assure good state.

It's unclear to me why this panic has resulted in no subsequent requests being served, but it has. This is what needs to be addressed in this issue - a panic here should cause (1), but if that cannot be assured then (2) MUST occur.

The panic:
```
Jul 15 2017 03:37:05.425Z DEBUG Finished streaming containerLogs for ddfa6b1116c485491ea6915b6f5da27f12c59498eaf78f4249b1d24fe1f0fe23
panic: close of closed channel

goroutine 160 [running]:
github.com/vmware/vic/vendor/github.com/vmware/govmomi/object.(*followDatastoreFile).Close(0xc420af5080, 0x2, 0x2)
	/go/src/github.com/vmware/vic/vendor/github.com/vmware/govmomi/object/datastore_file.go:401 +0x2f
github.com/vmware/vic/lib/iolog.(*LogReader).Close(0xc4202bea80, 0xdf77cb, 0x18)
	<autogenerated>:1 +0x49
github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).GetContainerLogsHandler.func1()
	/go/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers/containers_handlers.go:424 +0x2f
github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*StreamOutputHandler).WriteResponse.func1(0xc420120380, 0xc420c343c0, 0xc4202beab0)
	/go/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers/stream_handler.go:71 +0xa7
created by github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*StreamOutputHandler).WriteResponse
	/go/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers/stream_handler.go:72 +0x3c0
```

**Comment by corrieb** [comment]
@hickeng Serviceability issue. Must fix for 1.2? Please make high priority if you agree
