### ISSUE TITLE
Docker compose 3-02 test fails with worker container not running on VC

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#6466]
From worker container output.log:
```
zXdTkdFC6BRgAw==System.TimeoutException: The operation has timed out.
kxRVkdFC6BTAAw==   at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
LB1VkdFC6BTAAw==   at Npgsql.NpgsqlConnector.RawOpen(NpgsqlTimeout timeout)
/yBVkdFC6BSQAw==   at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout)
tpyBkdFC6BQgBQ==   at Npgsql.ConnectorPool.Allocate(NpgsqlConnection conn, NpgsqlTimeout timeout)
/ceRkdFC6BTQAg==   at Npgsql.NpgsqlConnection.OpenInternal()
zNCRkdFC6BTwAw==   at Worker.Program.OpenDbConnection(String connectionString)
VteRkdFC6BSQAg==   at Worker.Program.Main(String[] args)
```

From docker-personality:
```
Sep 27 2017 15:52:25.854Z INFO  Sending die event for container 13cc9eac7c00bf1764581c7a3d752f48f6003626c43d927ad665d2b1dcae8c3e - code: 1
```

It looks like this is where the poweroff happened, in portlayer, but not sure why it happened:
```
Sep 27 2017 15:52:25.663Z DEBUG Found 2 subscribers to id: 5639 - vsphere.VMEvent: worker-13cc9eac7c00 on  10.160.46.181 in ha-datacenter is powered off
Sep 27 2017 15:52:25.663Z DEBUG Event manager calling back to exec
Sep 27 2017 15:52:25.663Z DEBUG Event manager calling back to logging
Sep 27 2017 15:52:25.663Z DEBUG [BEGIN] [github.com/vmware/vic/lib/portlayer/logging.eventCallback:52]
Sep 27 2017 15:52:25.663Z DEBUG [ END ] [github.com/vmware/vic/lib/portlayer/logging.eventCallback:52] [5.47µs] 
Sep 27 2017 15:52:25.663Z DEBUG [BEGIN] [github.com/vmware/vic/lib/portlayer/exec.(*Container).OnEvent:666] event PoweredOff received for id: 5639
Sep 27 2017 15:52:25.663Z DEBUG [BEGIN] [github.com/vmware/vic/lib/portlayer/exec.eventedState:640] event PoweredOff received for id: 5639
Sep 27 2017 15:52:25.663Z DEBUG [ END ] [github.com/vmware/vic/lib/portlayer/exec.eventedState:640] [3.613µs] event PoweredOff received for id: 5639
Sep 27 2017 15:52:25.663Z DEBUG [BEGIN] [github.com/vmware/vic/lib/portlayer/exec.(*containerBase).updates:116]
```

Logs:
[3-02-Docker-Compose-Voting-App-VCH-0-7274-container-logs.zip](https://github.com/vmware/vic/files/1337863/3-02-Docker-Compose-Voting-App-VCH-0-7274-container-logs.zip)

**Comment by mhagen-vmware** [comment]
On a second run, this actually passed. So it would seem we might have some sort of race here maybe?

**Comment by hickeng** [comment]
The power off happened because the container process exited (with exit code `1`), presumably because it couldn't connect.
```
System.TimeoutException: The operation has timed out.
   at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.RawOpen(NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout)
   at Npgsql.ConnectorPool.Allocate(NpgsqlConnection conn, NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnection.OpenInternal()
   at Worker.Program.OpenDbConnection(String connectionString)
   at Worker.Program.Main(String[] args)
```

Looking in the portlayer we see a name resolution request from the worker container for `db`:
```
Sep 27 2017 15:52:08.329Z DEBUG [BEGIN] [github.com/vmware/vic/lib/dns.(*Server).HandleVIC:369] ;; opcode: QUERY, status: NOERROR, id: 47192
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;db.	IN	 A

Sep 27 2017 15:52:08.329Z DEBUG RemoteAddr: 172.17.0.2
```

We see the following alias have been added for `db`:
```
Sep 27 2017 15:51:46.927Z DEBUG parsing alias :db
Sep 27 2017 15:51:46.927Z DEBUG getting aliases for db from worker
Sep 27 2017 15:51:46.927Z DEBUG getting aliases for db from vote
Sep 27 2017 15:51:46.927Z DEBUG getting aliases for db from result
Sep 27 2017 15:51:46.927Z DEBUG getting aliases for db from redis
Sep 27 2017 15:51:46.927Z DEBUG adding alias votingapp_default:db -> db
Sep 27 2017 15:51:46.927Z DEBUG adding alias votingapp_default:50e9de19c617 -> db
```

The database came up but the log output doesn't look particularly clean:
```
4lKuG9BC6BTgBA==The files belonging to this database system will be owned by user "postgres".
nIjeG9BC6BTAAg==This user must also own the server process.
4BQLHNBC6BQQAA==
HkI3HdBC6BQwBA==The database cluster will be initialized with locale "en_US.utf8".
esPdHdBC6BQgBA==The default database encoding has accordingly been set to "UTF8".
bRAHHtBC6BQABA==The default text search configuration will be set to "english".
ERksHtBC6BQQAA==
9P81HtBC6BQgAg==Data page checksums are disabled.
ZOhXHtBC6BQQAA==
N+NiHtBC6BTgBA==fixing permissions on existing directory /var/lib/postgresql/data/data ... ok
Kz6THtBC6BTwAQ==creating subdirectories ... ok
Q1xGItBC6BSgAg==selecting default max_connections ... 100
m5taI9BC6BSwAg==selecting default shared_buffers ... 128MB
n9TNI9BC6BSQAw==selecting dynamic shared memory implementation ... posix
cRYcWtBC6BRAAg==creating configuration files ... ok
W1Rve9BC6BSwBA==creating template1 database in /var/lib/postgresql/data/data/base/1 ... ok
MiYSfdBC6BTgAQ==initializing pg_authid ... ok
Skm5gNBC6BQQAg==initializing dependencies ... ok
oskkh9BC6BTQAQ==creating system views ... ok
8I6OitBC6BTAAg==loading system objects' descriptions ... ok
bbJLjNBC6BSwAQ==creating collations ... ok
LpjvltBC6BTAAQ==creating conversions ... ok
xlqXnNBC6BTQAQ==creating dictionaries ... ok
bq1yntBC6BTgAg==setting privileges on built-in objects ... ok
gQkHqtBC6BQwAg==creating information schema ... ok
CobZq9BC6BTQAg==loading PL/pgSQL server-side language ... ok
74VUw9BC6BRAAg==vacuuming database template1 ... ok
w0Mgx9BC6BRgAg==copying template1 to template0 ... ok
GISKydBC6BRQAg==copying template1 to postgres ... ok
KLnR3tBC6BSgAQ==syncing data to disk ... 
idrS3tBC6BTwAw==WARNING: enabling "trust" authentication for local connections
KeXS3tBC6BRgBA==You can change this by editing pg_hba.conf or using the option -A, or
bOvS3tBC6BTAAw==--auth-local and --auth-host, the next time you run initdb.
qdb/3tBC6BQwAA==ok
Mxsm39BC6BQQAA==
BYQr39BC6BRgAw==Success. You can now start the database server using:
1Yor39BC6BQQAA==
qI8r39BC6BTgAg==    postgres -D /var/lib/postgresql/data/data
f5Qr39BC6BQwAA==or
UZgr39BC6BTQAw==    pg_ctl -D /var/lib/postgresql/data/data -l logfile start
fJ0r39BC6BQQAA==
V6T+4dBC6BRQAw==****************************************************
nbFO4tBC6BRAAw==WARNING: No password has been set for the database.
BS5z4tBC6BQwAw==         This will allow anyone with access to the
HCud4tBC6BQwAw==         Postgres port to access your database. In
NqjJ4tBC6BQQAw==         Docker's default configuration, this is
Frzo4tBC6BRQAw==         effectively any other container on the same
xCYl49BC6BQQAQ==         system.
H0k449BC6BQQAA==
5jNF49BC6BRAAw==         Use "-e POSTGRES_PASSWORD=password" to set
wa5w49BC6BTQAQ==         it in "docker run".
6/GN49BC6BRQAw==****************************************************
ARn/6NBC6BTgBQ==waiting for server to start....LOG:  database system was shut down at 2017-09-27 15:52:19 UTC
M+7u6dBC6BTgAw==LOG:  MultiXact member wraparound protections are now enabled
vPWI6tBC6BRQAw==LOG:  database system is ready to accept connections
GmH56tBC6BQgAg==LOG:  autovacuum launcher started
wRwYINFC6BRgAA== done
3KgnINFC6BTwAA==server started
JwXuIdFC6BSwAA==ALTER ROLE
nExmItFC6BQQAA==
S8J/ItFC6BQQAA==
AY4vI9FC6BTABA==/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
BopiI9FC6BQQAA==
CqdtI9FC6BRQAg==LOG:  received fast shutdown request
n4yKI9FC6BRwAg==LOG:  aborting any active transactions
w8iqI9FC6BSAAg==LOG:  autovacuum launcher shutting down
3cnHI9FC6BRwAw==waiting for server to shut down....LOG:  shutting down
p6ZGJdFC6BQwAg==LOG:  database system is shut down
sT7JXtFC6BRgAA== done
51zpXtFC6BTwAA==server stopped
0mhzX9FC6BQQAA==
ROh0X9FC6BRgAw==PostgreSQL init process complete; ready for start up.
m/N0X9FC6BQQAA==
qSZyYtFC6BTwAw==LOG:  database system was shut down at 2017-09-27 15:52:21 UTC
eW9MY9FC6BTgAw==LOG:  MultiXact member wraparound protections are now enabled
jBkSZNFC6BRQAw==LOG:  database system is ready to accept connections
tJdzZNFC6BQgAg==LOG:  autovacuum launcher started
1pt/ZtFC6BSAAw==ERROR:  relation "votes" does not exist at character 38
TRaBZtFC6BRQBA==STATEMENT:  SELECT vote, COUNT(id) AS count FROM votes GROUP BY vote
/SyeotFC6BSAAw==ERROR:  relation "votes" does not exist at character 38
CXKfotFC6BRQBA==STATEMENT:  SELECT vote, COUNT(id) AS count FROM votes GROUP BY vote
aslO3tFC6BSAAw==ERROR:  relation "votes" does not exist at character 38
qmNS3tFC6BRQBA==STATEMENT:  SELECT vote, COUNT(id) AS count FROM votes GROUP BY vote
HYahGtJC6BSAAw==ERROR:  relation "votes" does not exist at character 38
XCzIGtJC6BRQBA==STATEMENT:  SELECT vote, COUNT(id) AS count FROM votes GROUP BY vote
yglUVtJC6BSAAw==ERROR:  relation "votes" does not exist at character 38
YBwOV9JC6BRQBA==STATEMENT:  SELECT vote, COUNT(id) AS count FROM votes GROUP BY vote
iooiktJC6BSAAw==ERROR:  relation "votes" does not exist at character 38
KZJnktJC6BRQBA==STATEMENT:  SELECT vote, COUNT(id) AS count FROM votes GROUP BY vote
oDFRztJC6BSAAw==ERROR:  relation "votes" does not exist at character 38
EyKbztJC6BRQBA==STATEMENT:  SELECT vote, COUNT(id) AS count FROM votes GROUP BY vote
+3L/CdNC6BSAAw==ERROR:  relation "votes" does not exist at character 38
CWgrCtNC6BRQBA==STATEMENT:  SELECT vote, COUNT(id) AS count FROM votes GROUP BY vote
CajIRdNC6BSAAw==ERROR:  relation "votes" does not exist at character 38
wu7yRdNC6BRQBA==STATEMENT:  SELECT vote, COUNT(id) AS count FROM votes GROUP BY vote
e2h1gdNC6BSAAw==ERROR:  relation "votes" does not exist at character 38
7eP3gdNC6BRQBA==STATEMENT:  SELECT vote, COUNT(id) AS count FROM votes GROUP BY vote
rcY2vdNC6BSAAw==ERROR:  relation "votes" does not exist at character 38
/++UvdNC6BRQBA==STATEMENT:  SELECT vote, COUNT(id) AS count FROM votes GROUP BY vote
BXkr+dNC6BSAAw==ERROR:  relation "votes" does not exist at character 38
GsJV+dNC6BRQBA==STATEMENT:  SELECT vote, COUNT(id) AS count FROM votes GROUP BY vote
FJPbNNRC6BSAAw==ERROR:  relation "votes" does not exist at character 38
ck9RNdRC6BRQBA==STATEMENT:  SELECT vote, COUNT(id) AS count FROM votes GROUP BY vote
i2KQcNRC6BSAAw==ERROR:  relation "votes" does not exist at character 38
qZbHcNRC6BRQBA==STATEMENT:  SELECT vote, COUNT(id) AS count FROM votes GROUP BY vote
```

The timing shows database "up" for whatever that means given the log output at `15:52:22.450Z`:
```
Sep 27 2017 15:52:22.450Z DEBUG [0xc4202261e0] write "LOG:  database system is ready to accept connections\n"
```

and the worker shutting down at `Sep 27 2017 15:52:23.209Z`:
```
Sep 27 2017 15:52:23.209Z DEBUG [0xc4201b99e0] write "System.TimeoutException: The operation has timed out.\n
```

There's a couple of things this could be - and this isn't an exhaustive list:
* arp resolution failure - significant delay can sometimes occur on a distributed switch - see #4715 - don't know if IP address with a fresh VM is a specific issue in a vSphere DPG.
* final connection attempt was made before the database was up and running

**Comment by sflxn** [comment]
It appears the database may not have created the tables correctly or there was some corruption in the DB file.  SQL requests are coming into the DB but the table relation doesn't appear valid.  The postgres DB init sequence above looks correct.  The shutdown above should be ignored as that is correct.  The final logs before the sql query failure shows

```
jBkSZNFC6BRQAw==LOG:  database system is ready to accept connections
```

**Comment by mhagen-vmware** [comment]
This was likely resolved with strict ordering changes to the compose file here, either way been running this test on VC for several months successfully now:
https://github.com/vmware/vic/pull/7729
