### ISSUE TITLE
VCH authentication with Nexus3 ERROR Looking up OAuth URL failed: download failed

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#6633]
Customer found issue with VIC against Nexus 3 container registry server.

Persona logs contains,
```
Looking up OAuth URL failed: download failed: www-authenticate header is corrupted
```

Internal bugzilla issue 1986601.

**Comment by sflxn** [comment]
I've watched the GSS video recording with the customer.  It looks like an issue I just fixed related to Artifactory.  I'll try to get nexus up and running to verify it.

**Comment by sflxn** [comment]
Logs shows a panic:
```
Oct 24 2017 17:22:13.131Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*System).AuthenticateToRegistry:324] [20.079068908s] 
2017-10-24 17:22:13.131740 I | http: panic serving 10.1.146.97:63546: runtime error: invalid memory address or nil pointer dereference
goroutine 74 [running]:
net/http.(*conn).serve.func1(0xc4207dc320)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0x2269a60, 0x3cc0110)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
net/url.(*URL).String(0x0, 0xc420509500, 0xc42022ba70)
	/usr/local/go/src/net/url/url.go:726 +0x40
github.com/vmware/vic/lib/apiservers/engine/backends.(*System).AuthenticateToRegistry.func1(0x27527b2, 0x4, 0xc420b41601, 0x0, 0x0, 0x3ce3be0, 0xc4209bb300)
	/go/src/github.com/vmware/vic/lib/apiservers/engine/backends/system.go:383 +0x375
github.com/vmware/vic/lib/apiservers/engine/backends.(*System).AuthenticateToRegistry(0xc42057e560, 0x7f701259db60, 0xc4204d98f0, 0xc420b08070, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/vmware/vic/lib/apiservers/engine/backends/system.go:401 +0x3f4
github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/system.(*systemRouter).postAuth(0xc4203af4a0, 0x7f701259db60, 0xc4204d98f0, 0x3d298a0, 0xc4207e6000, 0xc4204dfe00, 0xc4204d96e0, 0x3d2b860, 0xc4204d98f0)
	/go/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/system/system_routes.go:167 +0x17e
github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/system.(*systemRouter).(github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/system.postAuth)-fm(0x7f701259db60, 0xc4204d98f0, 0x3d298a0, 0xc4207e6000, 0xc4204dfe00, 0xc4204d96e0, 0x7f701259db60, 0xc4204d98f0)
	/go/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/system/system.go:30 +0x69
github.com/vmware/vic/vendor/github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x7f701259db60, 0xc4204d97a0, 0x3d298a0, 0xc4207e6000, 0xc4204dfe00, 0xc4204d96e0, 0x0, 0x756ea1110b6fa5)
	/go/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/middleware/version.go:47 +0x50b
github.com/vmware/vic/vendor/github.com/docker/docker/api/server/middleware.DebugRequestMiddleware.func1(0x7f701259db60, 0xc4204d97a0, 0x3d298a0, 0xc4207e6000, 0xc4204dfe00, 0xc4204d96e0, 0x7f701259db60, 0xc4204d97a0)
	/go/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/middleware/debug.go:53 +0x527
github.com/vmware/vic/vendor/github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x3d298a0, 0xc4207e6000, 0xc4204dfe00)
	/go/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/server.go:139 +0x21a
net/http.HandlerFunc.ServeHTTP(0xc42023b5c0, 0x3d298a0, 0xc4207e6000, 0xc4204dfe00)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/vmware/vic/vendor/github.com/docker/docker/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420594cd0, 0x3d298a0, 0xc4207e6000, 0xc4204dfe00)
	/go/src/github.com/vmware/vic/vendor/github.com/docker/docker/vendor/github.com/gorilla/mux/mux.go:103 +0x255
github.com/vmware/vic/vendor/github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc420b2b5a0, 0x3d298a0, 0xc4207e6000, 0xc4204dfe00)
	/go/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router_swapper.go:29 +0x70
net/http.serverHandler.ServeHTTP(0xc420092f20, 0x3d298a0, 0xc4207e6000, 0xc4204dfe00)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4207dc320, 0x3d2b7a0, 0xc4204a5b00)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
```

**Comment by sflxn** [comment]
Error from GSS' video walkthrough with the customer shows,

```
error during connect:  Post https://<...>/v1.25/auth:  EOF
```

That is the panic in the previous analysis.

**Comment by sflxn** [comment]
Based on the last two analysis post, I believe #5338 fixed this issue.  I fixed 2 bugs in that issue.  The first bug in that issue was exactly this panic.
