### ISSUE TITLE
Attempt to concurrently power on 200+ containers across VCHs failed with "~has been marked [DISABLED] after failure to perform data collection"

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic#6850]
@lgayatri commented on [Tue Nov 21 2017](https://github.com/vmware/vic-product/issues/1109)

Live Setup available until 11/22. Please ping me on slack for credentials. An attempt to start 200+ containers failed with VCHs being marked as DISABLED. The same VCH was again marked ON after 2 hours.

https://10.197.37.132:8282/#/home/containers
![image](https://user-images.githubusercontent.com/25006749/33065580-422833a8-cecf-11e7-8aee-8793cd03c2fc.png)

```
Host [10.197.37.159:2376] has been marked [
DISABLED] after failure to perform data collection. Error message is: null; Reason: {"stackTrace":["com.vmware.xenon.common.Operation.fail(Operation.java:1234)","com.vmware.xenon.common.http.netty.NettyHttpServiceClient.failExpiredRequests(NettyHttpServiceClient.java:846)","com.vmware.xenon.common.http.netty.NettyHttpServiceClient.handleMaintenance(NettyHttpServiceClient.java:793)","com.vmware.admiral.adapter.docker.service.RemoteApiDockerAdapterCommandExecutorImpl.handlePeriodicMaintenance(RemoteApiDockerAdapterCommandExecutorImpl.java:188)","com.vmware.admiral.adapter.docker.service.AbstractDockerAdapterService.handlePeriodicMaintenance(AbstractDockerAdapterService.java:103)","com.vmware.xenon.common.StatelessService.handleMaintenance(StatelessService.java:267)","com.vmware.xenon.common.ServiceMaintenanceTracker.lambda$performServiceMaintenance$1(ServiceMaintenanceTracker.java:175)","com.vmware.xenon.common.ServiceHost.executeRunnableSafe(ServiceHost.java:5270)","com.vmware.xenon.common.ServiceHost.lambda$schedule$58(ServiceHost.java:5264)","java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)","java.util.concurrent.FutureTask.run(FutureTask.java:266)","java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)","java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)","java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)","java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)","java.lang.Thread.run(Thread.java:748)"],"statusCode":408,"documentKind":"com:vmware:xenon:common:ServiceErrorResponse","errorCode":0}
```

Log snippet from VCH says:
```
Nov 21 2017 07:34:09.483Z ERROR op=294.4601: vic/pkg/trace.(*Operation).Err: WaitForSession error: context deadline exceeded
Nov 21 2017 07:34:09.484Z ERROR op=294.4601: vic/pkg/trace.(*Operation).Err: WaitForSession error: context deadline exceeded
Nov 21 2017 07:34:13.134Z ERROR op=294.4601: CommitHandler error on handle(0601e29f1861d8eb4f80d59ccb959309) for 2651cc010f74871583d3ea2b2958a37f34bb1eadf2b619707840acae0091744b: unable to wait for process launch status: Post https://wdc-stvc3944-146-dhcp15.eng.vmware.com/sdk: context deadline exceeded
Nov 21 2017 07:34:18.368Z ERROR op=294.4725: unexpected fault on task retry: &types.ConcurrentAccess{VimFault:types.VimFault{MethodFault:types.MethodFault{FaultCause:(*types.LocalizedMethodFault)(nil), FaultMessage:[]types.LocalizableMessage(nil)}}}
Nov 21 2017 07:34:18.382Z ERROR op=294.4727: unexpected fault on task retry: &types.ConcurrentAccess{VimFault:types.VimFault{MethodFault:types.MethodFault{FaultCause:(*types.LocalizedMethodFault)(nil), FaultMessage:[]types.LocalizableMessage(nil)}}}
Nov 21 2017 07:34:18.393Z ERROR op=294.4726: unexpected fault on task retry: &types.ConcurrentAccess{VimFault:types.VimFault{MethodFault:types.MethodFault{FaultCause:(*types.LocalizedMethodFault)(nil), FaultMessage:[]types.LocalizableMessage(nil)}}}
Nov 21 2017 07:34:18.407Z ERROR op=294.4728: unexpected fault on task retry: &types.ConcurrentAccess{VimFault:types.VimFault{MethodFault:types.MethodFault{FaultCause:(*types.LocalizedMethodFault)(nil), FaultMessage:[]types.LocalizableMessage(nil)}}}
Nov 21 2017 07:34:18.420Z ERROR op=294.4729: unexpected fault on task retry: &types.ConcurrentAccess{VimFault:types.VimFault{MethodFault:types.MethodFault{FaultCause:(*types.LocalizedMethodFault)(nil), FaultMessage:[]types.LocalizableMessage(nil)}}}
Nov 21 2017 07:34:18.427Z ERROR op=294.4730: unexpected fault on task retry: &types.ConcurrentAccess{VimFault:types.VimFault{MethodFault:types.MethodFault{FaultCause:(*types.LocalizedMethodFault)(nil), FaultMessage:[]types.LocalizableMessage(nil)}}}
```

---

@lgayatri commented on [Tue Nov 21 2017](https://github.com/vmware/vic-product/issues/1109#issuecomment-345977329)

[VCH-159.zip](https://github.com/vmware/vic-product/files/1490848/VCH-159.zip)

**Comment by mdubya66** [comment]
is this related to #6851

**Comment by sflxn** [comment]
I've seen this issue myself.  It's not related to #6851.

```
Nov 21 2017 07:34:09.483Z ERROR op=294.4601: vic/pkg/trace.(*Operation).Err: WaitForSession error: context deadline exceeded
vic/lib/portlayer/exec.(*Container).start:423 WaitForSession
vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).CommitHandler:220 commit handle(0601e29f1861d8eb4f80d59ccb959309)
Nov 21 2017 07:34:09.484Z ERROR op=294.4601: vic/pkg/trace.(*Operation).Err: WaitForSession error: context deadline exceeded
vic/lib/portlayer/exec.(*Container).start:423 WaitForSession

...

Nov 21 2017 07:34:13.134Z ERROR op=294.4601: CommitHandler error on handle(0601e29f1861d8eb4f80d59ccb959309) for 2651cc010f74871583d3ea2b2958a37f34bb1eadf2b619707840acae0091744b: unable to wait for process launch status: Post https://wdc-stvc3944-146-dhcp15.eng.vmware.com/sdk: context deadline exceeded
```

It's a session expiration issue.

**Comment by sflxn** [comment]
This issue may be blocked on https://github.com/vmware/admiral/issues/234 as I cannot select more than 96 containers in Admiral with RC3.  I've only been able to come across this when starting 400 containers through Admiral.

**Comment by sflxn** [comment]
From Admiral logs:

```
[1517004][W][2017-12-12T00:02:24.976Z][705][8282/adapters/host-docker-service][fail][Fail: java.lang.Exception: No route to host: /10.197.37.161:2376; Reason: {"message":"No route to host: /10.197.37.161:2376","stackTrace":["sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)","sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)","io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:352)","io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)","io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:632)","io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)","io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)","io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)","io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)","java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)","java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)","java.lang.Thread.run(Thread.java:748)"],"statusCode":500,"details":["SHOULD_RETRY"],"documentKind":"com:vmware:xenon:common:ServiceErrorResponse","errorCode":0}
	at com.vmware.admiral.adapter.docker.service.AbstractDockerAdapterService.fail(AbstractDockerAdapterService.java:374)
	at com.vmware.admiral.adapter.docker.service.DockerHostAdapterService.lambda$getHostPatchCompletionHandler$16(DockerHostAdapterService.java:501)
	at com.vmware.xenon.common.Operation.completeOrFail(Operation.java:1331)
	at com.vmware.xenon.common.Operation.fail(Operation.java:1309)
	at com.vmware.xenon.common.Operation.fail(Operation.java:1237)
	at com.vmware.xenon.common.http.netty.NettyHttpServiceClient.fail(NettyHttpServiceClient.java:725)
	at com.vmware.xenon.common.http.netty.NettyHttpServiceClient.lambda$connectChannel$0(NettyHttpServiceClient.java:421)
	at com.vmware.xenon.common.Operation.lambda$nestCompletion$1(Operation.java:1362)
	at com.vmware.xenon.common.Operation.completeOrFail(Operation.java:1331)
	at com.vmware.xenon.common.Operation.fail(Operation.java:1309)
	at com.vmware.xenon.common.http.netty.NettyChannelPool.fail(NettyChannelPool.java:579)
	at com.vmware.xenon.common.http.netty.NettyChannelPool.lambda$connectOrReuse$1(NettyChannelPool.java:356)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:500)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:479)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:122)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:327)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:343)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:632)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: /10.197.37.161:2376
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:352)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
	... 8 more
Caused by: java.net.NoRouteToHostException: No route to host
	... 12 more
]
[1517005][I][2017-12-12T00:02:24.977Z][705][8282/adapters/host-docker-service][patchTaskStage][Patching adapter callback task https://172.17.0.3:8282/request/callback-handler/452151c2-e746-43ae-a4af-e4bf2a4808b5 with state FAILED for resource: https://172.17.0.3:8282/resources/compute/8d72ccadc773147555fcf36ca2641]
[1517006][I][2017-12-12T00:02:24.977Z][35079][8282/request/callback-handler/452151c2-e746-43ae-a4af-e4bf2a4808b5][validateStageTransitionAndState][Moving from STARTED(CREATED) to FAILED(ERROR). Caller: [https://vic-st-h2-132.eng.vmware.com:8282/adapters/host-docker-service]]
[1517007][W][2017-12-12T00:02:24.977Z][35079][8282/request/callback-handler/452151c2-e746-43ae-a4af-e4bf2a4808b5][handleFailedStagePatch][Failed updating host info]
[1517008][W][2017-12-12T00:02:24.977Z][35079][8282/request/callback-handler/452151c2-e746-43ae-a4af-e4bf2a4808b5][handleFailedStagePatch][Task failure error message: No route to host: /10.197.37.161:2376; Reason: {"message":"No route to host: /10.197.37.161:2376","stackTrace":["sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)","sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)","io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:352)","io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)","io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:632)","io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)","io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)","io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)","io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)","java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)","java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)","java.lang.Thread.run(Thread.java:748)"],"statusCode":500,"details":["SHOULD_RETRY"],"documentKind":"com:vmware:xenon:common:ServiceErrorResponse","errorCode":0}]
[1517009][W][2017-12-12T00:02:24.977Z][35079][8282/][lambda$prepareRequest$46][DELETE (ctx id:452151c2-e746-43ae-a4af-e4bf2a4808b5) to https://172.17.0.3:8282/request/callback-handler/452151c2-e746-43ae-a4af-e4bf2a4808b5, from https://vic-st-h2-132.eng.vmware.com:8282/request/callback-handler/452151c2-e746-43ae-a4af-e4bf2a4808b5 failed: Service not found: https://172.17.0.3:8282/request/callback-handler/452151c2-e746-43ae-a4af-e4bf2a4808b5]
[1517010][I][2017-12-12T00:02:56.276Z][11][8282/][lambda$schedulePeriodicCertificatesReload$1][Host https://vic-st-h2-132.eng.vmware.com:8282/: reloading all certificates]
```

**Comment by gigawhitlocks** [comment]
OK I tried running this and tailing all of the relevant logs.
Right before we start getting errors from the portlayer we get this:
```
[11703][W][2017-12-12T00:43:26.288Z][639][8282/adapters/docker-service][fail][Fail: java.lang.Exception: Service https://10.161.161.35:2376/v1.24/containers/create?name=alpine-mcm1105-61432734169 returned error 409 for POST. id 313788 message conflict. The name "alpine-mcm1105-61432734169" is already in use by container b75cd96faf3c633dfb9a66c70568eb26316b59b5f683ac2eef29d669fa304e32. You have to remove (or rename) that container to be able to re use that name.; Reason: {"message":"conflict. The name \"alpine-mcm1105-61432734169\" is already in use by container b75cd96faf3c633dfb9a66c70568eb26316b59b5f683ac2eef29d669fa304e32. You have to remove (or rename) that container to be able to re use that name."}

	at com.vmware.admiral.adapter.docker.service.AbstractDockerAdapterService.fail(AbstractDockerAdapterService.java:374)
	at com.vmware.admiral.adapter.docker.service.DockerAdapterService.lambda$null$23(DockerAdapterService.java:782)
	at com.vmware.xenon.common.Operation.completeOrFail(Operation.java:1331)
	at com.vmware.xenon.common.Operation.fail(Operation.java:1309)
	at com.vmware.xenon.common.Operation.fail(Operation.java:1237)
	at com.vmware.xenon.common.http.netty.NettyHttpServiceClient.fail(NettyHttpServiceClient.java:725)
	at com.vmware.xenon.common.http.netty.NettyHttpServiceClient.lambda$sendHttpRequest$1(NettyHttpServiceClient.java:580)
	at com.vmware.xenon.common.Operation.lambda$nestCompletion$1(Operation.java:1362)
	at com.vmware.xenon.common.Operation.completeOrFail(Operation.java:1331)
	at com.vmware.xenon.common.Operation.fail(Operation.java:1309)
	at com.vmware.xenon.common.Operation.fail(Operation.java:1237)
	at com.vmware.xenon.common.http.netty.NettyHttpServerResponseHandler.checkResponseForError(NettyHttpServerResponseHandler.java:242)
	at com.vmware.xenon.common.http.netty.NettyHttpServerResponseHandler.decodeResponseBody(NettyHttpServerResponseHandler.java:177)
	at com.vmware.xenon.common.http.netty.NettyHttpServerResponseHandler.completeRequest(NettyHttpServerResponseHandler.java:160)
	at com.vmware.xenon.common.http.netty.NettyHttpServerResponseHandler.channelRead0(NettyHttpServerResponseHandler.java:67)
	at com.vmware.xenon.common.http.netty.NettyHttpServerResponseHandler.channelRead0(NettyHttpServerResponseHandler.java:42)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1267)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1078)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ProtocolException: Service https://10.161.161.35:2376/v1.24/containers/create?name=alpine-mcm1105-61432734169 returned error 409 for POST. id 313788 message conflict. The name "alpine-mcm1105-61432734169" is already in use by container b75cd96faf3c633dfb9a66c70568eb26316b59b5f683ac2eef29d669fa304e32. You have to remove (or rename) that container to be able to re use that name.
	... 40 more
```

We get a whole bunch of these name conflicts, and then the VCH starts trying to back out changes, and everything goes nuts.. still investigating.

**Comment by gigawhitlocks** [comment]
On the PL side we see this concurrently:
```vic/lib/portlayer/exec.(*Container).start:423 WaitForSession
vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).CommitHandler:218 commit handle(7782f8d25731d51706be8e5859ec9007)
Dec 12 2017 00:44:41.412Z ERROR op=286.4018: unexpected fault on task retry: &types.GenericVmConfigFault{VmConfigFault:types.VmConfigFault{VimFault:types.VimFault{MethodFault:types.MethodFault{FaultCause:(*types.LocalizedMethodFault)(nil), FaultMessage:[]types.LocalizableMessage{types.LocalizableMessage{DynamicData:types.DynamicData{}, Key:"msg.moduletable.powerOnFailed", Arg:[]types.KeyAnyValue{types.KeyAnyValue{DynamicData:types.DynamicData{}, Key:"1", Value:"MonitorLoop"}}, Message:"Module 'MonitorLoop' power on failed. "}, types.LocalizableMessage{DynamicData:types.DynamicData{}, Key:"msg.dictionary.notBoolean", Arg:[]types.KeyAnyValue{types.KeyAnyValue{DynamicData:types.DynamicData{}, Key:"1", Value:"“TRUE\""}, types.KeyAnyValue{DynamicData:types.DynamicData{}, Key:"2", Value:"vhv.enable"}, types.KeyAnyValue{DynamicData:types.DynamicData{}, Key:"3", Value:"FALSE"}}, Message:"Value \"“TRUE\"\" for variable \"vhv.enable\" is not a valid boolean value. Using value \"FALSE\". "}, types.LocalizableMessage{DynamicData:types.DynamicData{}, Key:"vob.swap.poweron.createfailure.status", Arg:[]types.KeyAnyValue{types.KeyAnyValue{DynamicData:types.DynamicData{}, Key:"1", Value:"/vmfs/volumes/vsan:521a19debbea7f19-185ebbf292bf4d3b/4b252f5a-aa59-3d1c-9a87-020048644ef0/alpine-mcm1126-61432734169-e932f2ffe050-c233cfad.vswp"}, types.KeyAnyValue{DynamicData:types.DynamicData{}, Key:"2", Value:"Failure"}}, Message:"Failed to create swap file '/vmfs/volumes/vsan:521a19debbea7f19-185ebbf292bf4d3b/4b252f5a-aa59-3d1c-9a87-020048644ef0/alpine-mcm1126-61432734169-e932f2ffe050-c233cfad.vswp' : Failure"}, types.LocalizableMessage{DynamicData:types.DynamicData{}, Key:"msg.vmmonVMK.creatVMFailed", Arg:[]types.KeyAnyValue{types.KeyAnyValue{DynamicData:types.DynamicData{}, Key:"1", Value:"msg.vmk.status.VMK_FAILURE"}}, Message:"Could not power on virtual machine: Failure."}, types.LocalizableMessage{DynamicData:types.DynamicData{}, Key:"msg.monitorLoop.createVMFailed.vmk", Arg:[]types.KeyAnyValue(nil), Message:"Failed to power on VM."}, types.LocalizableMessage{DynamicData:types.DynamicData{}, Key:"msg.vmx.poweron.failed", Arg:[]types.KeyAnyValue(nil), Message:"Failed to start the virtual machine."}, types.LocalizableMessage{DynamicData:types.DynamicData{}, Key:"vpxd.vm.poweron.unexpectedfailure", Arg:[]types.KeyAnyValue{types.KeyAnyValue{DynamicData:types.DynamicData{}, Key:"1", Value:"alpine-mcm1126-61432734169-e932f2ffe050"}}, Message:"An error was received from the ESX host while powering on VM alpine-mcm1126-61432734169-e932f2ffe050."}}}}}, Reason:"Module 'MonitorLoop' power on failed. "}
```

and on the persona side, first we get a bunch of name conflict errors that correlate to the above:
```
Dec 12 2017 00:43:25.596Z ERROR Handler for POST /v1.24/containers/create returned error: conflict. The name "alpine-mcm1105-61432734169" is already in use by container b75cd96faf3c633dfb9a66c70568eb26316b59b5f683ac2eef29d669fa304e32. You have to remove (or rename) that container to be able to re use that name.
```

and then Admiral stops trying to create new containers and eventually we get some more errors from the persona

```
Dec 12 2017 00:44:55.081Z ERROR Will stop trying again. Operation failed with errors.apiError{error:(*errors.errorString)(0xc428042010), statusCode:500}
Dec 12 2017 00:44:55.081Z ERROR Handler for POST /v1.24/containers/52f0e589b1a709150cfdf38e2c352f45ec25a3f81860f604af40af5b2281703f/start returned error: Server error from portlayer: Module 'MonitorLoop' power on failed. 
Dec 12 2017 00:44:55.089Z ERROR Will stop trying again. Operation failed with errors.apiError{error:(*errors.errorString)(0xc4280426f0), statusCode:500}
Dec 12 2017 00:44:55.089Z ERROR Handler for POST /v1.24/containers/1666077b6565fe6e9b142954290a54184387a4495834d67a5b42c71ba9152c40/start returned error: Server error from portlayer: Module 'MonitorLoop' power on failed. 
Dec 12 2017 00:44:55.094Z ERROR Will stop trying again. Operation failed with errors.apiError{error:(*errors.errorString)(0xc4280431d0), statusCode:500}
Dec 12 2017 00:44:55.094Z ERROR Handler for POST /v1.24/containers/74b87be1898c5b5032d9caebfab77f7d3525c4fe2f0f84454e571d8a05688c45/start returned error: Server error from portlayer: Module 'MonitorLoop' power on failed. 
```

(Omitting too many repetitions of the same errors)

**Comment by gigawhitlocks** [comment]
Kind of just looks like the VCH is getting DoSed by Admiral..

**Comment by sflxn** [comment]
Unless something jumps out, I think we need to hand this issue over to Admiral.  The original error is an Admiral error, and I don't have enough information to figure out if it's an issue with the VCH.  We see various concurrent access issues and sesssion timeouts, but that doesn't mean they are related to this issue.

**Comment by sflxn** [comment]
Issue moved to [vmware/admiral #235](https://github.com/vmware/admiral/issues/235) via [**ZenHub**](https://www.zenhub.com/)

**Comment by AntonioFilipov** [comment]
@andrewtchin @sflxn could you take a look at my last comment on this issue https://github.com/vmware/admiral/issues/235. Based on it, I've tried to reopen this issue, but I cannot do it. Thanks!

**Comment by mdubya66** [comment]
I'm re-opening this based on the last comments in vmware/admiral#235. There might be some better behavior for the VCH to inform admiral that it has received the shutdown and is taking action, or something.

**Comment by mdubya66** [comment]
Removing from 1.3 as a ship stopper since the VCH recovers from the shutdown request storm.

**Comment by lgayatri** [comment]
@mdubya66 - can we fix this for 1.4?

**Comment by mdubya66** [comment]
@lgayatri we should fix this in 1.4

**Comment by lgayatri** [comment]
RC5 : https://storage.cloud.google.com/vic-product-ova-releases/vic-v1.3.0-rc5-2996-f8cc7317.ova

![image](https://user-images.githubusercontent.com/25006749/34513323-c0cce944-f08d-11e7-9525-9cfb70b92b98.png)
Thanks @mdubya66 , will verify in 1.4.

**Comment by lgayatri** [comment]
Seeing many VCHs in DISABLED state 

![image](https://user-images.githubusercontent.com/25006749/34513398-24f3a48a-f08e-11e7-8a6b-05dadd01cba4.png)

**Comment by mdubya66** [comment]
@lgayatri do we still hit this issue in your setup?

**Comment by lgayatri** [comment]
Not seeing this issue but hit https://github.com/vmware/admiral/issues/258. Closing for now.
