### ISSUE TITLE
vic-machine API panic handling middleware panics when ctrl+c kills running handler

### ISSUE THREAD

**Issue by AngieCris** [vmware/vic#6934]
When clients kills a running handler process with system interrupt (ctrl+c in this case), the panic handler middleware panics with `nil pointer derefence` 

vic-machine-server.log:
```
Dec  7 2017 18:40:38.132-08:00 INFO  Starting Service. Version: "v1.3.0-rc1-0-3aafdc8"
Dec  7 2017 18:40:38.220-08:00 INFO  Serving pprof at http://localhost:6060
Dec  7 2017 18:40:38.223-08:00 INFO  Serving vic machine at http://127.0.0.1:1337
Dec  7 2017 18:41:19.071-08:00 INFO  op=18966.1: Request: GET /container/target/10.161.2.135/vch HTTP/1.1
Dec  7 2017 18:41:21.638-08:00 ERROR op=18966.1: vic/pkg/trace.(*Operation).Err: HTTP/1.1 GET request to /container/target/10.161.2.135/vch error: context canceled
vic/lib/apiservers/service/restapi.addLogging.func1:212 HTTP/1.1 GET request to /container/target/10.161.2.135/vch
Dec  7 2017 18:41:21.638-08:00 ERROR op=18966.1: vic/pkg/trace.(*Operation).Err: HTTP/1.1 GET request to /container/target/10.161.2.135/vch error: context canceled
vic/lib/apiservers/service/restapi.addLogging.func1:212 HTTP/1.1 GET request to /container/target/10.161.2.135/vch
Dec  7 2017 18:41:21.639-08:00 ERROR op=18966.1: PANIC: runtime error: invalid memory address or nil pointer dereference
goroutine 23 [running]:
github.com/vmware/vic/lib/apiservers/service/restapi.addPanicRecovery.func1.1(0xc42000a900, 0x1b660a0, 0xc420732160)
	/home/angiew/go/src/github.com/vmware/vic/lib/apiservers/service/restapi/configure_vic_machine.go:258 +0x13c
panic(0xf4b9a0, 0x1b48e30)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/vmware/vic/pkg/vsphere/session.(*Session).Populate(0xc42018b180, 0x1b67b20, 0xc4205d52c0, 0xd, 0x1, 0x0)
	/home/angiew/go/src/github.com/vmware/vic/pkg/vsphere/session/session.go:358 +0xf8a
github.com/vmware/vic/lib/install/validate.NewValidator(0x1b67b20, 0xc4205d52c0, 0xc420196400, 0x0, 0x0, 0x0)
	/home/angiew/go/src/github.com/vmware/vic/lib/install/validate/validator.go:159 +0x978
github.com/vmware/vic/lib/apiservers/service/restapi/handlers.validateTarget(0x1b67820, 0xc420315980, 0xc42018aff0, 0x1, 0x1, 0xc4201da520, 0x7, 0x0, 0xc420196400, 0x0, ...)
	/home/angiew/go/src/github.com/vmware/vic/lib/apiservers/service/restapi/handlers/common.go:91 +0x17a
github.com/vmware/vic/lib/apiservers/service/restapi/handlers.listVCHs(0x1b67820, 0xc420315980, 0xc42018aff0, 0x1, 0x1, 0xc4201da520, 0x7, 0x0, 0xc420196400, 0xc, ...)
	/home/angiew/go/src/github.com/vmware/vic/lib/apiservers/service/restapi/handlers/vch_list_get.go:88 +0x5f
github.com/vmware/vic/lib/apiservers/service/restapi/handlers.(*VCHListGet).Handle(0x1bac4d0, 0xc42000a900, 0x0, 0xc4203a8216, 0xc, 0xc4201da860, 0x10072e0, 0xc4207321e0, 0x1bac601, 0x100000001b51410)
	/home/angiew/go/src/github.com/vmware/vic/lib/apiservers/service/restapi/handlers/vch_list_get.go:56 +0x34c
github.com/vmware/vic/lib/apiservers/service/restapi/operations.(*GetTargetTargetVch).ServeHTTP(0xc4206b3500, 0x1b660a0, 0xc420732160, 0xc42000a900)
	/home/angiew/go/src/github.com/vmware/vic/lib/apiservers/service/restapi/operations/get_target_target_vch.go:66 +0x340
github.com/vmware/vic/vendor/github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1(0x1b660a0, 0xc420732160, 0xc42000a900)
	/home/angiew/go/src/github.com/vmware/vic/vendor/github.com/go-openapi/runtime/middleware/operation.go:24 +0x69
net/http.HandlerFunc.ServeHTTP(0xc420690040, 0x1b660a0, 0xc420732160, 0xc42000a900)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/vmware/vic/vendor/github.com/go-openapi/runtime/middleware.NewRouter.func1(0x1b660a0, 0xc420732160, 0xc42000a900)
	/home/angiew/go/src/github.com/vmware/vic/vendor/github.com/go-openapi/runtime/middleware/router.go:75 +0x3b2
net/http.HandlerFunc.ServeHTTP(0xc4205e4220, 0x1b660a0, 0xc420732160, 0xc42000a900)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/vmware/vic/vendor/github.com/go-openapi/runtime/middleware.Redoc.func1(0x1b660a0, 0xc420732160, 0xc42000a900)
	/home/angiew/go/src/github.com/vmware/vic/vendor/github.com/go-openapi/runtime/middleware/redoc.go:72 +0xa3
net/http.HandlerFunc.ServeHTTP(0xc4208e80c0, 0x1b660a0, 0xc420732160, 0xc42000a900)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/vmware/vic/vendor/github.com/go-openapi/runtime/middleware.Spec.func1(0x1b660a0, 0xc420732160, 0xc42000a900)
	/home/angiew/go/src/github.com/vmware/vic/vendor/github.com/go-openapi/runtime/middleware/spec.go:45 +0x82
net/http.HandlerFunc.ServeHTTP(0xc4208e8100, 0x1b660a0, 0xc420732160, 0xc42000a900)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/vmware/vic/vendor/github.com/rs/cors.(*Cors).Handler.func1(0x1b660a0, 0xc420732160, 0xc42000a900)
	/home/angiew/go/src/github.com/vmware/vic/vendor/github.com/rs/cors/cors.go:200 +0xe9
net/http.HandlerFunc.ServeHTTP(0xc4208e24e0, 0x1b660a0, 0xc420732160, 0xc42000a900)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/vmware/vic/lib/apiservers/service/restapi.addPanicRecovery.func1(0x1b660a0, 0xc420732160, 0xc42000a900)
	/home/angiew/go/src/github.com/vmware/vic/lib/apiservers/service/restapi/configure_vic_machine.go:269 +0x9f
net/http.HandlerFunc.ServeHTTP(0xc4208e2500, 0x1b660a0, 0xc420732160, 0xc42000a900)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/vmware/vic/lib/apiservers/service/restapi.addLogging.func1(0x1b66be0
```

It fails at this line of code in panic handling middleware in `configure_vic_machine.go` (https://github.com/vmware/vic/blob/master/lib/apiservers/service/restapi/configure_vic_machine.go#L258):
```
bytes := goruntime.Stack(buf, false)
```
runtime stack is not available when terminating with ctrl+c, thus nil pointer dereference. 

(Also, the panic handling middleware defaults to 500 Internal Server Error when there is a panic. In this case, since the client side initiates the system interrupt, it should not be a server side error)

**Comment by anchal-agrawal** [comment]
Backlog items should have a priority.
