### ISSUE TITLE
VCH create with no gateway configuration in container network panics with nil pointer dereference

### ISSUE THREAD

**Issue by AngieCris** [vmware/vic#6977]
![containernetwork](https://user-images.githubusercontent.com/6562128/34121687-82a0cda2-e3ef-11e7-9e5c-10262f63a304.png)

When specifying container network setting, if leave container network gateway empty, the deployment with API panics.
According to the doc, container network gateway option is only required if the network is static (https://vmware.github.io/vic-product/assets/files/html/1.2/vic_vsphere_admin/container_networks.html):
> This option is required if the network that you specify in the --container-network option does not support DHCP. 
> The range of IP addresses that container VMs can use if the network that you specify in the container-network option does not support DHCP. 

The UI has already disabled gateway input field when DHCP is selected for container network. Apparently API still tries to grab the gateway. 

Request body:
```
{"name":"virtual-container-host","compute":{"cpu":{"limit":{"units":"MHz","value":0}},"memory":{"limit":{"units":"MiB","value":0}},"resource":{"name":"/RegionA01/host/RegionA01-COMP01"}},"storage":{"image_stores":["RegionA01-ISCSI01-COMP01"],"base_image_size":{"units":"GiB","value":8},"volume_stores":[{"datastore":"RegionA01-ISCSI01-COMP01","label":"default"}]},"network":{"bridge":{"ip_range":"172.16.0.0/12","port_group":{"name":"Bridge01-RegionA01-vDS-COMP"}},"public":{"port_group":{"name":"VM-RegionA01-vDS-COMP"},"static":"192.168.100.22/24","gateway":{"address":"192.168.100.1"},"nameservers":["192.168.110.10"]},"container":[{"port_group":{"name":"VM-RegionA01-vDS-COMP"},"alias":"routable","firewall":"open"}]},"auth":{"client":{"no_tls_verify":true},"server":{"generate":{"size":{"value":2048,"units":"bit"},"organization":["virtual-container-host"],"cname":"vch1.corp.local"}}},"container":{},"debug":0,"endpoint":{"operations_credentials":{"user":"administrator@vsphere.local","password":"VMware1!"}},"registry":{}}
```

CLI equivalent succeeds with no error:
```
./vic-machine-linux create --name virtual-container-host --compute-resource /RegionA01/host/RegionA01-COMP01 --image-store RegionA01-ISCSI01-COMP01 --base-image-size 8GB --volume-store RegionA01-ISCSI01-COMP01:default --bridge-network Bridge01-RegionA01-vDS-COMP --bridge-network-range 172.16.0.0/12 --public-network VM-RegionA01-vDS-COMP --public-network-ip 192.168.100.22/24 --public-network-gateway 192.168.100.1 --dns-server 192.168.110.10 --container-network VM-RegionA01-vDS-COMP:routable --container-network-firewall VM-RegionA01-vDS-COMP:open --tls-cname vch1.corp.local --organization corp.local --certificate-key-size 2048 --no-tlsverify --whitelist-registry registry.corp.local --whitelist-registry registry.hub.docker.com --registry-ca ca.crt --user Administrator@CORP.LOCAL --thumbprint F7:68:F0:93:F4:EC:B7:FE:C1:02:3F:F3:AB:62:1A:50:E8:9A:0E:85 --target vcsa-01a.corp.local/RegionA01 --ops-user administrator@vsphere.local
```

vic-machine-server.log: 
```
Dec 18 2017 16:40:24.204Z INFO  op=1.16: Request: OPTIONS /container/target/vcsa-01a.corp.local/datacenter/datacenter-21/vch HTTP/1.1
Dec 18 2017 16:40:24.205Z INFO  op=1.16: Response: 200 OK
Dec 18 2017 16:40:24.217Z INFO  op=1.17: Request: POST /container/target/vcsa-01a.corp.local/datacenter/datacenter-21/vch HTTP/1.1
Dec 18 2017 16:40:24.368Z INFO  op=1.17: Validating target
Dec 18 2017 16:40:24.369Z ERROR op=1.17: PANIC: runtime error: invalid memory address or nil pointer dereference
goroutine 55 [running]:
github.com/vmware/vic/lib/apiservers/service/restapi.addPanicRecovery.func1.1(0xc420406f00, 0x1b63520, 0xc4209c1da0)
        /go/src/github.com/vmware/vic/lib/apiservers/service/restapi/configure_vic_machine.go:258 +0x13c
panic(0xf4b5a0, 0x1b46270)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/vmware/vic/lib/apiservers/service/restapi/handlers.buildCreate(0x1b64ca0, 0xc420829e00, 0xc420732fa0, 0x1, 0x1, 0xc420aff4a0, 0x4, 0xc420733220, 0xc420a2cc00, 0x1b58760, ...)
        /go/src/github.com/vmware/vic/lib/apiservers/service/restapi/handlers/vch_create.go:280 +0x1cbb
github.com/vmware/vic/lib/apiservers/service/restapi/handlers.(*VCHDatacenterCreate).Handle(0x1ba9970, 0xc420406f00, 0xc4208a8ad6, 0xd, 0xc4208a8ab7, 0x13, 0xc420aff6f0, 0xc420600500, 0xfa56c0, 0xc420aff690, ...)
        /go/src/github.com/vmware/vic/lib/apiservers/service/restapi/handlers/vch_create.go:117 +0x411
github.com/vmware/vic/lib/apiservers/service/restapi/operations.(*PostTargetTargetDatacenterDatacenterVch).ServeHTTP(0xc4204fefe0, 0x1b63520, 0xc4209c1da0, 0xc420406f00)
        /go/src/github.com/vmware/vic/lib/apiservers/service/restapi/operations/post_target_target_datacenter_datacenter_vch.go:64 +0x344
github.com/vmware/vic/vendor/github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1(0x1b63520, 0xc4209c1da0, 0xc420406f00)
        /go/src/github.com/vmware/vic/vendor/github.com/go-openapi/runtime/middleware/operation.go:24 +0x69
net/http.HandlerFunc.ServeHTTP(0xc4201f3150, 0x1b63520, 0xc4209c1da0, 0xc420406f00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/vmware/vic/vendor/github.com/go-openapi/runtime/middleware.NewRouter.func1(0x1b63520, 0xc4209c1da0, 0xc420406f00)
        /go/src/github.com/vmware/vic/vendor/github.com/go-openapi/runtime/middleware/router.go:75 +0x3b2
net/http.HandlerFunc.ServeHTTP(0xc420634c00, 0x1b63520, 0xc4209c1da0, 0xc420406f00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/vmware/vic/vendor/github.com/go-openapi/runtime/middleware.Redoc.func1(0x1b63520, 0xc4209c1da0, 0xc420406f00)
        /go/src/github.com/vmware/vic/vendor/github.com/go-openapi/runtime/middleware/redoc.go:72 +0xa3
net/http.HandlerFunc.ServeHTTP(0xc42050a940, 0x1b63520, 0xc4209c1da0, 0xc420406f00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/vmware/vic/vendor/github.com/go-openapi/runtime/middleware.Spec.func1(0x1b63520, 0xc4209c1da0, 0xc420406f00)
        /go/src/github.com/vmware/vic/vendor/github.com/go-openapi/runtime/middleware/spec.go:45 +0x82
net/http.HandlerFunc.ServeHTTP(0xc42050a980, 0x1b63520, 0xc4209c1da0, 0xc420406f00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/vmware/vic/vendor/github.com/rs/cors.(*Cors).Handler.func1(0x1b63520, 0xc4209c1da0, 0xc420406f00)
        /go/src/github.com/vmware/vic/vendor/github.com/rs/cors/cors.go:200 +0xe9
net/http.HandlerFunc.ServeHTTP(0xc4206351c0, 0x1b63520, 0xc4209c1da0, 0xc420406f00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/vmware/vic/lib/apiservers/service/restapi.addPanicRecovery.func1(0x1b63520, 0xc4209c1da0, 0xc420406f00)
        /go/src/github.com/vmware/vic/lib/apiservers/service/restapi/configure_vic_machine.go:269 +0x9f
net/http.HandlerFunc.ServeHTTP(0xc420635200, 0x1b63520, 0xc4209c1da0, 0xc420406f00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/vmware/vic/lib/apiservers/service/restapi.addLogging.func1(0x1b64060, 0xc4208861c0, 0xc420406e00)
        /go/src/github.com/vmware/vic/lib/apiservers/service/restapi/configure_vic_machine.go:224 +0x440
net/http.HandlerFunc.ServeHTTP(0xc420635220, 0x1b64060, 0xc4208861c0, 0xc420406e00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
net/http.serverHandler.ServeHTTP(0xc4207f3290, 0x1b64060, 0xc4208861c0, 0xc420406e00)
        /usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4208a8a00, 0x1b64be0, 0xc4209d3f40)
        /usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2668 +0x2ce

Dec 18 2017 16:40:24.369Z INFO  op=1.17: Response: 500 Internal Server Error
```

The server log shows that the panic occurs when trying to grab gateway address from container network:
```
address := net.ParseIP(string(cnetwork.Gateway.Address))
```
Cc: @zjs

**Comment by AngieCris** [comment]
Closed via PR #6982 .
