### ISSUE TITLE
Basic VCH creation fails in the wizard on RC5

### ISSUE THREAD

**Issue by jooskim** [vmware/vic#7011]
**VIC product OVA version:**
RC5: https://storage.googleapis.com/vic-product-ova-releases/vic-v1.3.0-rc5-2996-f8cc7317.ova

**Steps to reproduce:**
1. Deploy the product OVA and finish setting it up
2. Download the VIC Engine tar ball file and install the UI plugin
3. Log out and back into H5 Client and make sure you see the vSphere Integrated Containers icon in the Shortcuts view
4. Go to vSphere Integrated Containers -> Virtual Container Hosts and open the wizard
5. Go through each step with the minimal and basic configurations (e.g. no additional volume, no container network, DHCP for management network, no client SSL certificate validation)

**Actual behavior:**
VCH creation fails with `runtime error: invalid memory address or nil pointer dereference` error message

![image](https://user-images.githubusercontent.com/3834071/34448801-cd94b862-ecb6-11e7-92fe-879b8da7f779.png)

**Expected behavior:**
VCH should be created without any failure

**Logs:**
vic-machine-server log:
```
Dec 29 2017 20:57:45.047Z INFO  op=1.11: Request: OPTIONS /container/target/sc-rdops-vm04-dhcp-123-166.eng.vmware.com/datacenter/datacenter-19/vch HTTP/1.1
Dec 29 2017 20:57:45.048Z INFO  op=1.11: Response: 200 OK
Dec 29 2017 20:57:45.127Z INFO  op=1.12: Request: POST /container/target/sc-rdops-vm04-dhcp-123-166.eng.vmware.com/datacenter/datacenter-19/vch HTTP/1.1
Dec 29 2017 20:57:45.147Z INFO  op=1.12: Validating target
Dec 29 2017 20:57:45.147Z INFO  op=1.12: Generating self-signed certificate/key pair - private key in virtual-container-host/server-key.pem
Dec 29 2017 20:57:45.583Z WARN  op=1.12: Configuring without TLS verify - certificate-based authentication disabled
Dec 29 2017 20:57:45.583Z INFO  op=1.12: Validating supplied configuration
Dec 29 2017 20:57:45.675Z INFO  op=1.12: vDS configuration OK on "bridge"
Dec 29 2017 20:57:45.677Z INFO  op=1.12: vCenter settings check OK
Dec 29 2017 20:57:45.703Z INFO  op=1.12: Firewall status: ENABLED on "/Datacenter/host/Cluster/10.161.44.247"
Dec 29 2017 20:57:45.710Z WARN  op=1.12: Firewall configuration on "/Datacenter/host/Cluster/10.161.44.247" may prevent connection on dst 2377/tcp outbound with allowed IPs: [10.192.214.1]
Dec 29 2017 20:57:45.710Z WARN  op=1.12: Unable to fully verify firewall configuration due to DHCP use on management network
Dec 29 2017 20:57:45.710Z WARN  op=1.12: VCH management interface IP assigned by DHCP must be permitted by allowed IP settings
Dec 29 2017 20:57:45.710Z WARN  op=1.12: Firewall allowed IP configuration may prevent required connection on hosts:
Dec 29 2017 20:57:45.710Z WARN  op=1.12: 	"/Datacenter/host/Cluster/10.161.44.247"
Dec 29 2017 20:57:45.710Z INFO  op=1.12: Firewall must permit dst 2377/tcp outbound to the VCH management interface
Dec 29 2017 20:57:45.712Z INFO  op=1.12: vCenter settings check OK
Dec 29 2017 20:57:45.725Z INFO  op=1.12: License check OK on hosts:
Dec 29 2017 20:57:45.725Z INFO  op=1.12:   "/Datacenter/host/Cluster/10.161.44.247"
Dec 29 2017 20:57:45.727Z INFO  op=1.12: DRS check OK on:
Dec 29 2017 20:57:45.727Z INFO  op=1.12:   "/Datacenter/host/Cluster"
Dec 29 2017 20:57:45.772Z INFO  op=1.12: Creating appliance on target
Dec 29 2017 20:57:45.783Z INFO  op=1.12: Network role "public" is sharing NIC with "management"
Dec 29 2017 20:57:45.783Z INFO  op=1.12: Network role "client" is sharing NIC with "management"
Dec 29 2017 20:57:45.784Z ERROR op=1.12: PANIC: runtime error: invalid memory address or nil pointer dereference
goroutine 56 [running]:
github.com/vmware/vic/lib/apiservers/service/restapi.addPanicRecovery.func1.1(0xc4205d4400, 0x1b69620, 0xc4208aa620)
	/go/src/github.com/vmware/vic/lib/apiservers/service/restapi/configure_vic_machine.go:258 +0x13c
panic(0xf4eae0, 0x1b4c030)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/vmware/vic/lib/install/management.(*Dispatcher).createAppliance.func2(0x1b6b0a0, 0xc420597e40, 0x1b6b0a0, 0xc420597e40, 0x0, 0x0)
	/go/src/github.com/vmware/vic/lib/install/management/appliance.go:506 +0x41
github.com/vmware/vic/pkg/vsphere/tasks.WaitForResult(0x1b6b0a0, 0xc420597e00, 0xc420d6cee0, 0xc420597e00, 0x0, 0x0)
	/go/src/github.com/vmware/vic/pkg/vsphere/tasks/waiter.go:72 +0x10c
github.com/vmware/vic/lib/install/management.(*Dispatcher).createAppliance(0xc4208e22d0, 0xc42049cc00, 0xc420bc3900, 0x0, 0x0)
	/go/src/github.com/vmware/vic/lib/install/management/appliance.go:507 +0x30d
github.com/vmware/vic/lib/install/management.(*Dispatcher).CreateVCH(0xc4208e22d0, 0xc42049cc00, 0xc420bc3900, 0x1b5dee0, 0xc4208aae00, 0x0, 0x0)
	/go/src/github.com/vmware/vic/lib/install/management/create.go:58 +0x1e6
github.com/vmware/vic/lib/apiservers/service/restapi/handlers.handleCreate(0x1b6ada0, 0xc4202eb4a0, 0xc4206ba910, 0x1, 0x1, 0xc420701d20, 0x4, 0xc4206bab90, 0xc42050c900, 0xc4205baa80, ...)
	/go/src/github.com/vmware/vic/lib/apiservers/service/restapi/handlers/vch_create.go:467 +0x683
github.com/vmware/vic/lib/apiservers/service/restapi/handlers.(*VCHDatacenterCreate).Handle(0x1bafa90, 0xc4205d4400, 0xc42027830c, 0xd, 0xc4202782d7, 0x29, 0xc420701f90, 0xc420585100, 0xfa8c80, 0xc420701f30, ...)
	/go/src/github.com/vmware/vic/lib/apiservers/service/restapi/handlers/vch_create.go:122 +0x5f1
github.com/vmware/vic/lib/apiservers/service/restapi/operations.(*PostTargetTargetDatacenterDatacenterVch).ServeHTTP(0xc420329d80, 0x1b69620, 0xc4208aa620, 0xc4205d4400)
	/go/src/github.com/vmware/vic/lib/apiservers/service/restapi/operations/post_target_target_datacenter_datacenter_vch.go:64 +0x344
github.com/vmware/vic/vendor/github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1(0x1b69620, 0xc4208aa620, 0xc4205d4400)
	/go/src/github.com/vmware/vic/vendor/github.com/go-openapi/runtime/middleware/operation.go:24 +0x69
net/http.HandlerFunc.ServeHTTP(0xc420301420, 0x1b69620, 0xc4208aa620, 0xc4205d4400)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/vmware/vic/vendor/github.com/go-openapi/runtime/middleware.NewRouter.func1(0x1b69620, 0xc4208aa620, 0xc4205d4400)
	/go/src/github.com/vmware/vic/vendor/github.com/go-openapi/runtime/middleware/router.go:75 +0x3b2
net/http.HandlerFunc.ServeHTTP(0xc42046a500, 0x1b69620, 0xc4208aa620, 0xc4205d4400)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/vmware/vic/vendor/github.com/go-openapi/runtime/middleware.Redoc.func1(0x1b69620, 0xc4208aa620, 0xc4205d4400)
	/go/src/github.com/vmware/vic/vendor/github.com/go-openapi/runtime/middleware/redoc.go:72 +0xa3
net/http.HandlerFunc.ServeHTTP(0xc4205f4440, 0x1b69620, 0xc4208aa620, 0xc4205d4400)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/vmware/vic/vendor/github.com/go-openapi/runtime/middleware.Spec.func1(0x1b69620, 0xc4208aa620, 0xc4205d4400)
	/go/src/github.com/vmware/vic/vendor/github.com/go-openapi/runtime/middleware/spec.go:45 +0x82
net/http.HandlerFunc.ServeHTTP(0xc4205f4640, 0x1b69620, 0xc4208aa620, 0xc4205d4400)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/vmware/vic/vendor/github.com/rs/cors.(*Cors).Handler.func1(0x1b69620, 0xc4208aa620, 0xc4205d4400)
	/go/src/github.com/vmware/vic/vendor/github.com/rs/cors/cors.go:200 +0xe9
net/http.HandlerFunc.ServeHTTP(0xc4204327e0, 0x1b69620, 0xc4208aa620, 0xc4205d4400)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/vmware/vic/lib/apiservers/service/restapi.addPanicRecovery.func1(0x1b69620, 0xc4208aa620, 0xc4205d4400)
	/go/src/github.com/vmware/vic/lib/apiservers/service/restapi/configure_vic_machine.go:269 +0x9f
net/http.HandlerFunc.ServeHTTP(0xc420432800, 0x1b69620, 0xc4208aa620, 0xc4205d4400)
	/usr/local/go/src
Dec 29 2017 20:57:45.784Z INFO  op=1.12: Response: 500 Internal Server Error
```

Request payload:
```
{"name":"virtual-container-host","compute":{"cpu":{"limit":{"units":"MHz","value":0}},"memory":{"limit":{"units":"MiB","value":0}},"resource":{"name":"/Datacenter/host/Cluster"}},"storage":{"image_stores":["datastore1"],"base_image_size":{"units":"GiB","value":8}},"network":{"bridge":{"ip_range":"172.16.0.0/12","port_group":{"name":"bridge"}},"public":{"port_group":{"name":"management"}}},"auth":{"client":{"no_tls_verify":true},"server":{"generate":{"size":{"value":2048,"units":"bit"},"organization":["virtual-container-host"],"cname":"virtual-container-host"}}},"container":{},"debug":0,"endpoint":{"operations_credentials":{"user":"administrator@vsphere.local","password":"Admin!23"}},"registry":{}}
```

**Comment by AngieCris** [comment]
Confirmed it's about multi-datacenter environment. 
Tested with my VC with two datacenters, one has a single Cluster with a single host, the other one is empty. VCH create with standalone API on datacenter specific endpoint fails with the exact same error:
```
{"message":"runtime error: invalid memory address or nil pointer dereference"}
```
After I delete the empty datacenter from my VC, VCH create with the same params and URL succeeds.

**Comment by AngieCris** [comment]
Root cause identified:
dispatcher session `VMFolder` field is not set (nil). In creating appliance VM, we do:
```
return d.session.VMFolder.CreateVM(ctx, *spec, d.vchPool, d.session.Host)
```
(https://github.com/vmware/vic/blob/master/lib/install/management/appliance.go#L506)
Since `d.session.VMFolder = nil`, calling `CreateVM` on it will result in runtime panic.

The field should be set when creating a new validator in `validator.session.Populate`:
```
	if s.Datacenter != nil {
		folders, err := s.Datacenter.Folders(op)
		if err != nil {
			errs = append(errs, fmt.Sprintf("Failure finding folders (%s): %s", s.DatacenterPath, err.Error()))
		} else {
			op.Debugf("Cached folders: %s", s.DatacenterPath)
		}
		s.VMFolder = folders.VmFolder
	}
```
https://github.com/vmware/vic/blob/master/pkg/vsphere/session/session.go#L352-L358
However since on API side, validator doesn't get the target URL path, so it doesn't know the dc path and the dc object. Thus the datacenter is just nil, and so we never set the VMFolder. (that's different from CLI, where we actually have target URL host **and** path, so the validator always knows the dc path)
On API side we only manually set the dc object outside of validator. So the fix would be manually set the VMFolder as well, outside of validator.
PR: 

**Why it works in single-dc environment**
Under single-dc, on API side, the validator still doesn't get the target URL path.
But when finding the dc object, the validator grabs the default by listing all dc's and use it if there's only one, or just return error if there're multiple. So under single-dc, the dc object will just default to be the only one. Under multi-dc, we have an error, and the dc is never set. 
We actually see such error in the log:
```
Jan  1 2018 01:34:04.745-08:00 DEBUG new validator Session.Populate: Failure finding dc (): default datacenter resolves to multiple instances, please specify
Failure finding cluster (): please specify a datacenter
Failure finding ds (): please specify a datacenter
Failure finding host (): please specify a datacenter
Failure finding pool (): please specify a datacenter
```
It's basically saying it's multi-dc and it doesn't know which to choose.

Cc: @hickeng @zjs

**Comment by lgayatri** [comment]
With RC5, even I am hitting this issue.

![image](https://user-images.githubusercontent.com/25006749/34480617-7fe7b536-efd3-11e7-8379-ceaa3f2f0c63.png)

**Comment by jooskim** [comment]
@lgayatri As far as I remember about your VC setup you have more than one DC so you're probably hitting the same issue.
