### ISSUE TITLE
VC HA fail over is not fully integrated with VIC.

### ISSUE THREAD

**Issue by vburenin** [vmware/vic#7504]
**User Statement:**
While trying to reproduce #6667 issue, I started bunch of containers and paused ESXi that was running VCH. VCH has been successfully migrated to another ESXi, so everything was recovered correctly. 
After that I stopped and removed several containers. Everything went just fine.
Then I enabled the paused ESXi, it got back online and back-up VCH was automatically removed leaving original one in place. Starting from this moment I was able to see running containers that I started and removed before. However, I could not delete them getting error back saying that container doesn't exists.

```
vmware/vic [6667-bug●] » docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                      PORTS               NAMES
e1bafe4ccd29        ubuntu              "/usr/bin/top"      2 hours ago         Up 28 minutes                                   priceless_sammet
bbf6d4b83ea6        ubuntu              "/bin/bash"         3 hours ago         Exited (0) 29 minutes ago                       angry_mcnulty
06701dcec70c        ubuntu              "/bin/top"          3 hours ago         Stopped                                         youthful_kirch
cc844ccff760        busybox             "/bin/top"          3 hours ago         Up 31 minutes                                   elated_wing
vmware/vic [6667-bug●] » docker rm 06701dcec70c
Error: No such container: 06701dcec70c
```

I suspect there are a lot more not functional pieces.

**Details:**
Repro steps:
1. Enable DRS and HA on VC.
2. Deploy VCH
3. Start a few containers like docker run -dti busybox /bin/top
4. Pause/Disconnect ESXi that is running VCH.
5. Wait when a new VCH is started.
6. Stop and delete running container.
7. Unpause/Connect ESXi paused in step 4.
8. Newly deployed VCH back should disappear and old one should take over.
9. Try to delete container.

**Acceptance Criteria:**
If VCH gets added back to the cluster, it should recover its state to be up to date with the fresh state. Everything should be functional as usual.

**Comment by vburenin** [comment]
while trying to reproduce this issue, there docker persona stopped responding to get list of containers producing following stacktrace:
```
ar 22 2018 19:24:27.322Z DEBUG Calling GET /v1.23/containers/json?all=1
Mar 22 2018 19:24:27.322Z DEBUG [BEGIN]  [vic/lib/apiservers/engine/backends.(*ContainerBackend).Containers:1328] ListOptions &types.ContainerListOptions{Quiet:false, Size:false, All:true, Latest:false, Since:"", Before:"", Limit:0, Filters:filters.Args{fields:map[string]map[string]bool{}}}
Mar 22 2018 19:24:27.324Z DEBUG [ END ]  [vic/lib/apiservers/engine/backends.(*ContainerBackend).Containers:1328] [1.691567ms] ListOptions &types.ContainerListOptions{Quiet:false, Size:false, All:true, Latest:false, Since:"", Before:"", Limit:0, Filters:filters.Args{fields:map[string]map[string]bool{}}}
2018-03-22 19:24:27.324222 I | http: panic serving 10.84.232.126:50941: runtime error: invalid memory address or nil pointer dereference
goroutine 405 [running]:
net/http.(*conn).serve.func1(0xc420c454a0)
	/usr/local/go/src/net/http/server.go:1726 +0xd0
panic(0x1a8f220, 0x2ffcbf0)
	/usr/local/go/src/runtime/panic.go:505 +0x229
github.com/vmware/vic/lib/apiservers/engine/network.PortForwardingInformation(0x0, 0xc42041f5d0, 0x1, 0x1, 0x0, 0x1, 0x8)
	/go/src/github.com/vmware/vic/lib/apiservers/engine/network/utils.go:567 +0x667
github.com/vmware/vic/lib/apiservers/engine/backends.(*ContainerBackend).Containers(0xc4204ac930, 0xc420f9c340, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/vmware/vic/lib/apiservers/engine/backends/container.go:1405 +0x1005
github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/container.(*containerRouter).getContainersJSON(0xc4206f0100, 0x7f7cfb74c5b0, 0xc4206e9920, 0x2025880, 0xc4207b97a0, 0xc420f94700, 0xc4206e9890, 0x2027b00, 0xc4206e9920)
	/go/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/container/container_routes.go:50 +0x201
github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/container.getContainersJSON)-fm(0x7f7cfb74c5b0, 0xc4206e9920, 0x2025880, 0xc4207b97a0, 0xc420f94700, 0xc4206e9890, 0x7f7cfb74c5b0, 0xc4206e9920)
	/go/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/container/container.go:44 +0x69
github.com/vmware/vic/vendor/github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x7f7cfb74c5b0, 0xc4206e98f0, 0x2025880, 0xc4207b97a0, 0xc420f94700, 0xc4206e9890, 0x402875, 0x1ff4510)
	/go/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/middleware/version.go:47 +0x440
github.com/vmware/vic/vendor/github.com/docker/docker/api/server/middleware.DebugRequestMiddleware.func1(0x7f7cfb74c5b0, 0xc4206e98f0, 0x2025880, 0xc4207b97a0, 0xc420f94700, 0xc4206e9890, 0x7f7cfb74c5b0, 0xc4206e98f0)
	/go/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/middleware/debug.go:22 +0x161
github.com/vmware/vic/vendor/github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x2025880, 0xc4207b97a0, 0xc420f94700)
	/go/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/server.go:139 +0x1c6
net/http.HandlerFunc.ServeHTTP(0xc4207812c0, 0x2025880, 0xc4207b97a0, 0xc420f94700)
	/usr/local/go/src/net/http/server.go:1947 +0x44
github.com/vmware/vic/vendor/github.com/docker/docker/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420d35720, 0x2025880, 0xc4207b97a0, 0xc420f94700)
	/go/src/github.com/vmware/vic/vendor/github.com/docker/docker/vendor/github.com/gorilla/mux/mux.go:103 +0x226
github.com/vmware/vic/vendor/github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc42047d960, 0x2025880, 0xc4207b97a0, 0xc420f94700)
	/go/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router_swapper.go:29 +0x70
net/http.serverHandler.ServeHTTP(0xc420d52a90, 0x2025880, 0xc4207b97a0, 0xc420f94700)
	/usr/local/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc420c454a0, 0x2027a40, 0xc420f9c200)
	/usr/local/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2795 +0x27b
```

**Comment by vburenin** [comment]
it looks like this issue takes longer to resolve only on the host that was paused not that was physically disconnected if I leave it to run it for couple minutes it recovers the state.

closing it for now.
