### ISSUE TITLE
Nightly-6.0-5-22-NFS-Volume - Nimbus Pod is unavailable

### ISSUE THREAD

**Issue by rajanashok** [vmware/vic#7642]
```Suite setup failed:
Keyword 'Setup ESX And NFS Suite' failed after retrying 10 times. The last error was: '2018-04-03 23:42:52 -0700: VM resource requirement: cpu - 1 VCPU(s), mem - 1024 MB, disk - 41943040 KB
2018-04-03 23:42:52 -0700: /mts/git/nimbus/lib/nimbus/deploys/nfs/nfs_deploy.rb, "NFS-292099.490703"
2018-04-03 23:42:52 -0700: sc-prd-rdops-nimbusgateway001 pid 56042
2018-04-03 23:42:52 -0700: USER: svc.victestuser
2018-04-03 23:42:52 -0700: id: uid=2000540(svc.victestuser) gid=201 groups=201

2018-04-03 23:42:52 -0700: logname: svc.victestuser

2018-04-03 23:42:52 -0700: Git version for /mts/git/: heads/staging-0-g5dc9da5
2018-04-03 23:42:52 -0700: Git version for /mts/git/nimbus: heads/staging-0-g33f2ee5
2018-04-03 23:42:52 -0700: Git version for /mts/git/nimbus-configs: heads/staging-0-g8dafca4
2018-04-03 23:42:53 -0700: Git version for /mts/git/rbvmomi: heads/staging-0-g142d4a3
2018-04-03 23:42:53 -0700: Git version for /mts/git/rbvmomi-utils: heads/master-0-gad4be2b
    [ Message content over the limit has been removed. ]
    "/mts/git/nimbus-toolchain/lin64/ruby/2.2.0/lib/ruby/2.2.0/timeout.rb:34:in `block in catch'",
    "/mts/git/nimbus-toolchain/lin64/ruby/2.2.0/lib/ruby/2.2.0/timeout.rb:34:in `catch'",
    "/mts/git/nimbus-toolchain/lin64/ruby/2.2.0/lib/ruby/2.2.0/timeout.rb:34:in `catch'",
    "/mts/git/nimbus-toolchain/lin64/ruby/2.2.0/lib/ruby/2.2.0/timeout.rb:104:in `timeout'",
    "/mts/git/nimbus-toolchain/lin64/ruby/2.2.0/lib/ruby/2.2.0/timeout.rb:125:in `timeout'",
    "/mts/git/nimbus/lib/nimbus/base_deploy.rb:622:in `run_cli'",
    "/mts/git/bin/../nimbus/lib/nimbus/deploys/nfs/nfs_deploy.rb:225:in `<main>'"
  ]
}
--- end nimbus json results ---
2018-04-03 23:42:53 -0700: Terminating VIM connection ...
2018-04-03 23:42:53 -0700: Exception: NimbusExceptionUnavailablePod: Pod is unavailable - Specified pod ["sc-prd-vc049"] is busy and cannot take any new load.' does not contain 'To manage this VM use'```

**Comment by mhagen-vmware** [comment]
as discussed with @rajanashok the solution to this is to build a full NFS test bed instead of relying on the unsupported pod placement calls
