### ISSUE TITLE
Unexpected EOF pulling image after interrupt and restart of endpointVM

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#8029]
When pulling image wdc-harbor-ci.eng.vmware.com/default-project/db2wh_ce:v2.8.0-db2wh_devc-linux
(this is from store/ibmcorp/db2wh_ce:v2.8.0-db2wh_devc-linux but saved to local repo as it's large).

Initial pull portion (unfortunately I didn't grab logs before the restart of the endpointVM):
```console
v2.8.0-db2wh_devc-linux: Pulling from default-project/db2wh_ce
6fd64836e300: Already exists
a3ed95caeb02: Pull complete
428d13ffdbc3: Already exists
66abb0836c06: Already exists
54066518fb70: Already exists
b9a5fe58a825: Already exists
b018a5c68deb: Already exists
612b82ab0cd5: Already exists
db01d3160376: Already exists
ade9c593f556: Already exists
1a35eb5ff099: Already exists
5fbc9ecb4ea6: Already exists
15822065b4dd: Already exists
6a1a3387f6e2: Already exists
8cc994fe803c: Already exists
7e8209f751fb: Already exists
be7bd3c19c16: Already exists
a4f29ed22a7e: Already exists
215c8e18fcc5: Already exists
369afc933ef5: Already exists
636cb6f699e3: Already exists
8ec6ac67ce50: Already exists
1668831e87ee: Already exists
1dd5fbd86170: Already exists
6181303cabbe: Already exists
069633a3716c: Pull complete
ac58fe57574f: Pull complete
0605b38b036a: Pull complete
adbdc38d1a2b: Pull complete
4acdb30c93a8: Pull complete
8477efb2a871: Pull complete
a7e955f8c6da: Pull complete
73333654ea03: Pull complete
b9e807a61fa7: Pull complete
9205657eee78: Pull complete
16f04a2c223c: Pull complete
9de3fbdd896c: Pull complete
74108d7f7771: Pull complete
e9ea9ff4fbaf: Pull complete
cb5c7130fce9: Pull complete
ef5a6d764a46: Downloading [========================================>          ]  272.7MB/340MB
04f1b0580601: Download complete
72eb4f63fafb: Download complete
37c9f1c6b092: Download complete
9a83d9678870: Download complete
b4be261175f3: Download complete
4036a9b5ec29: Download complete
0de243c29311: Download complete
8fd20c7c548f: Download complete

^C
```

Rerun of the pull after endpointVM restart:
```console
v2.8.0-db2wh_devc-linux: Pulling from default-project/db2wh_ce
6fd64836e300: Already exists
a3ed95caeb02: Already exists
428d13ffdbc3: Already exists
66abb0836c06: Already exists
54066518fb70: Already exists
b9a5fe58a825: Already exists
b018a5c68deb: Already exists
612b82ab0cd5: Already exists
db01d3160376: Already exists
ade9c593f556: Already exists
1a35eb5ff099: Already exists
5fbc9ecb4ea6: Already exists
15822065b4dd: Already exists
6a1a3387f6e2: Already exists
8cc994fe803c: Already exists
7e8209f751fb: Already exists
be7bd3c19c16: Already exists
a4f29ed22a7e: Already exists
215c8e18fcc5: Already exists
369afc933ef5: Already exists
636cb6f699e3: Already exists
8ec6ac67ce50: Already exists
1668831e87ee: Already exists
1dd5fbd86170: Already exists
6181303cabbe: Already exists
069633a3716c: Already exists
ac58fe57574f: Already exists
0605b38b036a: Already exists
adbdc38d1a2b: Already exists
4acdb30c93a8: Already exists
8477efb2a871: Already exists
a7e955f8c6da: Already exists
73333654ea03: Already exists
b9e807a61fa7: Already exists
9205657eee78: Already exists
16f04a2c223c: Already exists
9de3fbdd896c: Already exists
74108d7f7771: Already exists
e9ea9ff4fbaf: Already exists
cb5c7130fce9: Already exists
unexpected EOF
```

This shows the following panic in the personality:
```
Jun  7 2018 01:33:21.864Z DEBUG [ END ]  [vic/lib/imagec.(*LayerDownloader).DownloadLayers:107] [914.491778ms] 
Jun  7 2018 01:33:21.864Z DEBUG [ END ]  [vic/lib/apiservers/engine/backends.(*ImageBackend).PullImage:323] [7.86949726s] 
2018-06-07 01:33:21.864189 I | http: panic serving 192.168.78.215:60102: runtime error: invalid memory address or nil pointer dereference
goroutine 62 [running]:
net/http.(*conn).serve.func1(0xc42074ca00)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0x1ca8760, 0x3143ba0)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/vmware/vic/lib/imagec.(*LayerDownloader).DownloadLayers(0xc4204e8f20, 0x3188c80, 0xc420704360, 0xc420a51cc0, 0x0, 0x0)
	/home/vagrant/vicsmb/src/github.com/vmware/vic/lib/imagec/download.go:190 +0x814
github.com/vmware/vic/lib/imagec.(*ImageC).PullImage(0xc420a51cc0, 0x0, 0x0)
	/home/vagrant/vicsmb/src/github.com/vmware/vic/lib/imagec/imagec.go:494 +0x328
github.com/vmware/vic/lib/apiservers/engine/backends.(*ImageBackend).PullImage(0x31e7488, 0x7f00a84d7e90, 0xc4201a6880, 0xc4201a6900, 0x35, 0xc42062a0f2, 0x17, 0xc42043c720, 0xc4204058f0, 0x316c6c0, ...)
	/home/vagrant/vicsmb/src/github.com/vmware/vic/lib/apiservers/engine/backends/image.go:402 +0x836
github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/image.(*imageRouter).postImagesCreate(0xc420345640, 0x7f00a84d7e90, 0xc4201a6880, 0x3186c80, 0xc420559b20, 0xc4202de200, 0xc42043c510, 0x0, 0x0)
	/home/vagrant/vicsmb/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/image/image_routes.go:109 +0x51c
github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/image.(*imageRouter).(github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/image.postImagesCreate)-fm(0x7f00a84d7e90, 0xc4201a6880, 0x3186c80, 0xc420559b20, 0xc4202de200, 0xc42043c510, 0x1d99ba0, 0x3188cc0)
	/home/vagrant/vicsmb/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/image/image.go:43 +0x69
github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router.cancellableHandler.func1(0x7f00a84e59c0, 0xc42043c600, 0x3186c80, 0xc420559b20, 0xc4202de200, 0xc42043c510, 0x0, 0x0)
	/home/vagrant/vicsmb/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/local.go:84 +0xda
github.com/vmware/vic/vendor/github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x7f00a84e59c0, 0xc42043c5a0, 0x3186c80, 0xc420559b20, 0xc4202de200, 0xc42043c510, 0xc420c23ab0, 0x756ea15c140bfa)
	/home/vagrant/vicsmb/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/middleware/version.go:47 +0x50b
github.com/vmware/vic/vendor/github.com/docker/docker/api/server/middleware.DebugRequestMiddleware.func1(0x7f00a84e59c0, 0xc42043c5a0, 0x3186c80, 0xc420559b20, 0xc4202de200, 0xc42043c510, 0x7f00a84e59c0, 0xc42043c5a0)
	/home/vagrant/vicsmb/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/middleware/debug.go:25 +0x992
github.com/vmware/vic/vendor/github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x3186c80, 0xc420559b20, 0xc4202de200)
	/home/vagrant/vicsmb/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/server.go:139 +0x21a
net/http.HandlerFunc.ServeHTTP(0xc4205046a0, 0x3186c80, 0xc420559b20, 0xc4202de200)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/vmware/vic/vendor/github.com/docker/docker/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc42059c8c0, 0x3186c80, 0xc420559b20, 0xc4202de200)
	/home/vagrant/vicsmb/src/github.com/vmware/vic/vendor/github.com/docker/docker/vendor/github.com/gorilla/mux/mux.go:103 +0x255
github.com/vmware/vic/vendor/github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc4205892d0, 0x3186c80, 0xc420559b20, 0xc4202de200)
	/home/vagrant/vicsmb/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router_swapper.go:29 +0x70
net/http.serverHandler.ServeHTTP(0xc4202642c0, 0x3186c80, 0xc420559b20, 0xc4202de200)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc42074ca00, 0x3188c00, 0xc4201a6400)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
github.com/vmware/vic/vendor/github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc4205892d0, 0x3186c80, 0xc420559b20, 0xc4202de200)
	/home/vagrant/vicsmb/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router_swapper.go:29 +0x70
net/http.serverHandler.ServeHTTP(0xc4202642c0, 0x3186c80, 0xc420559b20, 0xc4202de200)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc42074ca00, 0x3188c00, 0xc4201a6400)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
```

[logs.zip](https://github.com/vmware/vic/files/2078669/logs.15.zip)

**Comment by hickeng** [comment]
Current hypothesis is that we are persisting whether the layer is downloading, but not purging that state when reloading the layer cache. This is occurring because [this member is exported](https://github.com/vmware/vic/blob/0645e42c6fcf1d02dc16afeee2bd83736782367b/lib/imagec/imagec.go#L128).

I'm unclear on whether it's deliberate that the downloading state is intentionally or unintentionally persisted.

**Comment by hickeng** [comment]
The following delta seems to have addressed the issue but I do not know if it's the _correct_ fix or just a work around. This drops layer cache entries marked with Downloading when initializing from saved state on the assumption that they are explicitly incomplete:
```diff
diff --git a/lib/imagec/layer_cache.go b/lib/imagec/layer_cache.go
index caed471..e68ffd9 100644
--- a/lib/imagec/layer_cache.go
+++ b/lib/imagec/layer_cache.go
@@ -89,6 +89,19 @@ func InitializeLayerCache(client *client.PortLayer) error {
                layerCache.layers = l.Layers
        }

+       // Sanitize cache - evict inconsistent elements
+       evict := make([]string, 0, len(l.Layers))
+       // build the list for evication - we should not iterate and modify in the same loop
+       for k, v := range l.Layers {
+               if v.Downloading {
+                       evict = append(evict, k)
+               }
+       }
+
+       for _, k := range evict {
+               layerCache.Remove(k)
+       }
+
        return nil
 }

```
We may instead want to do a state sanity check between the `ldm.downloadsByID` (which is managed by `registerDownload`) and the `layer.Download` state - the appropriate approach is dependent on whether [this should be an else or is deliberately leaving that inconsistency in place](https://github.com/vmware/vic/blob/0645e42c6fcf1d02dc16afeee2bd83736782367b/lib/imagec/download.go#L175)

With the delta it suggests that we are lacking an endpointVM crash test during layer download - any layer download - as this would be a very easy situation to get into.

**Comment by jzt** [comment]
@hickeng I think your solution should work. I confess I haven't thought through all the implications thoroughly, but I think dealing with it in the `else` clause you mentioned might be problematic as there could be a [separate instance](https://github.com/vmware/vic/blob/master/lib/apiservers/engine/backends/image.go#L362) of imagec/download manager downloading that particular layer (vs. just being in an inconsistent state after the service fell over). That would make sense as to why the `Downloading` field is exported. I think your fix is the right place to handle it because after the service goes down/comes back up, there should be no active downloads/download managers running during initialization.

**Comment by hickeng** [comment]
PR #8032 addresses the restartability portion. This issue is left open to look at the download stall behaviour.
