### ISSUE TITLE
Unable to provision containers - hitting "Maximum number of retries exceeded"

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic#8090]
#For stories, please include the information below:

**User Statement:**
Build: https://storage.cloud.google.com/vic-product-ova-releases/vic-v1.4.1-rc1-5422-f52b38e5.ova

Attempt to provision nginx  container failed with "Maximum number of retries exceeded"

**Details:**
xenon log says:
```
[206947][F][2018-06-25T09:36:59.861Z][2602][8282/][processContainerHealth][Container's health config not set for: /resources/container-descriptions/discovered-efc12da7-bb8e-42e4-a12f-3c6bc692eb21]
[206948][F][2018-06-25T09:36:59.861Z][2602][8282/][processContainerHealth][Container's health config not set for: /resources/container-descriptions/discovered-bfa6cdbf-9adc-4118-a3f4-74d6a4e8bfeb]
[206929][F][2018-06-25T09:36:59.858Z][2595][8282/][processContainerHealth][Container's health config not set for: /resources/container-descriptions/discovered-82145537-0776-4873-8a6f-657b36309e48]
[206949][F][2018-06-25T09:37:00.380Z][1189][8282/][log][Task 'start-container-d5c855a8afcc0b7726badb96433b1f6e967fc5b00380ea318aaa6a35d72edc54' failed to produce result: java.lang.RuntimeException: Service https://10.197.37.141:2376/v1.24/containers/d5c855a8afcc0b7726badb96433b1f6e967fc5b00380ea318aaa6a35d72edc54/start returned error 500 for POST. id 1712471 message Server error from portlayer: Attempted to power on the wrong number of VMs. Expected 1, attempted 0; Reason: {"message":"Server error from portlayer: Attempted to power on the wrong number of VMs. Expected 1, attempted 0"}

        at com.vmware.admiral.adapter.docker.service.DockerAdapterUtils.runtimeExceptionFromFailedDockerOperation(DockerAdapterUtils.java:187)
        at com.vmware.admiral.adapter.docker.service.DockerAdapterService.lambda$null$59(DockerAdapterService.java:1596)
        at com.vmware.xenon.common.Operation.completeOrFail(Operation.java:1340)
        at com.vmware.xenon.common.Operation.fail(Operation.java:1318)
        at com.vmware.xenon.common.Operation.fail(Operation.java:1243)
        at com.vmware.xenon.common.http.netty.NettyHttpServiceClient.fail(NettyHttpServiceClient.java:725)
        at com.vmware.xenon.common.http.netty.NettyHttpServiceClient.lambda$sendHttpRequest$1(NettyHttpServiceClient.java:580)
        at com.vmware.xenon.common.Operation.lambda$nestCompletion$1(Operation.java:1371)
        at com.vmware.xenon.common.Operation.completeOrFail(Operation.java:1340)
        at com.vmware.xenon.common.Operation.fail(Operation.java:1318)
        at com.vmware.xenon.common.Operation.fail(Operation.java:1243)

```
![image](https://user-images.githubusercontent.com/25006749/41843622-9e01b79c-788b-11e8-938a-95afd152bfc6.png)

**Acceptance Criteria:**
This operation should be successful.

Log bundle attached.
[vic_appliance_logs_2018-06-25-09-44-21.tar.gz](https://github.com/vmware/vic/files/2132625/vic_appliance_logs_2018-06-25-09-44-21.tar.gz)

@hickeng @lazarin 

**Acceptance (dev)**

Needed changes:
- [ ] "wrong number of VMs" - this is an abysmal message to give to the user, should be changed to at least provide _some_ indication as to what actually happened. The [vm power](https://github.com/vmware/vic/blob/b8eeb5c35f6fa2816cfaf82385ea1698a5a70543/pkg/vsphere/vm/vm.go#L974) code needs to run through the `notAttempted` array in the results to unpack the actual error for the VM in question.
- [ ] we report generation of a `die` event on the start errors. Either:
  - [ ] do not report a die event (error from start is sufficient), or
  - [ ] do *not* have an exit code of `0`, as this indicates success.

**Comment by lgayatri** [comment]
[container-logs.zip](https://github.com/vmware/vic/files/2132636/container-logs.zip) Logs from the VCH are attached here

**Comment by hickeng** [comment]
We have the following in persona:
```
Jun 25 2018 09:37:00.763Z ERROR Operation failed with errors.apiError{error:(*errors.errorString)(0xc4201ded10), statusCode:500}
Jun 25 2018 09:37:00.763Z ERROR Handler for POST /v1.24/containers/d5c855a8afcc0b7726badb96433b1f6e967fc5b00380ea318aaa6a35d72edc54/start returned error: Server error from portlayer: Attempted to power on the wrong number of VMs. Expected 1, attempted 0
Jun 25 2018 09:37:00.777Z INFO  Sending die event for container(d5c855a8afcc) with exitCode[0] - eventID(300.743)
```
and portlayer shows the same:
```
Jun 25 2018 09:36:59.858Z INFO  op=300.743: Reconfigure: attempting update to d5c855a8afcc0b7726badb96433b1f6e967fc5b00380ea318aaa6a35d72edc54 with change version "2018-06-25T09:36:57.77489Z" (poweredOff)
Jun 25 2018 09:37:00.426Z INFO  op=300.743: Reconfigure: committed update to d5c855a8afcc0b7726badb96433b1f6e967fc5b00380ea318aaa6a35d72edc54 with change version: 2018-06-25T09:36:57.77489Z
Jun 25 2018 09:37:00.427Z INFO  op=300.743: Attempting to perform a guest reconfigure operation on (d5c855a8afcc0b7726badb96433b1f6e967fc5b00380ea318aaa6a35d72edc54)
Jun 25 2018 09:37:00.760Z ERROR op=300.743: CommitHandler error on handle(20b7a1a38a530c957d4f93e956d24c59) for d5c855a8afcc0b7726badb96433b1f6e967fc5b00380ea318aaa6a35d72edc54: Attempted to power on the wrong number of VMs. Expected 1, attempted 0
```

However of note is that this does not appear to be unique to the nginx container mentioned. We first have an error about exceeding the maximum vCPU limit, then we have this same "wrong numer of VMs" return for all subsequent operations.

@lgayatri Initial maximum CPU error was seen for three containers before transforming into the "wrong number of VMs" message:
1. `b85609ef`
2. `21b5cebe`
3. `6e438e5d`

These all failed with the error:
```
Maximum virtual CPUs limit reached: 512 (32768 worlds).
```

I am updating the initial issue to have necessary updates recorded there so they're not lost in the comments.

Questions:
- [ ] should the die event be returned given we must be returning an error via the start command?
- [ ] why did the test not fail reporting the maximum CPU errors?
- [ ] why do we _stop_ reporting the maximum vCPU limit error - this is a much more useful error that actually tells the user something actionable.

**Comment by zjs** [comment]
Deferring to 1.4.2. As this is important and worth fixing, it is not a regression over 1.4.0.

**Comment by lgayatri** [comment]
Defer accepted.

**Comment by renmaosheng** [comment]
we should also do some monitoring on the resources, and report if the resource is exceeding the limits.

**Comment by hickeng** [comment]
The necessary changes have been noted in the updated issue description - this is:
1. update the vm power on code to unpack the actual error from vSphere
2. ensure that docker events is correct (either die event or no event).
