### ISSUE TITLE
Nimbus scenario tests home directory quota issue

### ISSUE THREAD

**Issue by DanielXiao** [vmware/vic#8189]
**Details**
5-5-Heterogeneous-ESXi always fails because user home directory exceeds quota during downloading pxe images. nimbus-esxdeploy returns below error:

[2018-08-07 03:38:09,734] pxe-deploy:153 - <module>: Exception: Failed in deploying /mts/home5/svc.vicproduct1/public_html/pxe/8935087/bora-8935087/mboot.efi from http://build-squid.eng.vmware.com/build/mts/release/bora-8935087/publish/pxe-modules/mboot.efi: [Errno 122] Disk quota exceeded. Traceback (most recent call last): File "/build/apps/bin/pxe-deploy", line 148, in <module> exit(main()) File "/build/apps/bin/pxe-deploy", line 126, in main image.Deploy(deployer) File "/bldmnt/trees/release/toolseng/devtools/deploy/image.py", line 117, in Deploy join(self.image_id(), name), True) File "/bldmnt/trees/release/toolseng/devtools/deploy/pxesuite.py", line 252, in deploy_file dst, src, str(download_error) or '(unknown)' Exception: Failed in deploying /mts/home5/svc.vicproduct1/public_html/pxe/8935087/bora-8935087/mboot.efi from http://build-squid.eng.vmware.com/build/mts/release/bora-8935087/publish/pxe-modules/mboot.efi: [Errno 122] Disk quota exceeded. 2018-08-07 03:38:09 -0700: RbVmomiUtils::PxeDeployError: pxe-deploy failed : /build/apps/bin/pxe-deploy preferredDeploy=copy force_tftp=True pxedir=/mts/home5/svc.vicproduct1/public_html/pxe/8935087 buildnum=8935087 pxe_abspath=True 2>&1

**Comment by DanielXiao** [comment]
use --pxe-base-dir can specify a different directory but the directory is required accessible by pxe server

**Comment by DanielXiao** [comment]
This issue is fixed by setting deletePXE=${true}

**Comment by zjs** [comment]
Re-opening as #8237 indicates that it fixes this issue, but is still open.
