### ISSUE TITLE
Null pointer or invalid reference seen with the following log/stacktrace

### ISSUE THREAD

**Issue by lcastellano** [vmware/vic#8214]
Running against ESX.

Log:
```
Aug 15 2018 17:14:00.212Z DEBUG Found 2 subscribers to 199: vsphere.VMEvent - Removed nifty_goldwasser-316ab37018fb on localhost.localdomain from ha-datacenter
Aug 15 2018 17:14:00.262Z DEBUG Event manager calling back to exec for Event(199): vsphere.VMEvent
Aug 15 2018 17:14:00.262Z DEBUG Event manager calling back to logging for Event(199): vsphere.VMEvent
Aug 15 2018 17:14:00.262Z DEBUG [BEGIN]  [vic/lib/portlayer/logging.eventCallback:58]
Aug 15 2018 17:14:00.262Z DEBUG [ END ]  [vic/lib/portlayer/logging.eventCallback:58] [19.173µs] 
Aug 15 2018 17:14:00.263Z DEBUG op=368.122: [NewOperation] op=368.122 [vic/lib/portlayer/exec.(*Container).OnEvent:705]
Aug 15 2018 17:14:00.263Z DEBUG [BEGIN] op=368.122 [vic/lib/portlayer/exec.(*Container).OnEvent:706] eventID(199) received for event: Removed
Aug 15 2018 17:14:00.263Z INFO  op=368.122: Container(316ab37018fb5c7404e92ce034b4381e1648374cf615b2688501968ce6b4c74d) in state: Stopped, has received unexpected Removed event
Aug 15 2018 17:14:00.427Z DEBUG Found 2 subscribers to 200: vsphere.VMEvent - Removed silly_blackwell-75575afe715e on localhost.localdomain from ha-datacenter
Aug 15 2018 17:14:00.427Z DEBUG Event manager calling back to exec for Event(200): vsphere.VMEvent
Aug 15 2018 17:14:00.427Z DEBUG Event manager calling back to logging for Event(200): vsphere.VMEvent
Aug 15 2018 17:14:00.427Z DEBUG [BEGIN]  [vic/lib/portlayer/logging.eventCallback:58]
Aug 15 2018 17:14:00.427Z DEBUG [ END ]  [vic/lib/portlayer/logging.eventCallback:58] [8.274µs] 
Aug 15 2018 17:14:00.428Z DEBUG op=368.122: container(316ab37018fb5c7404e92ce034b4381e1648374cf615b2688501968ce6b4c74d) vmExists, InventoryPath: /ha-datacenter/vm/nifty_goldwasser-316ab37018fb
Aug 15 2018 17:14:00.676Z DEBUG [ END ] op=368.122 [vic/lib/portlayer/exec.(*Container).OnEvent:706] [413.321695ms] eventID(199) received for event: Removed
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xd2ce88]
#For stories, please include the information below:
```

Stack trace:
```
goroutine 21 [running]:
github.com/vmware/vic/lib/portlayer/exec.(*Container).vmExists(0xc420ce1100, 0x1e1b200, 0xc4207fc180, 0xc4207ff8b0, 0x1, 0x1, 0xc4202f5e10, 0x7, 0x0, 0xc4210cfb00, ...)
    /home/vagrant/vicsmb/src/github.com/vmware/vic/lib/portlayer/exec/container.go:852 +0x488
github.com/vmware/vic/lib/portlayer/exec.(*Container).onEvent(0xc420ce1100, 0x1e1b200, 0xc4207fc180, 0xc4207ff8b0, 0x1, 0x1, 0xc4202f5e10, 0x7, 0x0, 0xa, ...)
    /home/vagrant/vicsmb/src/github.com/vmware/vic/lib/portlayer/exec/container.go:802 +0x787
github.com/vmware/vic/lib/portlayer/exec.(*Container).OnEvent(0xc420ce1100, 0x1e1ec20, 0xc420444248)
    /home/vagrant/vicsmb/src/github.com/vmware/vic/lib/portlayer/exec/container.go:716 +0x3bb
github.com/vmware/vic/lib/portlayer/exec.Init.func1.2(0x1e1ec20, 0xc420444248)
    /home/vagrant/vicsmb/src/github.com/vmware/vic/lib/portlayer/exec/exec.go:132 +0x86
github.com/vmware/vic/lib/portlayer/event.newSubscriber.func1(0xc4209ced20)
    /home/vagrant/vicsmb/src/github.com/vmware/vic/lib/portlayer/event/subscriber.go:113 +0x194
created by github.com/vmware/vic/lib/portlayer/event.newSubscriber
    /home/vagrant/vicsmb/src/github.com/vmware/vic/lib/portlayer/event/subscriber.go:119 +0x12a
```

**Comment by hickeng** [comment]
Seen in: https://ci-vic.vmware.com/vmware/vic/19837/7
Testcase: `Delete VCH without deleting powered on container`

Fails with:
```
'SIGSEGV: segmentation violation'
```
