### ISSUE TITLE
Docker stats message channel meet panic error

### ISSUE THREAD

**Issue by wjun** [vmware/vic#8400]
During the tests in #8399 , there are several same panic messages as below:

==========docker-personality.log-20181113-1542134551==========
 Nov 13 2018 17:34:11.805Z ERROR container metric conversion error for container(45459de093dd1e35f5b5277f0960636b2f3003c0d91ee4160441cdd906c1ea3f): The current sample time (2018-11-13 17:33:40 +0000 UTC) is before the previous time (2018-11
 -13 17:34:00 +0000 UTC)
 panic: send on closed channel
 
 goroutine 87234 [running]:
 github.com/vmware/vic/lib/apiservers/engine/backends/convert.(*ContainerStats).Listen.func2(0xc42074a930, 0xc421028fc0, 0xc420f00000)
         /go/src/github.com/vmware/vic/lib/apiservers/engine/backends/convert/stats.go:169 +0x21e
 created by github.com/vmware/vic/lib/apiservers/engine/backends/convert.(*ContainerStats).Listen
         /go/src/github.com/vmware/vic/lib/apiservers/engine/backends/convert/stats.go:175 +0x181

Bugzilla#2238550

**Comment by wjun** [comment]
The direct triage looks it seems like we need to return after the cancel on line 165 of stats.go. 

Ideally, we should look at the portlayer side of this operation to understand what occurred there leading to this error; it's possible there's an issue there as well.
