### ISSUE TITLE
The VIC Appliance is initializing

### ISSUE THREAD

**Issue by gogasca** [vmware/vic#8609]
Just deployed: vic-v1.5.4-7589-e70af4fe.ova
Used Public IP address, DNS, NTP 

![image](https://user-images.githubusercontent.com/30065079/71933650-8c100f80-3157-11ea-919a-7fdf6ce5a29f.png)

I get:

```
The VIC Appliance is initializing
VIC Appliance services are starting. This may take several minutes.

Please try again shortly.```

Tried install multiple times, same error.

ESXi:
```
Version:
6.5.0 Update 1 (Build 7967591)
State:
Normal (not connected to any vCenter Server)
```

**Comment by renmaosheng** [comment]
Hi gogasca ,
       could you please share logs? thanks.

**Comment by kevinfealey** [comment]
I'm also seeing this - here is the error:
```
root@localhost [ / ]# journalctl -u vic-appliance-environment.service
-- Logs begin at Tue 2020-07-21 12:44:58 UTC, end at Tue 2020-07-21 14:53:54 UTC. --
Jul 21 13:26:08 localhost systemd[1]: Starting VIC Appliance Environment...
Jul 21 13:26:09 localhost vic-appliance-environment.sh[367]: Hostname is null, using IP
Jul 21 13:26:09 localhost vic-appliance-environment.sh[367]: Using hostname: <redacted>
Jul 21 13:26:09 localhost chpasswd[506]: pam_unix(chpasswd:chauthtok): password changed for root
Jul 21 13:26:09 localhost vic-appliance-environment.sh[367]: panic: runtime error: invalid memory address or nil pointer dereference
Jul 21 13:26:09 localhost vic-appliance-environment.sh[367]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9b1210]
Jul 21 13:26:09 localhost vic-appliance-environment.sh[367]: goroutine 1 [running]:
Jul 21 13:26:09 localhost vic-appliance-environment.sh[367]: main.main.func1(0xc420078580, 0xc420078580, 0xc42004bc0f)
Jul 21 13:26:09 localhost vic-appliance-environment.sh[367]:         /go/src/github.com/vmware/vic-product/installer/ovatools/ovfenv/main.go:93 +0x960
Jul 21 13:26:09 localhost vic-appliance-environment.sh[367]: github.com/vmware/vic-product/installer/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0xaac260, 0xcc07c0, 0xc420078580, 0xc4200741
e0, 0x0)
Jul 21 13:26:09 localhost vic-appliance-environment.sh[367]:         /go/src/github.com/vmware/vic-product/installer/vendor/gopkg.in/urfave/cli.v1/app.go:490 +0xd2
Jul 21 13:26:09 localhost vic-appliance-environment.sh[367]: github.com/vmware/vic-product/installer/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc420068820, 0xc420010140, 0x5, 0x5, 0x0, 0x0
)
Jul 21 13:26:09 localhost vic-appliance-environment.sh[367]:         /go/src/github.com/vmware/vic-product/installer/vendor/gopkg.in/urfave/cli.v1/app.go:264 +0x635
Jul 21 13:26:09 localhost vic-appliance-environment.sh[367]: main.main()
Jul 21 13:26:09 localhost vic-appliance-environment.sh[367]:         /go/src/github.com/vmware/vic-product/installer/ovatools/ovfenv/main.go:133 +0x39b
Jul 21 13:26:09 localhost systemd[1]: vic-appliance-environment.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 21 13:26:09 localhost systemd[1]: Failed to start VIC Appliance Environment.
Jul 21 13:26:09 localhost systemd[1]: vic-appliance-environment.service: Unit entered failed state.
Jul 21 13:26:09 localhost systemd[1]: vic-appliance-environment.service: Failed with result 'exit-code'.
```

**Comment by kevinfealey** [comment]
Installing vCenter Server resolved this issue immediately. This leads me to believe there is an issue in the instructions here: https://vmware.github.io/vic-product/assets/files/html/0.8/vic_installation/deploy_vch_esxi.html since this is what I followed.

**Comment by Egyras** [comment]
so how to use without vcenter server, were to get runtime bundle that to use on standalone ESXi ?

**Comment by Egyras** [comment]
> so how to use without vcenter server, were to get runtime bundle that to use on standalone ESXi ?

just found in appliance required runtime /opt/vmware/fileserver/files/
