### ISSUE TITLE
[docker-server] runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by caglar10ur** [vmware/vic#913]
docker-engine-server crashes with following on my system. The trace points to convertV1ImageToDockerImage function call. 
```
2016/05/31 17:12:17 http: panic serving 192.168.218.141:33002: runtime error: invalid memory address or nil pointer dereference
goroutine 37 [running]:
net/http.(*conn).serve.func1(0xc820f59b80)
	/usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0xebe780, 0xc820010070)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/vmware/vic/lib/apiservers/engine/backends.(*Image).Images(0xc820493680, 0x0, 0x0, 0x0, 0x0, 0x1271700, 0x0, 0x0, 0x0, 0x0, ...)
	/opt/go/src/github.com/vmware/vic/lib/apiservers/engine/backends/image.go:104 +0x709
github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/image.(*imageRouter).getImagesJSON(0xc820634cc0, 0x7fe8493d8400, 0xc820f70600, 0x7fe8493d4218, 0xc821074000, 0xc820f2c540, 0xc820f70570, 0x0, 0x0)
	/opt/go/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/image/image_routes.go:313 +0x1a7
github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/image.(*imageRouter).(github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/image.getImagesJSON)-fm(0x7fe8493d8400, 0xc820f70600, 0x7fe8493d4218, 0xc821074000, 0xc820f2c540, 0xc820f70570, 0x0, 0x0)
	/opt/go/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/image/image.go:29 +0x74
github.com/vmware/vic/vendor/github.com/docker/docker/api/server/middleware.NewVersionMiddleware.func1.1(0x7fe8493d8400, 0xc820f70600, 0x7fe8493d4218, 0xc821074000, 0xc820f2c540, 0xc820f70570, 0x0, 0x0)
	/opt/go/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/middleware/version.go:42 +0xa43
github.com/vmware/vic/vendor/github.com/docker/docker/api/server/middleware.NewUserAgentMiddleware.func1.1(0x7fe8493d8348, 0xc8200113e8, 0x7fe8493d4218, 0xc821074000, 0xc820f2c540, 0xc820f70570, 0x0, 0x0)
	/opt/go/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/middleware/user_agent.go:32 +0x491
github.com/vmware/vic/vendor/github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7fe8493d4218, 0xc821074000, 0xc820f2c540)
	/opt/go/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/server.go:132 +0x138
net/http.HandlerFunc.ServeHTTP(0xc82063c160, 0x7fe8493d4218, 0xc821074000, 0xc820f2c540)
	/usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/vmware/vic/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc820632fa0, 0x7fe8493d4218, 0xc821074000, 0xc820f2c540)
	/opt/go/src/github.com/vmware/vic/vendor/github.com/gorilla/mux/mux.go:103 +0x270
github.com/vmware/vic/vendor/github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc8207deab0, 0x7fe8493d4218, 0xc821074000, 0xc820f2c540)
	/opt/go/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router_swapper.go:29 +0x72
net/http.serverHandler.ServeHTTP(0xc82062c200, 0x7fe8493d4218, 0xc821074000, 0xc820f2c540)
	/usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820f59b80)
	/usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2137 +0x44e
```

**Comment by caglar10ur** [comment]
That's how I ended up in this state
```
[vagrant@ubuntu-1604-vmware:/opt/go/src/github.com/vmware/vic(master)] docker -H 192.168.218.142:2376 --tls --tlscert='./ZzZ-cert.pem' --tlskey='./ZzZ-key.pem' pull golang
Using default tag: latest
latest: Pulling from library/golang
112699cac682: Pull complete
fdd5d7827f33: Pull complete
a3ed95caeb02: Pull complete
0f35d0fe50cc: Pull complete
7b40647e93b7: Pull complete
ef089453c5ae: Pull complete
d4648ccf073a: Pull complete
5da110fdd918: Pull complete
Status: Downloaded newer image for library/golang:latest
[vagrant@ubuntu-1604-vmware:/opt/go/src/github.com/vmware/vic(master)] docker -H 192.168.218.142:2376 --tls --tlscert='./ZzZ-cert.pem' --tlskey='./ZzZ-key.pem' images 
An error occurred trying to connect: Get https://192.168.218.142:2376/v1.23/images/json?all=1: EOF
```

**Comment by mhagen-vmware** [comment]
The integration tests are seeing this now too, I think this just happened with:
#804

**Comment by caglar10ur** [comment]
I don't htink #804 is related. We are doing this @lib/apiservers/engine/backends/image.go
```
func convertV1ImageToDockerImage(v1Image *v1.V1Image) *types.Image {
    return &types.Image{
        ID:       v1Image.ID,
        ParentID: v1Image.Parent,
        RepoTags: []string{"<fixme>:<fixme>"}, // TODO(jzt): replace with actual tags
        //RepoDigests: []string{"<fixme>:<fixme>"},
        Created:     v1Image.Created.Unix(),
        VirtualSize: v1Image.Size,
        Labels:      v1Image.Config.Labels,
    }
}
```
but there are some images with no label, eg;

```
"6ffc5fd0a51f3bd4619bcc23afaf5f8949942e36dbaa220dbbd93738a170e0f1": *{
        ID: "6ffc5fd0a51f3bd4619bcc23afaf5f8949942e36dbaa220dbbd93738a170e0f1",
        Parent: "16030ee67f7d788cddb9cbdbdb446e05dda6e4d76fddc148beee96b39014e539",
        Comment: "",
        Created: (*time.Time)(0xc82079e8f0),
        Container: "",
        ContainerConfig: (*github.com/vmware/vic/vendor/github.com/docker/engine-api/types/container.Config)(0xc82079e918),
        DockerVersion: "",
        Author: "",
        Config: *github.com/vmware/vic/vendor/github.com/docker/engine-api/types/container.Config nil,
        Architecture: "",
        OS: "",
        Size: 0,},
```
so trying to get v1Image.Config.Labels panics

**Comment by jzt** [comment]
I will push a quick fix for now that will fix any integration test issues. Most of this code will be changed very soon, just FYI.
